In [1]:
import numpy as np
import pandas as pd

In [10]:
borehole = pd.read_excel('Paradiseview/Paradise View Expenditures 4.xlsx', sheet_name='Borehole', skiprows=3)

In [11]:
borehole.head()

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,STARTED($),STARTED(D),Unnamed: 8,Unnamed: 9
0,Bore Drilling,1.0,95000.0,95000.0,1507.936508,2023-06-24,2000.0,126000.0,NaN,NaN
1,Carpenter,1.0,6500.0,6500.0,103.174603,2023-06-25,NaN,NaN,NaN,NaN
2,Kaye Rod,34.0,180.0,6120.0,97.142857,2023-06-25,NaN,NaN,NaN,NaN
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,170.634921,2023-06-25,NaN,NaN,NaN,NaN
4,Big Nale(kg),3.0,100.0,300.0,4.761905,2023-06-25,NaN,NaN,NaN,NaN

In [20]:
borehole.dropna(thresh=3, axis=1, inplace=True)

In [22]:
borehole

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,Bore Drilling,1.0,95000.0,95000.0,1507.936508,2023-06-24
1,Carpenter,1.0,6500.0,6500.0,103.174603,2023-06-25
2,Kaye Rod,34.0,180.0,6120.0,97.142857,2023-06-25
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,170.634921,2023-06-25
4,Big Nale(kg),3.0,100.0,300.0,4.761905,2023-06-25
5,Small Nale(Packs),3.0,350.0,1050.0,16.666667,2023-06-25
6,Wood for Doors,5.0,300.0,1500.0,23.809524,2023-06-25
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,25.396825,2023-06-25
8,Delivering Guys,1.0,800.0,800.0,12.698413,2023-06-25
9,Leftover,1.0,2380.0,2380.0,37.777778,NaT
10,NaN,NaN,NaN,NaN,NaN,NaT
11,NaN,NaN,NaN,NaN,NaN,NaT
12,NaN,NaN,NaN,NaN,NaN,NaT
13,NaN,NaN,NaN,NaN,NaN,NaT
14,Total,NaN,NaN,126000.0,2000.000000,NaT
15,NaN,NaN,NaN,NaN,NaN,NaT
16,1 Dollar = 63 Dalasis,NaN,NaN,NaN,NaN,NaT

In [33]:
borehole.dropna(thresh=(len(borehole.columns) - 1), axis=0, inplace=True)

In [34]:
# Change the columns strings to lowercase unsing String Vectorization
borehole.columns = borehole.columns.str.lower()

In [35]:
borehole.columns

Index(['item', 'quantity ', 'unit price(d)', 'total cost(d)', 'cost($)',
       'date'],
      dtype='str')

In [37]:
borehole = borehole.rename(columns={'unit price(d)': 'unti_cost', 'total cost(d)': 'total_cost'})

In [41]:
# Perminantly drop the cost($) column fromn the dataset
borehole.drop(columns='cost($)', inplace=True)

In [44]:
borehole

,item,quantity,unti_cost,total_cost,date
0,Bore Drilling,1.0,95000.0,95000.0,2023-06-24
1,Carpenter,1.0,6500.0,6500.0,2023-06-25
2,Kaye Rod,34.0,180.0,6120.0,2023-06-25
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,2023-06-25
4,Big Nale(kg),3.0,100.0,300.0,2023-06-25
5,Small Nale(Packs),3.0,350.0,1050.0,2023-06-25
6,Wood for Doors,5.0,300.0,1500.0,2023-06-25
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,2023-06-25
8,Delivering Guys,1.0,800.0,800.0,2023-06-25
9,Leftover,1.0,2380.0,2380.0,NaT

In [45]:
# Chabge the misinput date to correct date
borehole.at[9, 'date'] = '2023-06-25'

In [46]:
borehole

,item,quantity,unti_cost,total_cost,date
0,Bore Drilling,1.0,95000.0,95000.0,2023-06-24
1,Carpenter,1.0,6500.0,6500.0,2023-06-25
2,Kaye Rod,34.0,180.0,6120.0,2023-06-25
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,2023-06-25
4,Big Nale(kg),3.0,100.0,300.0,2023-06-25
5,Small Nale(Packs),3.0,350.0,1050.0,2023-06-25
6,Wood for Doors,5.0,300.0,1500.0,2023-06-25
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,2023-06-25
8,Delivering Guys,1.0,800.0,800.0,2023-06-25
9,Leftover,1.0,2380.0,2380.0,2023-06-25

In [50]:
borehole['date'].dtype

dtype('<M8[us]')

In [51]:
# Check the datatype of date column
np.dtype(borehole['date'])

dtype('<M8[us]')

In [56]:
borehole['date'] = borehole['date'].dt.strftime('%m/%d/%Y')

In [61]:
# Assign 'Residual to index #9 from the item column
borehole.at[9, 'item'] = 'Residual'

In [83]:
borehole.tail()

,item,quantity,unti_cost,total_cost,date,sub_category,category
5,Small Nale(Packs),3.0,350.0,1050.0,06/25/2023,Borehole Drilling,Preconstruction
6,Wood for Doors,5.0,300.0,1500.0,06/25/2023,Borehole Drilling,Preconstruction
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,06/25/2023,Borehole Drilling,Preconstruction
8,Delivering Guys,1.0,800.0,800.0,06/25/2023,Borehole Drilling,Preconstruction
9,Residual,1.0,2380.0,2380.0,06/25/2023,Borehole Drilling,Preconstruction

In [74]:
# Create two new columns

borehole['sun_category'] = 'Borehole Drilling'
borehole['category'] = 'Preconstruction'

In [77]:
borehole.rename(columns={'sun_category': 'sub_category'}, inplace=True)

In [78]:
borehole.head()

,item,quantity,unti_cost,total_cost,date,sub_category,category
0,Bore Drilling,1.0,95000.0,95000.0,06/24/2023,Borehole Drilling,Preconstruction
1,Carpenter,1.0,6500.0,6500.0,06/25/2023,Borehole Drilling,Preconstruction
2,Kaye Rod,34.0,180.0,6120.0,06/25/2023,Borehole Drilling,Preconstruction
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,06/25/2023,Borehole Drilling,Preconstruction
4,Big Nale(kg),3.0,100.0,300.0,06/25/2023,Borehole Drilling,Preconstruction

In [84]:
# Save the dataFrame to csv file
borehole.to_csv('ParadiseView/out/df_borehole_drilling.csv', index=False)

In [2]:
# Read the csv dataset from file
df = pd.read_csv('ParadiseView/out/df_borehole_drilling.csv')

In [3]:
df.columns

Index(['item', 'quantity ', 'unti_cost', 'total_cost', 'date', 'sub_category',
       'category'],
      dtype='str')

In [4]:
# rename the columns names in order and remove the empty space
df.rename(columns={'quantity ': 'quantity', 'unti_cost': 'unit_cost'}, inplace=True)

In [5]:
df.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category',
       'category'],
      dtype='str')

In [6]:
df = df.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [7]:
# Create a new column called 'exchange_rate' and assigned 63.00 to its rows
df['exchange_rate'] = 63.00

In [8]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Bore Drilling,1.0,95000.0,95000.0,06/24/2023,Borehole Drilling,Preconstruction,63.0
1,Carpenter,1.0,6500.0,6500.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
2,Kaye Rod,34.0,180.0,6120.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
4,Big Nale(kg),3.0,100.0,300.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
5,Small Nale(Packs),3.0,350.0,1050.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
6,Wood for Doors,5.0,300.0,1500.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
8,Delivering Guys,1.0,800.0,800.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
9,Residual,1.0,2380.0,2380.0,06/25/2023,Borehole Drilling,Preconstruction,63.0

In [10]:
df['date'] = pd.to_datetime(df['date'])

In [11]:
df.to_csv('ParadiseView/out/df_borehole_drill.csv', index=False)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           10 non-null     str
 1   quantity       10 non-null     float64
 2   unit_cost      10 non-null     float64
 3   total_cost     10 non-null     float64
 4   date           10 non-null     datetime64[us]
 5   sub_category   10 non-null     str
 6   category       10 non-null     str
 7   exchange_rate  10 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 772.0 bytes

In [14]:
df= pd.read_csv('ParadiseView/out/df_borehole_drill.csv')

In [15]:
print(df.to_string())

                                     item  quantity  unit_cost  total_cost        date       sub_category         category  exchange_rate
0                           Bore Drilling       1.0    95000.0     95000.0  2023-06-24  Borehole Drilling  Preconstruction           63.0
1                               Carpenter       1.0     6500.0      6500.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
2                                Kaye Rod      34.0      180.0      6120.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
3         Polycarbonate Roof Panel(Packs)       2.5     4300.0     10750.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
4                            Big Nale(kg)       3.0      100.0       300.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
5                       Small Nale(Packs)       3.0      350.0      1050.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
6                          Wood for Doors       5.0      300.0      1500.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
7  Cutting Mango Branch and Moving Bricks       1.0     1600.0      1600.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
8                         Delivering Guys       1.0      800.0       800.0  2023-06-25  Borehole Drilling  Preconstruction           63.0
9                                Residual       1.0     2380.0      2380.0  2023-06-25  Borehole Drilling  Preconstruction           63.0