In [97]:
import numpy as np
import pandas as pd
from datetime import datetime, date

In [98]:
# Read the data from excel sheet
contractor_consul = pd.read_excel('ParadiseView/Paradise View Expenditures 4.xlsx', sheet_name='Consultation', skiprows= 4)

In [99]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,Unnamed: 6,Unnamed: 7
0,Consulting Contractors,1,4000,4000,65.04065,2023-09-25 00:00:00,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total,NaN,4000,4000,65.04065,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 Dollar = 61.5 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Preparing Land for Construction,NaN,NaN,NaN,NaN,NaN,"D12,000 sent on 12/20/23"
9,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,NaN,187.5
10,Clearing the Area,1,8000,8000,125,2023-12-21 00:00:00,NaN,NaN
11,Transportation,1,2000,2000,31.25,2023-12-21 00:00:00,NaN,Sent D64000 on 12/24/2023 that is $100
12,Total,NaN,10000,10000,156.25,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Other Expenses,NaN,NaN,NaN,NaN,NaN,NaN
21,WHO,AMOUNT(D),AMOUNT($),DATE,NaN,NaN,NaN,NaN
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Total,2000,31.25,NaN,NaN,NaN,NaN,NaN
25,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
# drop two unwanted columns
contractor_consul.drop(columns=['Unnamed: 6', 'Unnamed: 7'], inplace=True)

In [101]:
# drop the cost($) column
contractor_consul.drop(columns='COST($)', inplace=True)

In [102]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),DATE
0,Consulting Contractors,1,4000,4000,2023-09-25 00:00:00
1,NaN,NaN,NaN,NaN,NaN
2,Total,NaN,4000,4000,NaN
3,NaN,NaN,NaN,NaN,NaN
4,1 Dollar = 61.5 Dalasis,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN
8,NaN,Preparing Land for Construction,NaN,NaN,NaN
9,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),DATE
10,Clearing the Area,1,8000,8000,2023-12-21 00:00:00
11,Transportation,1,2000,2000,2023-12-21 00:00:00
12,Total,NaN,10000,10000,NaN
13,NaN,NaN,NaN,NaN,NaN
14,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN
20,NaN,Other Expenses,NaN,NaN,NaN
21,WHO,AMOUNT(D),AMOUNT($),DATE,NaN
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Total,2000,31.25,NaN,NaN
25,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN

In [103]:
# Permanentely drop missing data and keep rows with atmost 4 non-missing columns
contractor_consul.dropna(thresh = (len(contractor_consul.columns) - 2), axis=0, inplace=True)

In [104]:
# pass a list of indeces to be dropped fron the dataset
contractor_consul = contractor_consul.drop(index=[2,9,12,21,24])

In [105]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),DATE
0,Consulting Contractors,1,4000,4000,2023-09-25 00:00:00
10,Clearing the Area,1,8000,8000,2023-12-21 00:00:00
11,Transportation,1,2000,2000,2023-12-21 00:00:00
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN

In [106]:
# change the column names to lowecase and rename them to desire column names
contractor_consul.columns =contractor_consul.columns.str.lower()
contractor_consul.rename(columns={'quantity ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [107]:
contractor_consul.loc[22, 'date'] ='2023-12-20 00:00:00'

In [108]:
# access and change values of columns to desire values
contractor_consul.loc[22, 'quantity'] = 1
contractor_consul.loc[22, 'unit_cost'] = 2000
contractor_consul.loc[22, 'total_cost'] = 2000

In [109]:
contractor_consul

                      item quantity unit_cost total_cost                 date
0   Consulting Contractors        1      4000       4000  2023-09-25 00:00:00
10       Clearing the Area        1      8000       8000  2023-12-21 00:00:00
11         Transportation         1      2000       2000  2023-12-21 00:00:00
22            Bubacarr Fai        1      2000       2000  2023-12-20 00:00:00

In [110]:
contractor_consul['date'] = pd.to_datetime(contractor_consul['date'])

In [111]:
contractor_consul['date'] = contractor_consul['date'].dt.strftime('%m/%d/%Y')

In [112]:
# create three new collumns
contractor_consul['sub_category'] = 'Contractor Consultation'
contractor_consul['category'] = 'Preconstruction'
contractor_consul['exchange_rate'] = 61.50

In [113]:
contractor_consul.loc[1:, 'exchange_rate'] = 64.00

In [114]:
contractor_consul

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Consulting Contractors,1,4000,4000,09/25/2023,Contractor Consultation,Preconstruction,61.5
10,Clearing the Area,1,8000,8000,12/21/2023,Contractor Consultation,Preconstruction,64.0
11,Transportation,1,2000,2000,12/21/2023,Contractor Consultation,Preconstruction,64.0
22,Bubacarr Fai,1,2000,2000,12/20/2023,Contractor Consultation,Preconstruction,64.0

In [115]:
# change the date column to datatime object
contractor_consul['date'] = pd.to_datetime(contractor_consul['date'])

In [116]:
# save the file as a csv file
contractor_consul.to_csv('ParadiseView/out/df_contractor_consul.csv', index=False)

In [117]:
contractor_consul = pd.read_csv('ParadiseView/out/df_contractor_consul.csv')

In [118]:
contractor_consul

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Consulting Contractors,1,4000,4000,2023-09-25,Contractor Consultation,Preconstruction,61.5
1,Clearing the Area,1,8000,8000,2023-12-21,Contractor Consultation,Preconstruction,64.0
2,Transportation,1,2000,2000,2023-12-21,Contractor Consultation,Preconstruction,64.0
3,Bubacarr Fai,1,2000,2000,2023-12-20,Contractor Consultation,Preconstruction,64.0