In [37]:
import pandas as pd
import numpy as np

In [38]:
# list of rows tobe dropped
skiprows = [0,1,2,3,6,7,8,9,10,22,23,24,25]

In [39]:
# read an excel file into cost_date
cost_data = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx", skiprows=skiprows)

In [40]:
cost_data

                             ITEM  COST(D)      COST($)        DATE
0   Paradise View Plot: 20m x 25m   750000  15000.000000 2019-08-03
1                 Physical Plan 1     1500     30.612245 2019-08-09
2                 Physical Plan 2     1000     20.408163 2019-12-17
3                    MoneyTra Fee      490     10.000000 2020-02-06
4                 Physical Plan 2     2000     40.816327 2020-02-07
5                      GTBank Fee     5000    102.040816 2020-02-07
6                     Gas for Car      500     10.204082 2020-02-07
7             Chief Area Council      2000     40.816327 2020-02-10
8                     Gas for Car      500     10.204082 2020-02-10
9               Lady Filled Forms      400      8.163265 2020-02-10
10                  Sukuta Alkalo     1500     30.612245 2020-02-11
11                            Gas      100      2.040816 2020-02-11

In [41]:
# rename some of the columns 
cost_data.rename(columns={'COST(D)': 'cost_dalasi', 'COST($) ': 'cost_dollar'}, inplace=True)

In [42]:
cost_data

                             ITEM  cost_dalasi   cost_dollar       DATE
0   Paradise View Plot: 20m x 25m       750000  15000.000000 2019-08-03
1                 Physical Plan 1         1500     30.612245 2019-08-09
2                 Physical Plan 2         1000     20.408163 2019-12-17
3                    MoneyTra Fee          490     10.000000 2020-02-06
4                 Physical Plan 2         2000     40.816327 2020-02-07
5                      GTBank Fee         5000    102.040816 2020-02-07
6                     Gas for Car          500     10.204082 2020-02-07
7             Chief Area Council          2000     40.816327 2020-02-10
8                     Gas for Car          500     10.204082 2020-02-10
9               Lady Filled Forms          400      8.163265 2020-02-10
10                  Sukuta Alkalo         1500     30.612245 2020-02-11
11                            Gas          100      2.040816 2020-02-11

In [43]:
# change the columns names to lowercase string
cost_data.columns = cost_data.columns.str.lower()

In [44]:
# change date column's datatype to datetime object
cost_data['date'] = pd.to_datetime(cost_data['date'])

In [45]:
# change the format of the date column to month/day/year
cost_data['date'] = cost_data['date'].dt.strftime("%m/%d/%Y")

In [46]:
cost_data

                             item  cost_dalasi   cost_dollar        date
0   Paradise View Plot: 20m x 25m       750000  15000.000000  08/03/2019
1                 Physical Plan 1         1500     30.612245  08/09/2019
2                 Physical Plan 2         1000     20.408163  12/17/2019
3                    MoneyTra Fee          490     10.000000  02/06/2020
4                 Physical Plan 2         2000     40.816327  02/07/2020
5                      GTBank Fee         5000    102.040816  02/07/2020
6                     Gas for Car          500     10.204082  02/07/2020
7             Chief Area Council          2000     40.816327  02/10/2020
8                     Gas for Car          500     10.204082  02/10/2020
9               Lady Filled Forms          400      8.163265  02/10/2020
10                  Sukuta Alkalo         1500     30.612245  02/11/2020
11                            Gas          100      2.040816  02/11/2020

In [47]:
# drop the cost_dollar column as it is not needed
df_cost = cost_data.drop(columns='cost_dollar')

In [48]:
df_cost

                             item  cost_dalasi        date
0   Paradise View Plot: 20m x 25m       750000  08/03/2019
1                 Physical Plan 1         1500  08/09/2019
2                 Physical Plan 2         1000  12/17/2019
3                    MoneyTra Fee          490  02/06/2020
4                 Physical Plan 2         2000  02/07/2020
5                      GTBank Fee         5000  02/07/2020
6                     Gas for Car          500  02/07/2020
7             Chief Area Council          2000  02/10/2020
8                     Gas for Car          500  02/10/2020
9               Lady Filled Forms          400  02/10/2020
10                  Sukuta Alkalo         1500  02/11/2020
11                            Gas          100  02/11/2020

In [50]:
# rename cost_dalasi column to cost
df_cost.rename(columns={'cost_dalasi': 'cost'}, inplace=True)

In [ ]:
# save the dataset as aa csv file
df_cost.to_csv('ParadiseView/out/df_cost_clean.csv', index=False)

In [12]:
import pandas as pd
import numpy as np

In [11]:
# Read the csv file and assign it to df
df = pd.read_csv('ParadiseView/out/df_cost_clean.csv')

In [4]:
df

                             item    cost        date
0   Paradise View Plot: 20m x 25m  750000  08/03/2019
1                 Physical Plan 1    1500  08/09/2019
2                 Physical Plan 2    1000  12/17/2019
3                    MoneyTra Fee     490  02/06/2020
4                 Physical Plan 2    2000  02/07/2020
5                      GTBank Fee    5000  02/07/2020
6                     Gas for Car     500  02/07/2020
7             Chief Area Council     2000  02/10/2020
8                     Gas for Car     500  02/10/2020
9               Lady Filled Forms     400  02/10/2020
10                  Sukuta Alkalo    1500  02/11/2020
11                            Gas     100  02/11/2020

In [5]:
# Access the column names
df.columns

Index(['item', 'cost', 'date'], dtype='str')

In [7]:
# Rename the column cost to total_cost
df.rename(columns={'cost': 'total_cost'}, inplace=True)

In [32]:
# Create four new columns
df['unit_cost'] = df['total_cost']
df['quantity'] = 1
df['sub_category'] = 'Registration'
df['category'] = 'Buying'

In [30]:
# Reindex the columns to a desire arragement
df = df.reindex(columns = ['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [45]:
# Locate index 0 of 'sub_category' collumn and assign 'cost' to it
df.loc[0, 'sub_category'] = 'Cost'

In [21]:
# Conditionally change from the values of 'item' columns 
df['item'] = np.where(df['item'] == 'Physical Plan 1', 'Physical Plan Guy 1', df['item'])

In [24]:
df['item'] = np.where(df['item'] == 'Physical Plan 2', 'Physical Plan Guy 2', df['item'])

In [41]:
df['exchange_rate'] = 49.00

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           12 non-null     str
 1   quantity       12 non-null     int64
 2   unit_cost      12 non-null     int64
 3   total_cost     12 non-null     int64
 4   date           12 non-null     datetime64[us]
 5   sub_category   12 non-null     str
 6   category       12 non-null     str
 7   exchange_rate  12 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 900.0 bytes

In [37]:
# Change the date column from string to datetime object
df['date'] = pd.to_datetime(df['date'])

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           12 non-null     str
 1   quantity       12 non-null     int64
 2   unit_cost      12 non-null     int64
 3   total_cost     12 non-null     int64
 4   date           12 non-null     datetime64[us]
 5   sub_category   12 non-null     str
 6   category       12 non-null     str
 7   exchange_rate  12 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 900.0 bytes

In [48]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Paradise View Plot: 20m x 25m,1,750000,750000,2019-08-03,Cost,Buying,49.0
1,Physical Plan Guy 1,1,1500,1500,2019-08-09,Registration,Buying,49.0
2,Physical Plan Guy 2,1,1000,1000,2019-12-17,Registration,Buying,49.0
3,MoneyTra Fee,1,490,490,2020-02-06,Registration,Buying,49.0
4,Physical Plan Guy 2,1,2000,2000,2020-02-07,Registration,Buying,49.0
5,GTBank Fee,1,5000,5000,2020-02-07,Registration,Buying,49.0
6,Gas for Car,1,500,500,2020-02-07,Registration,Buying,49.0
7,Chief Area Council,1,2000,2000,2020-02-10,Registration,Buying,49.0
8,Gas for Car,1,500,500,2020-02-10,Registration,Buying,49.0
9,Lady Filled Forms,1,400,400,2020-02-10,Registration,Buying,49.0
10,Sukuta Alkalo,1,1500,1500,2020-02-11,Registration,Buying,49.0
11,Gas,1,100,100,2020-02-11,Registration,Buying,49.0

In [49]:
# Save the dataset as a csv file
df.to_csv('ParadiseView/out/df_cost.csv', index=False)