In [4]:
# import pandas and numpy libraries
import pandas as pd 
import numpy as np

In [25]:
# read an excel file into df_fencing
df_fencing = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx", skiprows=6, sheet_name="Fencing")

In [26]:
# display the dataset
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30,NaN,NaN,NaN
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30,NaN,NaN,NaN
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30,NaN,NaN,NaN
3,Cement,40,285,11400,232.653061,2020-05-06,NaN,NaN,NaN
4,Cement Transport,1,600,600,12.244898,2020-05-06,NaN,NaN,NaN
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06,NaN,NaN,NaN
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06,NaN,NaN,NaN
7,Water for Molding,1,1000,1000,20.408163,2020-05-06,NaN,NaN,NaN
8,Gas for Transport,1,450,450,9.183673,2020-05-06,NaN,NaN,NaN
9,Police Ticket,1,200,200,4.081633,2020-04-29,NaN,NaN,NaN
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08,NaN,NaN,NaN
11,Cement,25,285,7125,145.408163,2020-05-08,NaN,NaN,NaN
12,Cement Transport,25,15,375,7.653061,2020-05-08,NaN,NaN,NaN
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08,NaN,NaN,NaN
14,Gas for Transport,1,200,200,4.081633,2020-05-08,NaN,NaN,NaN
15,Iron Rods,—,4550,4550,92.857143,2020-05-10,NaN,NaN,NaN
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10,NaN,NaN,NaN
17,Gas for Transport,1,125,125,2.551020,2020-05-10,NaN,NaN,NaN
18,Gas for Transport,1,400,400,8.163265,2020-05-16,NaN,NaN,NaN
19,Electric Pipes,4,35,140,2.857143,2020-05-16,NaN,NaN,NaN
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16,NaN,NaN,NaN
21,Kilo of Nales,2,60,120,2.448980,2020-05-16,NaN,NaN,NaN
22,Taxi Fare,1,250,250,5.102041,2020-05-16,NaN,NaN,NaN
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16,NaN,NaN,NaN
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16,NaN,NaN,NaN
25,Cement,—,285,1150,23.469388,2020-05-22,NaN,NaN,NaN
26,Gas for Transport,1,200,200,4.081633,2020-05-22,NaN,NaN,NaN
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22,NaN,NaN,NaN
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22,NaN,NaN,NaN
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22,NaN,NaN,NaN
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22,NaN,NaN,NaN
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22,NaN,NaN,NaN
32,Lock for Gate,1,250,250,5.102041,2020-05-22,NaN,NaN,NaN
33,Gate,1,26000,26000,530.612245,2020-05-22,NaN,NaN,NaN
34,Cement,5,285,1425,29.081633,2020-05-22,NaN,NaN,NaN
35,Cement Transport,5,15,75,1.530612,2020-05-22,NaN,NaN,NaN
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24,NaN,NaN,NaN
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24,NaN,NaN,NaN
38,Finishing,1,1000,1000,20.408163,2020-06-23,NaN,NaN,NaN
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
41,Total,NaN,NaN,112635,2298.673469,NaT,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaT,NaN,225270.0,2286.43
43,1 Dollar = 49 Dalasis,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
47,NaN,OTHER EXPENSES,NaN,NaN,NaN,NaT,NaN,NaN,NaN
48,WHO,AMOUNT(D),AMOUNT($),DATE,NaN,NaT,NaN,NaN,NaN
49,Papa jara,2000,40.816327,2020-03-23 00:00:00,NaN,NaT,NaN,NaN,NaN
50,Bubacarr Fai,1500,30.612245,2020-04-29 00:00:00,NaN,NaT,NaN,NaN,NaN
51,Papa jara,2000,40.816327,2020-05-23 00:00:00,NaN,NaT,NaN,NaN,NaN
52,Bubacarr Fai,2000,40.816327,2020-05-23 00:00:00,NaN,NaT,NaN,NaN,NaN
53,Papa Jara,2500,51.020408,2022-04-23 00:00:00,NaN,NaT,NaN,NaN,NaN
54,Bubacarr Fai,2500,51.020408,2022-04-23 00:00:00,NaN,NaT,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
56,Total,12500,255.102041,NaN,NaN,NaT,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
58,1 Dollar = 49 Dalasis,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [8]:
# drop from the dataset from index number 40 to the end of the dataset
df_fencing = df_fencing.drop(df_fencing.iloc[40:].index)

In [9]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30,NaN,NaN,NaN
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30,NaN,NaN,NaN
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30,NaN,NaN,NaN
3,Cement,40,285,11400,232.653061,2020-05-06,NaN,NaN,NaN
4,Cement Transport,1,600,600,12.244898,2020-05-06,NaN,NaN,NaN
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06,NaN,NaN,NaN
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06,NaN,NaN,NaN
7,Water for Molding,1,1000,1000,20.408163,2020-05-06,NaN,NaN,NaN
8,Gas for Transport,1,450,450,9.183673,2020-05-06,NaN,NaN,NaN
9,Police Ticket,1,200,200,4.081633,2020-04-29,NaN,NaN,NaN
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08,NaN,NaN,NaN
11,Cement,25,285,7125,145.408163,2020-05-08,NaN,NaN,NaN
12,Cement Transport,25,15,375,7.653061,2020-05-08,NaN,NaN,NaN
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08,NaN,NaN,NaN
14,Gas for Transport,1,200,200,4.081633,2020-05-08,NaN,NaN,NaN
15,Iron Rods,—,4550,4550,92.857143,2020-05-10,NaN,NaN,NaN
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10,NaN,NaN,NaN
17,Gas for Transport,1,125,125,2.551020,2020-05-10,NaN,NaN,NaN
18,Gas for Transport,1,400,400,8.163265,2020-05-16,NaN,NaN,NaN
19,Electric Pipes,4,35,140,2.857143,2020-05-16,NaN,NaN,NaN
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16,NaN,NaN,NaN
21,Kilo of Nales,2,60,120,2.448980,2020-05-16,NaN,NaN,NaN
22,Taxi Fare,1,250,250,5.102041,2020-05-16,NaN,NaN,NaN
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16,NaN,NaN,NaN
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16,NaN,NaN,NaN
25,Cement,—,285,1150,23.469388,2020-05-22,NaN,NaN,NaN
26,Gas for Transport,1,200,200,4.081633,2020-05-22,NaN,NaN,NaN
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22,NaN,NaN,NaN
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22,NaN,NaN,NaN
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22,NaN,NaN,NaN
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22,NaN,NaN,NaN
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22,NaN,NaN,NaN
32,Lock for Gate,1,250,250,5.102041,2020-05-22,NaN,NaN,NaN
33,Gate,1,26000,26000,530.612245,2020-05-22,NaN,NaN,NaN
34,Cement,5,285,1425,29.081633,2020-05-22,NaN,NaN,NaN
35,Cement Transport,5,15,75,1.530612,2020-05-22,NaN,NaN,NaN
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24,NaN,NaN,NaN
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24,NaN,NaN,NaN
38,Finishing,1,1000,1000,20.408163,2020-06-23,NaN,NaN,NaN
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [10]:
# drop column 6 all the way to the last column
df_fencing = df_fencing.drop(df_fencing.iloc[:, 6:], axis=1)

In [11]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,—,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,—,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT

In [12]:
# access row 25, column 1 and assign integer 4 to it
df_fencing.iloc[25:26, 1:2] = 4

In [13]:
df_fencing.iloc[15:16, 1:2] = 1

In [14]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT

In [15]:
# drop all rows with missing value
df_fencing.dropna(inplace=True)

In [16]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23

In [17]:
# change the dataset column names into lowercase string
df_fencing.columns = df_fencing.columns.str.lower()

In [18]:
# display the collumn names
df_fencing.columns

Index(['item', 'quantity ', 'unit price(d)', 'total cost(d)', 'total($)',
       'date'],
      dtype='str')

In [19]:
# rename some column names
df_fencing.rename(columns={'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost', 'total($)': 'total_dollar'}, inplace=True)

In [20]:
df_fencing

,item,quantity,unit_cost,total_cost,total_dollar,date
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23

In [21]:
# change date collumn format
df_fencing['date'] = df_fencing['date'].dt.strftime('%m/%d/%Y')

In [22]:
df_fencing

,item,quantity,unit_cost,total_cost,total_dollar,date
0,Cutting Trees,1,10000,10000,204.081633,04/30/2020
1,Big Trip of Sand,1,7500,7500,153.061224,04/30/2020
2,Small Trip of Sand,1,4000,4000,81.632653,04/30/2020
3,Cement,40,285,11400,232.653061,05/06/2020
4,Cement Transport,1,600,600,12.244898,05/06/2020
5,Wheelbarrow Rental,1,200,200,4.081633,05/06/2020
6,Molding Bricks,1370,5,6850,139.795918,05/06/2020
7,Water for Molding,1,1000,1000,20.408163,05/06/2020
8,Gas for Transport,1,450,450,9.183673,05/06/2020
9,Police Ticket,1,200,200,4.081633,04/29/2020
10,Trip of Pebbles,1,3500,3500,71.428571,05/08/2020
11,Cement,25,285,7125,145.408163,05/08/2020
12,Cement Transport,25,15,375,7.653061,05/08/2020
13,Papa Jara Transport,1,600,600,12.244898,05/08/2020
14,Gas for Transport,1,200,200,4.081633,05/08/2020
15,Iron Rods,1,4550,4550,92.857143,05/10/2020
16,Iron Rods Transport,1,200,200,4.081633,05/10/2020
17,Gas for Transport,1,125,125,2.551020,05/10/2020
18,Gas for Transport,1,400,400,8.163265,05/16/2020
19,Electric Pipes,4,35,140,2.857143,05/16/2020
20,Wire for Pillar Board,1,100,100,2.040816,05/16/2020
21,Kilo of Nales,2,60,120,2.448980,05/16/2020
22,Taxi Fare,1,250,250,5.102041,05/16/2020
23,Pillar Boardrent 2Ds,14,50,700,14.285714,05/16/2020
24,Pillar Iron Rods,4,600,2400,48.979592,05/16/2020
25,Cement,4,285,1150,23.469388,05/22/2020
26,Gas for Transport,1,200,200,4.081633,05/22/2020
27,Pillar Mold Rental,4,500,2000,40.816327,05/22/2020
28,Pillar Board Rental,6,25,150,3.061224,02/22/2020
29,Pillar & Board Trasp,1,1000,1000,20.408163,05/22/2020
30,Pillar Pebbel,1,3000,3000,61.224490,05/22/2020
31,Pillar Pebbel Trasport,1,400,400,8.163265,05/22/2020
32,Lock for Gate,1,250,250,5.102041,05/22/2020
33,Gate,1,26000,26000,530.612245,05/22/2020
34,Cement,5,285,1425,29.081633,05/22/2020
35,Cement Transport,5,15,75,1.530612,05/22/2020
36,Fence Building Fee,1,12000,12000,244.897959,05/24/2020
37,Water for Fencing,1,1000,1000,20.408163,05/24/2020
38,Finishing,1,1000,1000,20.408163,06/23/2020

In [23]:
# drop the total_dollar column as it is not needed
df_fencing = df_fencing.drop('total_dollar', axis=1)

In [24]:
df_fencing

                      item quantity  unit_cost total_cost        date
0            Cutting Trees         1     10000      10000  04/30/2020
1         Big Trip of Sand         1      7500       7500  04/30/2020
2       Small Trip of Sand         1      4000       4000  04/30/2020
3                  Cement         40       285      11400  05/06/2020
4        Cement Transport          1       600        600  05/06/2020
5       Wheelbarrow Rental         1       200        200  05/06/2020
6           Molding Bricks      1370         5       6850  05/06/2020
7       Water for Molding          1      1000       1000  05/06/2020
8       Gas for Transport          1       450        450  05/06/2020
9           Police Ticket          1       200        200  04/29/2020
10        Trip of Pebbles          1      3500       3500  05/08/2020
11                 Cement         25       285       7125  05/08/2020
12       Cement Transport         25        15        375  05/08/2020
13     Papa Jara Transport         1       600        600  05/08/2020
14      Gas for Transport          1       200        200  05/08/2020
15               Iron Rods         1      4550       4550  05/10/2020
16    Iron Rods Transport          1       200        200  05/10/2020
17      Gas for Transport          1       125        125  05/10/2020
18      Gas for Transport          1       400        400  05/16/2020
19         Electric Pipes          4        35        140  05/16/2020
20   Wire for Pillar Board         1       100        100  05/16/2020
21           Kilo of Nales         2        60        120  05/16/2020
22              Taxi Fare          1       250        250  05/16/2020
23    Pillar Boardrent 2Ds        14        50        700  05/16/2020
24        Pillar Iron Rods         4       600       2400  05/16/2020
25                 Cement          4       285       1150  05/22/2020
26      Gas for Transport          1       200        200  05/22/2020
27     Pillar Mold Rental          4       500       2000  05/22/2020
28    Pillar Board Rental          6        25        150  02/22/2020
29    Pillar & Board Trasp         1      1000       1000  05/22/2020
30           Pillar Pebbel         1      3000       3000  05/22/2020
31  Pillar Pebbel Trasport         1       400        400  05/22/2020
32           Lock for Gate         1       250        250  05/22/2020
33                    Gate         1     26000      26000  05/22/2020
34                 Cement          5       285       1425  05/22/2020
35       Cement Transport          5        15         75  05/22/2020
36      Fence Building Fee         1     12000      12000  05/24/2020
37      Water for Fencing          1      1000       1000  05/24/2020
38              Finishing          1      1000       1000  06/23/2020

In [ ]:
# save the datgaset as a csv file
df_fencing.to_csv('ParadiseView/out/df_fencing_clean.csv', index=False)

In [2]:
import pandas as pd
import numpy as np

In [13]:
# Read csv file from ParadiseView folder
df = pd.read_csv('ParadiseView/out/df_fencing_clean.csv')

In [14]:
# Get a quick information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        39 non-null     str
 1   quantity    39 non-null     int64
 2   unit_cost   39 non-null     int64
 3   total_cost  39 non-null     int64
 4   date        39 non-null     str
dtypes: int64(3), str(2)
memory usage: 1.7 KB

In [16]:
# Create three new columns and assign vaolues to them
df['sub_category'] = 'Fencing'
df['category'] = 'Preconstruction'
df['exchange_rate'] = 49.00

In [23]:
df.rename(columns={'quantity ': 'quantity'}, inplace=True)

In [24]:
# Reindex the columns to a desire arrangement
df = df.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category', 'exchange_rate'])

In [25]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cutting Trees,1,10000,10000,04/30/2020,Fencing,Preconstruction,49.0
1,Big Trip of Sand,1,7500,7500,04/30/2020,Fencing,Preconstruction,49.0
2,Small Trip of Sand,1,4000,4000,04/30/2020,Fencing,Preconstruction,49.0
3,Cement,40,285,11400,05/06/2020,Fencing,Preconstruction,49.0
4,Cement Transport,1,600,600,05/06/2020,Fencing,Preconstruction,49.0
5,Wheelbarrow Rental,1,200,200,05/06/2020,Fencing,Preconstruction,49.0
6,Molding Bricks,1370,5,6850,05/06/2020,Fencing,Preconstruction,49.0
7,Water for Molding,1,1000,1000,05/06/2020,Fencing,Preconstruction,49.0
8,Gas for Transport,1,450,450,05/06/2020,Fencing,Preconstruction,49.0
9,Police Ticket,1,200,200,04/29/2020,Fencing,Preconstruction,49.0
10,Trip of Pebbles,1,3500,3500,05/08/2020,Fencing,Preconstruction,49.0
11,Cement,25,285,7125,05/08/2020,Fencing,Preconstruction,49.0
12,Cement Transport,25,15,375,05/08/2020,Fencing,Preconstruction,49.0
13,Papa Jara Transport,1,600,600,05/08/2020,Fencing,Preconstruction,49.0
14,Gas for Transport,1,200,200,05/08/2020,Fencing,Preconstruction,49.0
15,Iron Rods,1,4550,4550,05/10/2020,Fencing,Preconstruction,49.0
16,Iron Rods Transport,1,200,200,05/10/2020,Fencing,Preconstruction,49.0
17,Gas for Transport,1,125,125,05/10/2020,Fencing,Preconstruction,49.0
18,Gas for Transport,1,400,400,05/16/2020,Fencing,Preconstruction,49.0
19,Electric Pipes,4,35,140,05/16/2020,Fencing,Preconstruction,49.0
20,Wire for Pillar Board,1,100,100,05/16/2020,Fencing,Preconstruction,49.0
21,Kilo of Nales,2,60,120,05/16/2020,Fencing,Preconstruction,49.0
22,Taxi Fare,1,250,250,05/16/2020,Fencing,Preconstruction,49.0
23,Pillar Boardrent 2Ds,14,50,700,05/16/2020,Fencing,Preconstruction,49.0
24,Pillar Iron Rods,4,600,2400,05/16/2020,Fencing,Preconstruction,49.0
25,Cement,4,285,1150,05/22/2020,Fencing,Preconstruction,49.0
26,Gas for Transport,1,200,200,05/22/2020,Fencing,Preconstruction,49.0
27,Pillar Mold Rental,4,500,2000,05/22/2020,Fencing,Preconstruction,49.0
28,Pillar Board Rental,6,25,150,02/22/2020,Fencing,Preconstruction,49.0
29,Pillar & Board Trasp,1,1000,1000,05/22/2020,Fencing,Preconstruction,49.0
30,Pillar Pebbel,1,3000,3000,05/22/2020,Fencing,Preconstruction,49.0
31,Pillar Pebbel Trasport,1,400,400,05/22/2020,Fencing,Preconstruction,49.0
32,Lock for Gate,1,250,250,05/22/2020,Fencing,Preconstruction,49.0
33,Gate,1,26000,26000,05/22/2020,Fencing,Preconstruction,49.0
34,Cement,5,285,1425,05/22/2020,Fencing,Preconstruction,49.0
35,Cement Transport,5,15,75,05/22/2020,Fencing,Preconstruction,49.0
36,Fence Building Fee,1,12000,12000,05/24/2020,Fencing,Preconstruction,49.0
37,Water for Fencing,1,1000,1000,05/24/2020,Fencing,Preconstruction,49.0
38,Finishing,1,1000,1000,06/23/2020,Fencing,Preconstruction,49.0

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           39 non-null     str
 1   quantity       39 non-null     int64
 2   unit_cost      39 non-null     int64
 3   total_cost     39 non-null     int64
 4   date           39 non-null     str
 5   sub_category   39 non-null     str
 6   category       39 non-null     str
 7   exchange_rate  39 non-null     float64
dtypes: float64(1), int64(3), str(4)
memory usage: 2.6 KB

In [29]:
# Change the datatype of the date column to a datetime object
df['date'] = pd.to_datetime(df['date'])

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           39 non-null     str
 1   quantity       39 non-null     int64
 2   unit_cost      39 non-null     int64
 3   total_cost     39 non-null     int64
 4   date           39 non-null     datetime64[us]
 5   sub_category   39 non-null     str
 6   category       39 non-null     str
 7   exchange_rate  39 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 2.6 KB

In [31]:
# Save the dataset as a csv file in the ParadiseView/out folder
df.to_csv('ParadiseView/out/df_fencing.csv', index=False)