In [2]:
# import pandas and numpy libraries
import pandas as pd
import numpy as np

In [3]:
# declare two variables
filepath = "ParadiseView/Paradise View Expenditures 4.xlsx"
outFilePath = 'ParadiseView/out',

In [4]:
# read an excel file into f_floorMolding
f_floorMolding = pd.read_excel(filepath, sheet_name='Brick Molding', skiprows=4)

In [5]:
# display the dataset
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00,NaN,NaN,NaN,NaN
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00,NaN,NaN,NaN,NaN
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total,NaN,7750,7750,155,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,BRICK MOLDING EXPENSES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,NaN,NaN,NaN,NaN
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00,NaN,NaN,NaN,NaN
13,Cement,75,320,24000,480,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00,NaN,NaN,NaN,"D1,500 missing from the D50,000"
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
21,Gasoline,1,300,300,6,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
22,Missing,—-,—,1500,30,NaN,NaN,NaN,NaN,"D1,000 given to Kasaru"
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00,NaN,NaN,NaN,NaN
24,Cement,120,325,39000,780,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
27,Small Tank,1,800,800,16,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
29,Gasoline,1,500,500,10,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00,NaN,NaN,NaN,NaN
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00,NaN,NaN,NaN,NaN
32,Bricks Payment,4210,6,25260,505.2,NaN,NaN,NaN,NaN,NaN
33,Over Payment,1,1800,1800,36,NaN,NaN,NaN,NaN,NaN
34,Big Sand Trip,1,8000,8000,160,NaN,NaN,NaN,NaN,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN,NaN,NaN,NaN,NaN
36,Cement,55,330,18150,363,NaN,NaN,NaN,NaN,NaN
37,Cement Transport,55,15,825,16.5,NaN,NaN,NaN,NaN,NaN
38,Bricks payment,2675,6,16050,321,NaN,NaN,NaN,NaN,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Total,NaN,NaN,195000,3900,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# drop four columns from the dataset
f_floorMolding.drop(columns=['Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'], inplace=True)

In [7]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Total,NaN,7750,7750,155,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,BRICK MOLDING EXPENSES,NaN,NaN,NaN
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----
40,NaN,NaN,NaN,NaN,NaN,NaN
41,Total,NaN,NaN,195000,3900,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN
43,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN

In [33]:
# keep rows with atleast six non-missing columns and drop the rest
f_floorMolding.dropna(thresh=len(f_floorMolding.columns) - 1, inplace=True)

In [9]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----

In [10]:
# drop a row from the dataset where ITEM column is equal to ITEM
f_floorMolding.drop(f_floorMolding[f_floorMolding['ITEM'] == 'ITEM'].index, inplace =True)

In [11]:
# make the dataset's columns lowercase strings
f_floorMolding.columns = f_floorMolding.columns.str.lower()

In [12]:
# display first five rows of the dataset
f_floorMolding.head()

,item,quantity,unit price(d),total cost(d),cost($),date
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00

In [13]:
# rename some of the columns
f_floorMolding.rename(columns={'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [14]:
# drop cost($) column from the dataset
f_floorMolding.drop(columns='cost($)', inplace=True)

In [15]:
f_floorMolding

                      item quantity  unit_cost total_cost                 date
0        $100 Transfer Fee         1       250        250  2022-03-27 00:00:00
1            Cutting Trees         1      5000       5000  2022-04-03 00:00:00
2            Clearing Plot         1      2500       2500  2022-04-03 00:00:00
12     $1,000 Transfer Fee         1      1000       1000  2022-04-16 00:00:00
13                 Cement         75       320      24000  2022-04-18 00:00:00
14        Cement Transport        75        20       1500  2022-04-18 00:00:00
15            Wheelbarrow          1      3000       3000  2022-04-18 00:00:00
16          50m Hose/Pipe          1      1400       1400  2022-04-18 00:00:00
17           Small Bucket          2       100        200  2022-04-18 00:00:00
18           Big Sand Trip         2      8000      16000  2022-04-18 00:00:00
19             Small Tank          1      1600       1600  2022-04-18 00:00:00
20         Cement Watchman         1       500        500  2022-04-18 00:00:00
21               Gasoline          1       300        300  2022-04-18 00:00:00
22                Missing         —-         —       1500                  NaN
23     $1,000 Transfer Fee         1      1000       1000  2022-04-19 00:00:00
24                 Cement        120       325      39000  2022-04-20 00:00:00
25        Cement Transport       120        15       1800  2022-04-20 00:00:00
26           Big Sand Trip         1      8000       8000  2022-04-20 00:00:00
27             Small Tank          1       800        800  2022-04-20 00:00:00
28       Wheelbarrow Tire          1       700        700  2022-04-20 00:00:00
29               Gasoline          1       500        500  2022-04-20 00:00:00
30     $1,000 Transfer Fee         1       600        600  2022-04-22 00:00:00
31          Big Sand Trip          2      8000      16000  2022-04-23 00:00:00
32         Bricks Payment       4210         6      25260                  NaN
33           Over Payment          1      1800       1800                  NaN
34           Big Sand Trip         1      8000       8000                  NaN
35        6Wheel Sand Trip         1      5500       5500                  NaN
36                 Cement         55       330      18150                  NaN
37       Cement Transport         55        15        825                  NaN
38         Bricks payment       2675         6      16050                  NaN
39  Needs To Be Determined      .---      .---         15                .----

In [16]:
# aacess indeces and assign a value string to them
f_floorMolding.at[22, 'date'] = '2022-04-18 00:00:00'

In [17]:
f_floorMolding.loc[32:, 'date'] = '2022-04-23 00:00:00'

In [18]:
f_floorMolding.loc[f_floorMolding['item'] == 'Missing', 'date'] = 1

In [19]:
f_floorMolding.at[32, 'unit_cost'] = 6.00

In [20]:
f_floorMolding.at[22, 'unit_cost'] = 1500

In [21]:
f_floorMolding.at[39, 'quantity '] = 1
f_floorMolding.at[39, 'unit_cost'] = 15

In [22]:
# get the column names
f_floorMolding.columns

Index(['item', 'quantity ', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [23]:
# change the date column to datetime object
f_floorMolding['date'] = pd.to_datetime(f_floorMolding['date'])

In [24]:
f_floorMolding['date'].info

<bound method Series.info of 0    2022-03-27
1    2022-04-03
2    2022-04-03
12   2022-04-16
13   2022-04-18
14   2022-04-18
15   2022-04-18
16   2022-04-18
17   2022-04-18
18   2022-04-18
19   2022-04-18
20   2022-04-18
21   2022-04-18
22   2022-04-18
23   2022-04-19
24   2022-04-20
25   2022-04-20
26   2022-04-20
27   2022-04-20
28   2022-04-20
29   2022-04-20
30   2022-04-22
31   2022-04-23
32   2022-04-23
33   2022-04-23
34   2022-04-23
35   2022-04-23
36   2022-04-23
37   2022-04-23
38   2022-04-23
39   2022-04-23
Name: date, dtype: datetime64[us]>

In [25]:
# change the format of the date column
f_floorMolding['date'] = f_floorMolding['date'].dt.strftime('%m/%d/%Y')

In [26]:
f_floorMolding

                      item quantity  unit_cost total_cost        date
0        $100 Transfer Fee         1       250        250  03/27/2022
1            Cutting Trees         1      5000       5000  04/03/2022
2            Clearing Plot         1      2500       2500  04/03/2022
12     $1,000 Transfer Fee         1      1000       1000  04/16/2022
13                 Cement         75       320      24000  04/18/2022
14        Cement Transport        75        20       1500  04/18/2022
15            Wheelbarrow          1      3000       3000  04/18/2022
16          50m Hose/Pipe          1      1400       1400  04/18/2022
17           Small Bucket          2       100        200  04/18/2022
18           Big Sand Trip         2      8000      16000  04/18/2022
19             Small Tank          1      1600       1600  04/18/2022
20         Cement Watchman         1       500        500  04/18/2022
21               Gasoline          1       300        300  04/18/2022
22                Missing         —-      1500       1500  04/18/2022
23     $1,000 Transfer Fee         1      1000       1000  04/19/2022
24                 Cement        120       325      39000  04/20/2022
25        Cement Transport       120        15       1800  04/20/2022
26           Big Sand Trip         1      8000       8000  04/20/2022
27             Small Tank          1       800        800  04/20/2022
28       Wheelbarrow Tire          1       700        700  04/20/2022
29               Gasoline          1       500        500  04/20/2022
30     $1,000 Transfer Fee         1       600        600  04/22/2022
31          Big Sand Trip          2      8000      16000  04/23/2022
32         Bricks Payment       4210       6.0      25260  04/23/2022
33           Over Payment          1      1800       1800  04/23/2022
34           Big Sand Trip         1      8000       8000  04/23/2022
35        6Wheel Sand Trip         1      5500       5500  04/23/2022
36                 Cement         55       330      18150  04/23/2022
37       Cement Transport         55        15        825  04/23/2022
38         Bricks payment       2675         6      16050  04/23/2022
39  Needs To Be Determined         1        15         15  04/23/2022

In [27]:
# create two new columns
f_floorMolding['sub_category'] = 'Brick Molding'
f_floorMolding['category'] = '1st Floor'

In [29]:
f_floorMolding

,item,quantity,unit_cost,total_cost,date,sub_category,category
0,$100 Transfer Fee,1,250,250,03/27/2022,Brick Molding,1st Floor
1,Cutting Trees,1,5000,5000,04/03/2022,Brick Molding,1st Floor
2,Clearing Plot,1,2500,2500,04/03/2022,Brick Molding,1st Floor
12,"$1,000 Transfer Fee",1,1000,1000,04/16/2022,Brick Molding,1st Floor
13,Cement,75,320,24000,04/18/2022,Brick Molding,1st Floor
14,Cement Transport,75,20,1500,04/18/2022,Brick Molding,1st Floor
15,Wheelbarrow,1,3000,3000,04/18/2022,Brick Molding,1st Floor
16,50m Hose/Pipe,1,1400,1400,04/18/2022,Brick Molding,1st Floor
17,Small Bucket,2,100,200,04/18/2022,Brick Molding,1st Floor
18,Big Sand Trip,2,8000,16000,04/18/2022,Brick Molding,1st Floor
19,Small Tank,1,1600,1600,04/18/2022,Brick Molding,1st Floor
20,Cement Watchman,1,500,500,04/18/2022,Brick Molding,1st Floor
21,Gasoline,1,300,300,04/18/2022,Brick Molding,1st Floor
22,Missing,—-,1500,1500,04/18/2022,Brick Molding,1st Floor
23,"$1,000 Transfer Fee",1,1000,1000,04/19/2022,Brick Molding,1st Floor
24,Cement,120,325,39000,04/20/2022,Brick Molding,1st Floor
25,Cement Transport,120,15,1800,04/20/2022,Brick Molding,1st Floor
26,Big Sand Trip,1,8000,8000,04/20/2022,Brick Molding,1st Floor
27,Small Tank,1,800,800,04/20/2022,Brick Molding,1st Floor
28,Wheelbarrow Tire,1,700,700,04/20/2022,Brick Molding,1st Floor
29,Gasoline,1,500,500,04/20/2022,Brick Molding,1st Floor
30,"$1,000 Transfer Fee",1,600,600,04/22/2022,Brick Molding,1st Floor
31,Big Sand Trip,2,8000,16000,04/23/2022,Brick Molding,1st Floor
32,Bricks Payment,4210,6.0,25260,04/23/2022,Brick Molding,1st Floor
33,Over Payment,1,1800,1800,04/23/2022,Brick Molding,1st Floor
34,Big Sand Trip,1,8000,8000,04/23/2022,Brick Molding,1st Floor
35,6Wheel Sand Trip,1,5500,5500,04/23/2022,Brick Molding,1st Floor
36,Cement,55,330,18150,04/23/2022,Brick Molding,1st Floor
37,Cement Transport,55,15,825,04/23/2022,Brick Molding,1st Floor
38,Bricks payment,2675,6,16050,04/23/2022,Brick Molding,1st Floor
39,Needs To Be Determined,1,15,15,04/23/2022,Brick Molding,1st Floor

In [ ]:
# save the dataset as a csv file
f_floorMolding.to_csv('ParadiseView/out/df_ffBrickMoldingClean.csv', index=False)

In [32]:
import pandas as pd
import numpy as np

In [33]:
# Read csv file into df
df = pd.read_csv('ParadiseView/out/df_ffBrickMoldingClean.csv')

In [35]:
# Create a new column and assign 50.00 as its value
df['exchange_rate'] = 50.00

In [37]:
# get quick information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           31 non-null     str
 1   quantity       31 non-null     int64
 2   unit_cost      31 non-null     float64
 3   total_cost     31 non-null     int64
 4   date           31 non-null     str
 5   sub_category   31 non-null     str
 6   category       31 non-null     str
 7   exchange_rate  31 non-null     float64
dtypes: float64(2), int64(2), str(4)
memory usage: 2.1 KB

In [39]:
# Change totasl_cost column datatype from int64 to float64 
df['total_cost'] = df['total_cost'].astype('float64')

In [40]:
df['quantity'] = df['quantity'].astype('float64')

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           31 non-null     str
 1   quantity       31 non-null     float64
 2   unit_cost      31 non-null     float64
 3   total_cost     31 non-null     float64
 4   date           31 non-null     str
 5   sub_category   31 non-null     str
 6   category       31 non-null     str
 7   exchange_rate  31 non-null     float64
dtypes: float64(4), str(4)
memory usage: 2.1 KB

In [42]:
# Convert date column from string to datetime object
df['date'] = pd.to_datetime(df['date'])

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           31 non-null     str
 1   quantity       31 non-null     float64
 2   unit_cost      31 non-null     float64
 3   total_cost     31 non-null     float64
 4   date           31 non-null     datetime64[us]
 5   sub_category   31 non-null     str
 6   category       31 non-null     str
 7   exchange_rate  31 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 2.1 KB

In [44]:
# get the columns names
df.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category',
       'category', 'exchange_rate'],
      dtype='str')

In [45]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,$100 Transfer Fee,1.0,250.0,250.0,2022-03-27,Brick Molding,1st Floor,50.0
1,Cutting Trees,1.0,5000.0,5000.0,2022-04-03,Brick Molding,1st Floor,50.0
2,Clearing Plot,1.0,2500.0,2500.0,2022-04-03,Brick Molding,1st Floor,50.0
3,"$1,000 Transfer Fee",1.0,1000.0,1000.0,2022-04-16,Brick Molding,1st Floor,50.0
4,Cement,75.0,320.0,24000.0,2022-04-18,Brick Molding,1st Floor,50.0
5,Cement Transport,75.0,20.0,1500.0,2022-04-18,Brick Molding,1st Floor,50.0
6,Wheelbarrow,1.0,3000.0,3000.0,2022-04-18,Brick Molding,1st Floor,50.0
7,50m Hose/Pipe,1.0,1400.0,1400.0,2022-04-18,Brick Molding,1st Floor,50.0
8,Small Bucket,2.0,100.0,200.0,2022-04-18,Brick Molding,1st Floor,50.0
9,Big Sand Trip,2.0,8000.0,16000.0,2022-04-18,Brick Molding,1st Floor,50.0
10,Small Tank,1.0,1600.0,1600.0,2022-04-18,Brick Molding,1st Floor,50.0
11,Cement Watchman,1.0,500.0,500.0,2022-04-18,Brick Molding,1st Floor,50.0
12,Gasoline,1.0,300.0,300.0,2022-04-18,Brick Molding,1st Floor,50.0
13,Missing,1.0,1500.0,1500.0,2022-04-18,Brick Molding,1st Floor,50.0
14,"$1,000 Transfer Fee",1.0,1000.0,1000.0,2022-04-19,Brick Molding,1st Floor,50.0
15,Cement,120.0,325.0,39000.0,2022-04-20,Brick Molding,1st Floor,50.0
16,Cement Transport,120.0,15.0,1800.0,2022-04-20,Brick Molding,1st Floor,50.0
17,Big Sand Trip,1.0,8000.0,8000.0,2022-04-20,Brick Molding,1st Floor,50.0
18,Small Tank,1.0,800.0,800.0,2022-04-20,Brick Molding,1st Floor,50.0
19,Wheelbarrow Tire,1.0,700.0,700.0,2022-04-20,Brick Molding,1st Floor,50.0
20,Gasoline,1.0,500.0,500.0,2022-04-20,Brick Molding,1st Floor,50.0
21,"$1,000 Transfer Fee",1.0,600.0,600.0,2022-04-22,Brick Molding,1st Floor,50.0
22,Big Sand Trip,2.0,8000.0,16000.0,2022-04-23,Brick Molding,1st Floor,50.0
23,Bricks Payment,4210.0,6.0,25260.0,2022-04-23,Brick Molding,1st Floor,50.0
24,Over Payment,1.0,1800.0,1800.0,2022-04-23,Brick Molding,1st Floor,50.0
25,Big Sand Trip,1.0,8000.0,8000.0,2022-04-23,Brick Molding,1st Floor,50.0
26,6Wheel Sand Trip,1.0,5500.0,5500.0,2022-04-23,Brick Molding,1st Floor,50.0
27,Cement,55.0,330.0,18150.0,2022-04-23,Brick Molding,1st Floor,50.0
28,Cement Transport,55.0,15.0,825.0,2022-04-23,Brick Molding,1st Floor,50.0
29,Bricks payment,2675.0,6.0,16050.0,2022-04-23,Brick Molding,1st Floor,50.0
30,Needs To Be Determined,1.0,15.0,15.0,2022-04-23,Brick Molding,1st Floor,50.0

In [47]:
# save the dataset as a csv file
df.to_csv('ParadiseView/out/df_ffBrickMolding.csv', index=False)