In [2]:
import pandas as pd
import numpy as np

In [4]:
# read an excel file 
otherExp = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx", skiprows=55, sheet_name="Fencing")

In [5]:
otherExp

,WHO,AMOUNT(D),AMOUNT($),DATE,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Papa jara,2000.0,40.816327,2020-03-23,NaN,NaN,NaN,NaN,NaN
1,Bubacarr Fai,1500.0,30.612245,2020-04-29,NaN,NaN,NaN,NaN,NaN
2,Papa jara,2000.0,40.816327,2020-05-23,NaN,NaN,NaN,NaN,NaN
3,Bubacarr Fai,2000.0,40.816327,2020-05-23,NaN,NaN,NaN,NaN,NaN
4,Papa Jara,2500.0,51.020408,2022-04-23,NaN,NaN,NaN,NaN,NaN
5,Bubacarr Fai,2500.0,51.020408,2022-04-23,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
7,Total,12500.0,255.102041,NaT,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
9,1 Dollar = 49 Dalasis,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [6]:
# drop unwanted columns from the dataset
otherExp.drop(['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',], axis=1, inplace=True)

In [7]:
# display the dataset
otherExp

                     WHO  AMOUNT(D)   AMOUNT($)       DATE
0              Papa jara     2000.0   40.816327 2020-03-23
1           Bubacarr Fai     1500.0   30.612245 2020-04-29
2              Papa jara     2000.0   40.816327 2020-05-23
3           Bubacarr Fai     2000.0   40.816327 2020-05-23
4             Papa Jara      2500.0   51.020408 2022-04-23
5           Bubacarr Fai     2500.0   51.020408 2022-04-23
6                    NaN        NaN         NaN        NaT
7                  Total    12500.0  255.102041        NaT
8                    NaN        NaN         NaN        NaT
9  1 Dollar = 49 Dalasis        NaN         NaN        NaT

In [8]:
# drop all missing values from tghe dataset
otherExp.dropna(inplace=True)

In [9]:
otherExp

            WHO  AMOUNT(D)  AMOUNT($)       DATE
0     Papa jara     2000.0  40.816327 2020-03-23
1  Bubacarr Fai     1500.0  30.612245 2020-04-29
2     Papa jara     2000.0  40.816327 2020-05-23
3  Bubacarr Fai     2000.0  40.816327 2020-05-23
4    Papa Jara      2500.0  51.020408 2022-04-23
5  Bubacarr Fai     2500.0  51.020408 2022-04-23

In [10]:
# rename columns
otherExp.rename(columns={'WHO': 'item', 'AMOUNT(D)': 'unit_cost'}, inplace=True)

In [11]:
otherExp

           item  unit_cost  AMOUNT($)       DATE
0     Papa jara     2000.0  40.816327 2020-03-23
1  Bubacarr Fai     1500.0  30.612245 2020-04-29
2     Papa jara     2000.0  40.816327 2020-05-23
3  Bubacarr Fai     2000.0  40.816327 2020-05-23
4    Papa Jara      2500.0  51.020408 2022-04-23
5  Bubacarr Fai     2500.0  51.020408 2022-04-23

In [12]:
otherExp.columns

Index(['item', 'unit_cost', 'AMOUNT($)', 'DATE'], dtype='str')

In [13]:
# drop AMOUNT($) column from the dataset
otherExp.drop('AMOUNT($)', axis=1, inplace=True)

In [14]:
otherExp

           item  unit_cost       DATE
0     Papa jara     2000.0 2020-03-23
1  Bubacarr Fai     1500.0 2020-04-29
2     Papa jara     2000.0 2020-05-23
3  Bubacarr Fai     2000.0 2020-05-23
4    Papa Jara      2500.0 2022-04-23
5  Bubacarr Fai     2500.0 2022-04-23

In [15]:
# change column names to lowercase string
otherExp.columns = otherExp.columns.str.lower()

In [16]:
# format the date column
otherExp['date'] = otherExp['date'].dt.strftime('%m/%d/%Y')

In [17]:
otherExp

           item  unit_cost        date
0     Papa jara     2000.0  03/23/2020
1  Bubacarr Fai     1500.0  04/29/2020
2     Papa jara     2000.0  05/23/2020
3  Bubacarr Fai     2000.0  05/23/2020
4    Papa Jara      2500.0  04/23/2022
5  Bubacarr Fai     2500.0  04/23/2022

In [18]:
# assign integer 1 to 'quantity' column
otherExp['quantity'] = 1

In [19]:
otherExp

           item  unit_cost        date  quantity
0     Papa jara     2000.0  03/23/2020         1
1  Bubacarr Fai     1500.0  04/29/2020         1
2     Papa jara     2000.0  05/23/2020         1
3  Bubacarr Fai     2000.0  05/23/2020         1
4    Papa Jara      2500.0  04/23/2022         1
5  Bubacarr Fai     2500.0  04/23/2022         1

In [20]:
# drive new column from results from multiplying two columns
otherExp['total_cost'] = otherExp['unit_cost'] * otherExp['quantity']

In [21]:
# reindex the columns
otherExp = otherExp.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date'])

In [22]:
otherExp

           item  quantity  unit_cost  total_cost        date
0     Papa jara         1     2000.0      2000.0  03/23/2020
1  Bubacarr Fai         1     1500.0      1500.0  04/29/2020
2     Papa jara         1     2000.0      2000.0  05/23/2020
3  Bubacarr Fai         1     2000.0      2000.0  05/23/2020
4    Papa Jara          1     2500.0      2500.0  04/23/2022
5  Bubacarr Fai         1     2500.0      2500.0  04/23/2022

In [ ]:
# sdave the dataset as csv file without the indeces
otherExp.to_csv('ParadiseView/out/df_otherExp_clean.csv', index=False)

In [23]:
import pandas as pd
import numpy as np

In [24]:
otherExp = pd.read_csv('ParadiseView/out/df_otherExp_clean.csv')

In [25]:
otherExp

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Papa Jara,1,2000.0,2000.0,2020-03-23,Fencing,Preconstruction,49.0
1,Bubacarr Faye,1,1500.0,1500.0,2020-04-29,Fencing,Preconstruction,49.0
2,Papa Jara,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
3,Bubacarr Faye,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
4,Papa Jara,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0
5,Bubacarr Faye,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0

In [26]:
# search for a string value and replace it with another string value
otherExp['item'] = np.where(otherExp['item'].str.contains('Papa jara', case=False, na=False), 'Papa Jara', otherExp['item'])

In [27]:
otherExp['item'] = np.where(otherExp['item'].str.contains('Bubacarr Fai', case=False, na=False), 'Bubacarr Faye', otherExp['item'])

In [28]:
otherExp

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Papa Jara,1,2000.0,2000.0,2020-03-23,Fencing,Preconstruction,49.0
1,Bubacarr Faye,1,1500.0,1500.0,2020-04-29,Fencing,Preconstruction,49.0
2,Papa Jara,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
3,Bubacarr Faye,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
4,Papa Jara,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0
5,Bubacarr Faye,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0

In [29]:
# create three new columns
otherExp['sub_category'] = 'Fencing'
otherExp['category'] = 'Preconstruction'
otherExp['exchange_rate'] = 49.00

In [30]:
otherExp['date'] = np.where(otherExp['date'] == pd.to_datetime('2022-04-23'), pd.to_datetime('2020-04-23'), otherExp['date'])

In [31]:
otherExp['date'] = pd.to_datetime(otherExp['date'])

In [32]:
otherExp

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Papa Jara,1,2000.0,2000.0,2020-03-23,Fencing,Preconstruction,49.0
1,Bubacarr Faye,1,1500.0,1500.0,2020-04-29,Fencing,Preconstruction,49.0
2,Papa Jara,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
3,Bubacarr Faye,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
4,Papa Jara,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0
5,Bubacarr Faye,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0

In [ ]:
otherExp.to_csv('ParadiseView/out/df_otherExp_clean.csv', index=False)