In [1]:
import pandas as pd
import numpy as np

In [20]:
df= pd.read_csv('ParadiseView/out/df_borehole_drilling.csv')

In [21]:
df

,item,quantity,unti_cost,total_cost,date,sub_category,category
0,Bore Drilling,1.0,95000.0,95000.0,06/24/2023,Borehole Drilling,Preconstruction
1,Carpenter,1.0,6500.0,6500.0,06/25/2023,Borehole Drilling,Preconstruction
2,Kaye Rod,34.0,180.0,6120.0,06/25/2023,Borehole Drilling,Preconstruction
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,06/25/2023,Borehole Drilling,Preconstruction
4,Big Nale(kg),3.0,100.0,300.0,06/25/2023,Borehole Drilling,Preconstruction
5,Small Nale(Packs),3.0,350.0,1050.0,06/25/2023,Borehole Drilling,Preconstruction
6,Wood for Doors,5.0,300.0,1500.0,06/25/2023,Borehole Drilling,Preconstruction
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,06/25/2023,Borehole Drilling,Preconstruction
8,Delivering Guys,1.0,800.0,800.0,06/25/2023,Borehole Drilling,Preconstruction
9,Residual,1.0,2380.0,2380.0,06/25/2023,Borehole Drilling,Preconstruction

In [22]:
df.columns

Index(['item', 'quantity ', 'unti_cost', 'total_cost', 'date', 'sub_category',
       'category'],
      dtype='str')

In [23]:
df.rename(columns={'quantity ': 'quantity', 'unti_cost': 'unit_cost'}, inplace=True)

In [24]:
df.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category',
       'category'],
      dtype='str')

In [25]:
df = df.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [26]:
df['exchange_rate'] = 63.00

In [27]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Bore Drilling,1.0,95000.0,95000.0,06/24/2023,Borehole Drilling,Preconstruction,63.0
1,Carpenter,1.0,6500.0,6500.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
2,Kaye Rod,34.0,180.0,6120.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
4,Big Nale(kg),3.0,100.0,300.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
5,Small Nale(Packs),3.0,350.0,1050.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
6,Wood for Doors,5.0,300.0,1500.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
8,Delivering Guys,1.0,800.0,800.0,06/25/2023,Borehole Drilling,Preconstruction,63.0
9,Residual,1.0,2380.0,2380.0,06/25/2023,Borehole Drilling,Preconstruction,63.0

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           10 non-null     str
 1   quantity       10 non-null     float64
 2   unit_cost      10 non-null     float64
 3   total_cost     10 non-null     float64
 4   date           10 non-null     str
 5   sub_category   10 non-null     str
 6   category       10 non-null     str
 7   exchange_rate  10 non-null     float64
dtypes: float64(4), str(4)
memory usage: 772.0 bytes

In [29]:
df['date'] = pd.to_datetime(df['date'])

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           10 non-null     str
 1   quantity       10 non-null     float64
 2   unit_cost      10 non-null     float64
 3   total_cost     10 non-null     float64
 4   date           10 non-null     datetime64[us]
 5   sub_category   10 non-null     str
 6   category       10 non-null     str
 7   exchange_rate  10 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 772.0 bytes

In [31]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Bore Drilling,1.0,95000.0,95000.0,2023-06-24,Borehole Drilling,Preconstruction,63.0
1,Carpenter,1.0,6500.0,6500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
2,Kaye Rod,34.0,180.0,6120.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
4,Big Nale(kg),3.0,100.0,300.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
5,Small Nale(Packs),3.0,350.0,1050.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
6,Wood for Doors,5.0,300.0,1500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
8,Delivering Guys,1.0,800.0,800.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
9,Residual,1.0,2380.0,2380.0,2023-06-25,Borehole Drilling,Preconstruction,63.0

In [32]:
df.to_csv('ParadiseView/out/df_borehole_drill.csv', index=False)

In [33]:
pd.read_csv('ParadiseView/out/df_borehole_drill.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Bore Drilling,1.0,95000.0,95000.0,2023-06-24,Borehole Drilling,Preconstruction,63.0
1,Carpenter,1.0,6500.0,6500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
2,Kaye Rod,34.0,180.0,6120.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
4,Big Nale(kg),3.0,100.0,300.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
5,Small Nale(Packs),3.0,350.0,1050.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
6,Wood for Doors,5.0,300.0,1500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
8,Delivering Guys,1.0,800.0,800.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
9,Residual,1.0,2380.0,2380.0,2023-06-25,Borehole Drilling,Preconstruction,63.0