In [51]:
import numpy as np
import pandas as pd

In [2]:
cost_data = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx")

In [48]:
pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\mrsuf\miniconda3\Lib\site-packages (3.0.2)
Requirement already satisfied: openpyxl in C:\Users\mrsuf\miniconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mrsuf\miniconda3\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mrsuf\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\mrsuf\miniconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in C:\Users\mrsuf\miniconda3\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\mrsuf\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
cost_columns = np.array(['item', 'cost_D', 'cost_$', 'Date'])

In [8]:
cost_columns

array(['item', 'cost_D', 'cost_$', 'Date'], dtype='<U6')

In [9]:
df_cost = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx", skiprows=10, nrows=12)

In [10]:
df_cost

                   ITEM  COST(D)     COST($)        DATE
0       Physical Plan 1      1500   30.612245 2019-08-09
1       Physical Plan 2      1000   20.408163 2019-12-17
2          MoneyTra Fee       490   10.000000 2020-02-06
3       Physical Plan 2      2000   40.816327 2020-02-07
4            GTBank Fee      5000  102.040816 2020-02-07
5           Gas for Car       500   10.204082 2020-02-07
6   Chief Area Council       2000   40.816327 2020-02-10
7           Gas for Car       500   10.204082 2020-02-10
8     Lady Filled Forms       400    8.163265 2020-02-10
9         Sukuta Alkalo      1500   30.612245 2020-02-11
10                  Gas       100    2.040816 2020-02-11

In [11]:
df_cost.columns

Index(['ITEM', 'COST(D) ', 'COST($) ', 'DATE'], dtype='str')

In [12]:
df_cost.rename(columns={"COST(D) ": "cost_dalasi", "COST($) ": "cost_dollar"}, inplace=True)

In [13]:
df_cost.columns = df_cost.columns.str.lower()

In [14]:
df_cost

                   item  cost_dalasi  cost_dollar       date
0       Physical Plan 1         1500    30.612245 2019-08-09
1       Physical Plan 2         1000    20.408163 2019-12-17
2          MoneyTra Fee          490    10.000000 2020-02-06
3       Physical Plan 2         2000    40.816327 2020-02-07
4            GTBank Fee         5000   102.040816 2020-02-07
5           Gas for Car          500    10.204082 2020-02-07
6   Chief Area Council          2000    40.816327 2020-02-10
7           Gas for Car          500    10.204082 2020-02-10
8     Lady Filled Forms          400     8.163265 2020-02-10
9         Sukuta Alkalo         1500    30.612245 2020-02-11
10                  Gas          100     2.040816 2020-02-11

In [15]:
df_cost['date'] = pd.to_datetime(df_cost['date'])

In [16]:
df_cost

                   item  cost_dalasi  cost_dollar       date
0       Physical Plan 1         1500    30.612245 2019-08-09
1       Physical Plan 2         1000    20.408163 2019-12-17
2          MoneyTra Fee          490    10.000000 2020-02-06
3       Physical Plan 2         2000    40.816327 2020-02-07
4            GTBank Fee         5000   102.040816 2020-02-07
5           Gas for Car          500    10.204082 2020-02-07
6   Chief Area Council          2000    40.816327 2020-02-10
7           Gas for Car          500    10.204082 2020-02-10
8     Lady Filled Forms          400     8.163265 2020-02-10
9         Sukuta Alkalo         1500    30.612245 2020-02-11
10                  Gas          100     2.040816 2020-02-11

In [17]:
df_cost['date'] = df_cost['date'].dt.strftime('%m/%d/%Y')

In [18]:
df_cost

                   item  cost_dalasi  cost_dollar        date
0       Physical Plan 1         1500    30.612245  08/09/2019
1       Physical Plan 2         1000    20.408163  12/17/2019
2          MoneyTra Fee          490    10.000000  02/06/2020
3       Physical Plan 2         2000    40.816327  02/07/2020
4            GTBank Fee         5000   102.040816  02/07/2020
5           Gas for Car          500    10.204082  02/07/2020
6   Chief Area Council          2000    40.816327  02/10/2020
7           Gas for Car          500    10.204082  02/10/2020
8     Lady Filled Forms          400     8.163265  02/10/2020
9         Sukuta Alkalo         1500    30.612245  02/11/2020
10                  Gas          100     2.040816  02/11/2020

In [19]:
df_costDalasiDollar = df_cost

In [20]:
df_costClean = df_cost.drop('cost_dollar', axis=1)

In [21]:
df_costClean

                   item  cost_dalasi        date
0       Physical Plan 1         1500  08/09/2019
1       Physical Plan 2         1000  12/17/2019
2          MoneyTra Fee          490  02/06/2020
3       Physical Plan 2         2000  02/07/2020
4            GTBank Fee         5000  02/07/2020
5           Gas for Car          500  02/07/2020
6   Chief Area Council          2000  02/10/2020
7           Gas for Car          500  02/10/2020
8     Lady Filled Forms          400  02/10/2020
9         Sukuta Alkalo         1500  02/11/2020
10                  Gas          100  02/11/2020

In [49]:
df_costClean.rename(columns={'cost_dalasi': 'cost'}, inplace=True)

In [50]:
df_costClean

                   item  cost        date
0       Physical Plan 1  1500  08/09/2019
1       Physical Plan 2  1000  12/17/2019
2          MoneyTra Fee   490  02/06/2020
3       Physical Plan 2  2000  02/07/2020
4            GTBank Fee  5000  02/07/2020
5           Gas for Car   500  02/07/2020
6   Chief Area Council   2000  02/10/2020
7           Gas for Car   500  02/10/2020
8     Lady Filled Forms   400  02/10/2020
9         Sukuta Alkalo  1500  02/11/2020
10                  Gas   100  02/11/2020

In [24]:
df_costClean.to_csv('ParadiseView/out/costClean1.csv')

In [25]:
%timeit df_costClean.to_csv('ParadiseView/out/costClean1.csv')

5.86 ms ± 133 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [67]:
skiprows = [0,1,2,3,6,7,8,9,10,22,23,24,25]

In [68]:
cost_data2 = pd.read_excel("ParadiseView/Paradise View Expenditures 4.xlsx", skiprows=skiprows)

In [69]:
cost_data2

                             ITEM  COST(D)      COST($)        DATE
0   Paradise View Plot: 20m x 25m   750000  15000.000000 2019-08-03
1                 Physical Plan 1     1500     30.612245 2019-08-09
2                 Physical Plan 2     1000     20.408163 2019-12-17
3                    MoneyTra Fee      490     10.000000 2020-02-06
4                 Physical Plan 2     2000     40.816327 2020-02-07
5                      GTBank Fee     5000    102.040816 2020-02-07
6                     Gas for Car      500     10.204082 2020-02-07
7             Chief Area Council      2000     40.816327 2020-02-10
8                     Gas for Car      500     10.204082 2020-02-10
9               Lady Filled Forms      400      8.163265 2020-02-10
10                  Sukuta Alkalo     1500     30.612245 2020-02-11
11                            Gas      100      2.040816 2020-02-11

In [72]:
cost_data2.rename(columns={'COST(D)': 'cost_dalasi', 'COST($) ': 'cost_dollar'}, inplace=True)

In [73]:
cost_data2

                             ITEM  cost_dalasi   cost_dollar       DATE
0   Paradise View Plot: 20m x 25m       750000  15000.000000 2019-08-03
1                 Physical Plan 1         1500     30.612245 2019-08-09
2                 Physical Plan 2         1000     20.408163 2019-12-17
3                    MoneyTra Fee          490     10.000000 2020-02-06
4                 Physical Plan 2         2000     40.816327 2020-02-07
5                      GTBank Fee         5000    102.040816 2020-02-07
6                     Gas for Car          500     10.204082 2020-02-07
7             Chief Area Council          2000     40.816327 2020-02-10
8                     Gas for Car          500     10.204082 2020-02-10
9               Lady Filled Forms          400      8.163265 2020-02-10
10                  Sukuta Alkalo         1500     30.612245 2020-02-11
11                            Gas          100      2.040816 2020-02-11

In [74]:
cost_data2.columns = cost_data2.columns.str.lower()

In [75]:
cost_data2

                             item  cost_dalasi   cost_dollar       date
0   Paradise View Plot: 20m x 25m       750000  15000.000000 2019-08-03
1                 Physical Plan 1         1500     30.612245 2019-08-09
2                 Physical Plan 2         1000     20.408163 2019-12-17
3                    MoneyTra Fee          490     10.000000 2020-02-06
4                 Physical Plan 2         2000     40.816327 2020-02-07
5                      GTBank Fee         5000    102.040816 2020-02-07
6                     Gas for Car          500     10.204082 2020-02-07
7             Chief Area Council          2000     40.816327 2020-02-10
8                     Gas for Car          500     10.204082 2020-02-10
9               Lady Filled Forms          400      8.163265 2020-02-10
10                  Sukuta Alkalo         1500     30.612245 2020-02-11
11                            Gas          100      2.040816 2020-02-11

In [88]:
cost_data2['date'] = pd.to_datetime(cost_data2['date'])

In [89]:
cost_data2['date'] = cost_data2['date'].dt.strftime("%m/%d/%Y")

In [90]:
cost_data2

                             item  cost_dalasi   cost_dollar        date
0   Paradise View Plot: 20m x 25m       750000  15000.000000  08/03/2019
1                 Physical Plan 1         1500     30.612245  08/09/2019
2                 Physical Plan 2         1000     20.408163  12/17/2019
3                    MoneyTra Fee          490     10.000000  02/06/2020
4                 Physical Plan 2         2000     40.816327  02/07/2020
5                      GTBank Fee         5000    102.040816  02/07/2020
6                     Gas for Car          500     10.204082  02/07/2020
7             Chief Area Council          2000     40.816327  02/10/2020
8                     Gas for Car          500     10.204082  02/10/2020
9               Lady Filled Forms          400      8.163265  02/10/2020
10                  Sukuta Alkalo         1500     30.612245  02/11/2020
11                            Gas          100      2.040816  02/11/2020

In [92]:
df_cost = cost_data2.drop(columns='cost_dollar')

In [93]:
df_cost

                             item  cost_dalasi        date
0   Paradise View Plot: 20m x 25m       750000  08/03/2019
1                 Physical Plan 1         1500  08/09/2019
2                 Physical Plan 2         1000  12/17/2019
3                    MoneyTra Fee          490  02/06/2020
4                 Physical Plan 2         2000  02/07/2020
5                      GTBank Fee         5000  02/07/2020
6                     Gas for Car          500  02/07/2020
7             Chief Area Council          2000  02/10/2020
8                     Gas for Car          500  02/10/2020
9               Lady Filled Forms          400  02/10/2020
10                  Sukuta Alkalo         1500  02/11/2020
11                            Gas          100  02/11/2020

In [95]:
df_costClean = df_cost.rename(columns={'cost_dalasi': 'cost'})

In [96]:
df_costClean

                             item    cost        date
0   Paradise View Plot: 20m x 25m  750000  08/03/2019
1                 Physical Plan 1    1500  08/09/2019
2                 Physical Plan 2    1000  12/17/2019
3                    MoneyTra Fee     490  02/06/2020
4                 Physical Plan 2    2000  02/07/2020
5                      GTBank Fee    5000  02/07/2020
6                     Gas for Car     500  02/07/2020
7             Chief Area Council     2000  02/10/2020
8                     Gas for Car     500  02/10/2020
9               Lady Filled Forms     400  02/10/2020
10                  Sukuta Alkalo    1500  02/11/2020
11                            Gas     100  02/11/2020

In [101]:
df_costClean.to_csv('ParadiseView/out/df_cost_clean.csv', index=False)

In [102]:
df2 = pd.read_csv('ParadiseView/out/df_cost_clean.csv')

In [103]:
df2

                             item    cost        date
0   Paradise View Plot: 20m x 25m  750000  08/03/2019
1                 Physical Plan 1    1500  08/09/2019
2                 Physical Plan 2    1000  12/17/2019
3                    MoneyTra Fee     490  02/06/2020
4                 Physical Plan 2    2000  02/07/2020
5                      GTBank Fee    5000  02/07/2020
6                     Gas for Car     500  02/07/2020
7             Chief Area Council     2000  02/10/2020
8                     Gas for Car     500  02/10/2020
9               Lady Filled Forms     400  02/10/2020
10                  Sukuta Alkalo    1500  02/11/2020
11                            Gas     100  02/11/2020

In [40]:
df_fencing = pd.read_excel("ParadiseView/Paradise View Expenditures 6.xlsx", skiprows=6, sheet_name="Fencing")

In [41]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30,NaN,NaN,NaN
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30,NaN,NaN,NaN
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30,NaN,NaN,NaN
3,Cement,40,285,11400,232.653061,2020-05-06,NaN,NaN,NaN
4,Cement Transport,1,600,600,12.244898,2020-05-06,NaN,NaN,NaN
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06,NaN,NaN,NaN
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06,NaN,NaN,NaN
7,Water for Molding,1,1000,1000,20.408163,2020-05-06,NaN,NaN,NaN
8,Gas for Transport,1,450,450,9.183673,2020-05-06,NaN,NaN,NaN
9,Police Ticket,1,200,200,4.081633,2020-04-29,NaN,NaN,NaN
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08,NaN,NaN,NaN
11,Cement,25,285,7125,145.408163,2020-05-08,NaN,NaN,NaN
12,Cement Transport,25,15,375,7.653061,2020-05-08,NaN,NaN,NaN
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08,NaN,NaN,NaN
14,Gas for Transport,1,200,200,4.081633,2020-05-08,NaN,NaN,NaN
15,Iron Rods,—,4550,4550,92.857143,2020-05-10,NaN,NaN,NaN
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10,NaN,NaN,NaN
17,Gas for Transport,1,125,125,2.551020,2020-05-10,NaN,NaN,NaN
18,Gas for Transport,1,400,400,8.163265,2020-05-16,NaN,NaN,NaN
19,Electric Pipes,4,35,140,2.857143,2020-05-16,NaN,NaN,NaN
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16,NaN,NaN,NaN
21,Kilo of Nales,2,60,120,2.448980,2020-05-16,NaN,NaN,NaN
22,Taxi Fare,1,250,250,5.102041,2020-05-16,NaN,NaN,NaN
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16,NaN,NaN,NaN
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16,NaN,NaN,NaN
25,Cement,—,285,1150,23.469388,2020-05-22,NaN,NaN,NaN
26,Gas for Transport,1,200,200,4.081633,2020-05-22,NaN,NaN,NaN
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22,NaN,NaN,NaN
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22,NaN,NaN,NaN
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22,NaN,NaN,NaN
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22,NaN,NaN,NaN
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22,NaN,NaN,NaN
32,Lock for Gate,1,250,250,5.102041,2020-05-22,NaN,NaN,NaN
33,Gate,1,26000,26000,530.612245,2020-05-22,NaN,NaN,NaN
34,Cement,5,285,1425,29.081633,2020-05-22,NaN,NaN,NaN
35,Cement Transport,5,15,75,1.530612,2020-05-22,NaN,NaN,NaN
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24,NaN,NaN,NaN
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24,NaN,NaN,NaN
38,Finishing,1,1000,1000,20.408163,2020-06-23,NaN,NaN,NaN
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
41,Total,NaN,NaN,112635,2298.673469,NaT,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaT,NaN,225270.0,2286.43
43,1 Dollar = 49 Dalasis,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
47,NaN,OTHER EXPENSES,NaN,NaN,NaN,NaT,NaN,NaN,NaN
48,WHO,AMOUNT(D),AMOUNT($),DATE,NaN,NaT,NaN,NaN,NaN
49,Papa jara,2000,40.816327,2020-03-23 00:00:00,NaN,NaT,NaN,NaN,NaN
50,Bubacarr Fai,1500,30.612245,2020-04-29 00:00:00,NaN,NaT,NaN,NaN,NaN
51,Papa jara,2000,40.816327,2020-05-23 00:00:00,NaN,NaT,NaN,NaN,NaN
52,Bubacarr Fai,2000,40.816327,2020-05-23 00:00:00,NaN,NaT,NaN,NaN,NaN
53,Papa Jara,2500,51.020408,2022-04-23 00:00:00,NaN,NaT,NaN,NaN,NaN
54,Bubacarr Fai,2500,51.020408,2022-04-23 00:00:00,NaN,NaT,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
56,Total,12500,255.102041,NaN,NaN,NaT,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
58,1 Dollar = 49 Dalasis,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [42]:
df_fencing = df_fencing.drop(df_fencing.iloc[40:].index)

In [43]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30,NaN,NaN,NaN
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30,NaN,NaN,NaN
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30,NaN,NaN,NaN
3,Cement,40,285,11400,232.653061,2020-05-06,NaN,NaN,NaN
4,Cement Transport,1,600,600,12.244898,2020-05-06,NaN,NaN,NaN
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06,NaN,NaN,NaN
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06,NaN,NaN,NaN
7,Water for Molding,1,1000,1000,20.408163,2020-05-06,NaN,NaN,NaN
8,Gas for Transport,1,450,450,9.183673,2020-05-06,NaN,NaN,NaN
9,Police Ticket,1,200,200,4.081633,2020-04-29,NaN,NaN,NaN
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08,NaN,NaN,NaN
11,Cement,25,285,7125,145.408163,2020-05-08,NaN,NaN,NaN
12,Cement Transport,25,15,375,7.653061,2020-05-08,NaN,NaN,NaN
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08,NaN,NaN,NaN
14,Gas for Transport,1,200,200,4.081633,2020-05-08,NaN,NaN,NaN
15,Iron Rods,—,4550,4550,92.857143,2020-05-10,NaN,NaN,NaN
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10,NaN,NaN,NaN
17,Gas for Transport,1,125,125,2.551020,2020-05-10,NaN,NaN,NaN
18,Gas for Transport,1,400,400,8.163265,2020-05-16,NaN,NaN,NaN
19,Electric Pipes,4,35,140,2.857143,2020-05-16,NaN,NaN,NaN
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16,NaN,NaN,NaN
21,Kilo of Nales,2,60,120,2.448980,2020-05-16,NaN,NaN,NaN
22,Taxi Fare,1,250,250,5.102041,2020-05-16,NaN,NaN,NaN
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16,NaN,NaN,NaN
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16,NaN,NaN,NaN
25,Cement,—,285,1150,23.469388,2020-05-22,NaN,NaN,NaN
26,Gas for Transport,1,200,200,4.081633,2020-05-22,NaN,NaN,NaN
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22,NaN,NaN,NaN
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22,NaN,NaN,NaN
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22,NaN,NaN,NaN
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22,NaN,NaN,NaN
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22,NaN,NaN,NaN
32,Lock for Gate,1,250,250,5.102041,2020-05-22,NaN,NaN,NaN
33,Gate,1,26000,26000,530.612245,2020-05-22,NaN,NaN,NaN
34,Cement,5,285,1425,29.081633,2020-05-22,NaN,NaN,NaN
35,Cement Transport,5,15,75,1.530612,2020-05-22,NaN,NaN,NaN
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24,NaN,NaN,NaN
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24,NaN,NaN,NaN
38,Finishing,1,1000,1000,20.408163,2020-06-23,NaN,NaN,NaN
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [44]:
df_fencing = df_fencing.drop(df_fencing.iloc[:, 6:], axis=1)

In [45]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,—,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,—,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT

In [46]:
df_fencing.iloc[25:26, 1:2] = 4

In [47]:
df_fencing.iloc[15:16, 1:2] = 1

In [48]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23
39,Money Transfer Fee,NaN,NaN,NaN,NaN,NaT

In [49]:
df_fencing.dropna(inplace=True)

In [50]:
df_fencing

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL($),DATE
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23

In [51]:
df_fencing.columns = df_fencing.columns.str.lower()

In [52]:
df_fencing

,item,quantity,unit price(d),total cost(d),total($),date
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23

In [53]:
df_fencing.columns

Index(['item', 'quantity ', 'unit price(d)', 'total cost(d)', 'total($)',
       'date'],
      dtype='str')

In [54]:
df_fencing.rename(columns={'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost', 'total($)': 'total_dollar'}, inplace=True)

In [55]:
df_fencing

,item,quantity,unit_cost,total_cost,total_dollar,date
0,Cutting Trees,1,10000,10000,204.081633,2020-04-30
1,Big Trip of Sand,1,7500,7500,153.061224,2020-04-30
2,Small Trip of Sand,1,4000,4000,81.632653,2020-04-30
3,Cement,40,285,11400,232.653061,2020-05-06
4,Cement Transport,1,600,600,12.244898,2020-05-06
5,Wheelbarrow Rental,1,200,200,4.081633,2020-05-06
6,Molding Bricks,1370,5,6850,139.795918,2020-05-06
7,Water for Molding,1,1000,1000,20.408163,2020-05-06
8,Gas for Transport,1,450,450,9.183673,2020-05-06
9,Police Ticket,1,200,200,4.081633,2020-04-29
10,Trip of Pebbles,1,3500,3500,71.428571,2020-05-08
11,Cement,25,285,7125,145.408163,2020-05-08
12,Cement Transport,25,15,375,7.653061,2020-05-08
13,Papa Jara Transport,1,600,600,12.244898,2020-05-08
14,Gas for Transport,1,200,200,4.081633,2020-05-08
15,Iron Rods,1,4550,4550,92.857143,2020-05-10
16,Iron Rods Transport,1,200,200,4.081633,2020-05-10
17,Gas for Transport,1,125,125,2.551020,2020-05-10
18,Gas for Transport,1,400,400,8.163265,2020-05-16
19,Electric Pipes,4,35,140,2.857143,2020-05-16
20,Wire for Pillar Board,1,100,100,2.040816,2020-05-16
21,Kilo of Nales,2,60,120,2.448980,2020-05-16
22,Taxi Fare,1,250,250,5.102041,2020-05-16
23,Pillar Boardrent 2Ds,14,50,700,14.285714,2020-05-16
24,Pillar Iron Rods,4,600,2400,48.979592,2020-05-16
25,Cement,4,285,1150,23.469388,2020-05-22
26,Gas for Transport,1,200,200,4.081633,2020-05-22
27,Pillar Mold Rental,4,500,2000,40.816327,2020-05-22
28,Pillar Board Rental,6,25,150,3.061224,2020-02-22
29,Pillar & Board Trasp,1,1000,1000,20.408163,2020-05-22
30,Pillar Pebbel,1,3000,3000,61.224490,2020-05-22
31,Pillar Pebbel Trasport,1,400,400,8.163265,2020-05-22
32,Lock for Gate,1,250,250,5.102041,2020-05-22
33,Gate,1,26000,26000,530.612245,2020-05-22
34,Cement,5,285,1425,29.081633,2020-05-22
35,Cement Transport,5,15,75,1.530612,2020-05-22
36,Fence Building Fee,1,12000,12000,244.897959,2020-05-24
37,Water for Fencing,1,1000,1000,20.408163,2020-05-24
38,Finishing,1,1000,1000,20.408163,2020-06-23

In [56]:
df_fencing['date'] = df_fencing['date'].dt.strftime('%m/%d/%Y')

In [57]:
df_fencing

,item,quantity,unit_cost,total_cost,total_dollar,date
0,Cutting Trees,1,10000,10000,204.081633,04/30/2020
1,Big Trip of Sand,1,7500,7500,153.061224,04/30/2020
2,Small Trip of Sand,1,4000,4000,81.632653,04/30/2020
3,Cement,40,285,11400,232.653061,05/06/2020
4,Cement Transport,1,600,600,12.244898,05/06/2020
5,Wheelbarrow Rental,1,200,200,4.081633,05/06/2020
6,Molding Bricks,1370,5,6850,139.795918,05/06/2020
7,Water for Molding,1,1000,1000,20.408163,05/06/2020
8,Gas for Transport,1,450,450,9.183673,05/06/2020
9,Police Ticket,1,200,200,4.081633,04/29/2020
10,Trip of Pebbles,1,3500,3500,71.428571,05/08/2020
11,Cement,25,285,7125,145.408163,05/08/2020
12,Cement Transport,25,15,375,7.653061,05/08/2020
13,Papa Jara Transport,1,600,600,12.244898,05/08/2020
14,Gas for Transport,1,200,200,4.081633,05/08/2020
15,Iron Rods,1,4550,4550,92.857143,05/10/2020
16,Iron Rods Transport,1,200,200,4.081633,05/10/2020
17,Gas for Transport,1,125,125,2.551020,05/10/2020
18,Gas for Transport,1,400,400,8.163265,05/16/2020
19,Electric Pipes,4,35,140,2.857143,05/16/2020
20,Wire for Pillar Board,1,100,100,2.040816,05/16/2020
21,Kilo of Nales,2,60,120,2.448980,05/16/2020
22,Taxi Fare,1,250,250,5.102041,05/16/2020
23,Pillar Boardrent 2Ds,14,50,700,14.285714,05/16/2020
24,Pillar Iron Rods,4,600,2400,48.979592,05/16/2020
25,Cement,4,285,1150,23.469388,05/22/2020
26,Gas for Transport,1,200,200,4.081633,05/22/2020
27,Pillar Mold Rental,4,500,2000,40.816327,05/22/2020
28,Pillar Board Rental,6,25,150,3.061224,02/22/2020
29,Pillar & Board Trasp,1,1000,1000,20.408163,05/22/2020
30,Pillar Pebbel,1,3000,3000,61.224490,05/22/2020
31,Pillar Pebbel Trasport,1,400,400,8.163265,05/22/2020
32,Lock for Gate,1,250,250,5.102041,05/22/2020
33,Gate,1,26000,26000,530.612245,05/22/2020
34,Cement,5,285,1425,29.081633,05/22/2020
35,Cement Transport,5,15,75,1.530612,05/22/2020
36,Fence Building Fee,1,12000,12000,244.897959,05/24/2020
37,Water for Fencing,1,1000,1000,20.408163,05/24/2020
38,Finishing,1,1000,1000,20.408163,06/23/2020

In [60]:
df_fencing_clean = df_fencing.drop('total_dollar', axis=1)

In [61]:
df_fencing_clean

                      item quantity  unit_cost total_cost        date
0            Cutting Trees         1     10000      10000  04/30/2020
1         Big Trip of Sand         1      7500       7500  04/30/2020
2       Small Trip of Sand         1      4000       4000  04/30/2020
3                  Cement         40       285      11400  05/06/2020
4        Cement Transport          1       600        600  05/06/2020
5       Wheelbarrow Rental         1       200        200  05/06/2020
6           Molding Bricks      1370         5       6850  05/06/2020
7       Water for Molding          1      1000       1000  05/06/2020
8       Gas for Transport          1       450        450  05/06/2020
9           Police Ticket          1       200        200  04/29/2020
10        Trip of Pebbles          1      3500       3500  05/08/2020
11                 Cement         25       285       7125  05/08/2020
12       Cement Transport         25        15        375  05/08/2020
13     Papa Jara Transport         1       600        600  05/08/2020
14      Gas for Transport          1       200        200  05/08/2020
15               Iron Rods         1      4550       4550  05/10/2020
16    Iron Rods Transport          1       200        200  05/10/2020
17      Gas for Transport          1       125        125  05/10/2020
18      Gas for Transport          1       400        400  05/16/2020
19         Electric Pipes          4        35        140  05/16/2020
20   Wire for Pillar Board         1       100        100  05/16/2020
21           Kilo of Nales         2        60        120  05/16/2020
22              Taxi Fare          1       250        250  05/16/2020
23    Pillar Boardrent 2Ds        14        50        700  05/16/2020
24        Pillar Iron Rods         4       600       2400  05/16/2020
25                 Cement          4       285       1150  05/22/2020
26      Gas for Transport          1       200        200  05/22/2020
27     Pillar Mold Rental          4       500       2000  05/22/2020
28    Pillar Board Rental          6        25        150  02/22/2020
29    Pillar & Board Trasp         1      1000       1000  05/22/2020
30           Pillar Pebbel         1      3000       3000  05/22/2020
31  Pillar Pebbel Trasport         1       400        400  05/22/2020
32           Lock for Gate         1       250        250  05/22/2020
33                    Gate         1     26000      26000  05/22/2020
34                 Cement          5       285       1425  05/22/2020
35       Cement Transport          5        15         75  05/22/2020
36      Fence Building Fee         1     12000      12000  05/24/2020
37      Water for Fencing          1      1000       1000  05/24/2020
38              Finishing          1      1000       1000  06/23/2020

In [62]:
df_fencing_clean.to_csv('ParadiseView/out/df_fencing_clean.csv', index=False)

In [63]:
pd.read_csv('ParadiseView/out/df_fencing_clean.csv')

                      item  quantity   unit_cost  total_cost        date
0            Cutting Trees          1      10000       10000  04/30/2020
1         Big Trip of Sand          1       7500        7500  04/30/2020
2       Small Trip of Sand          1       4000        4000  04/30/2020
3                  Cement          40        285       11400  05/06/2020
4        Cement Transport           1        600         600  05/06/2020
5       Wheelbarrow Rental          1        200         200  05/06/2020
6           Molding Bricks       1370          5        6850  05/06/2020
7       Water for Molding           1       1000        1000  05/06/2020
8       Gas for Transport           1        450         450  05/06/2020
9           Police Ticket           1        200         200  04/29/2020
10        Trip of Pebbles           1       3500        3500  05/08/2020
11                 Cement          25        285        7125  05/08/2020
12       Cement Transport          25         15         375  05/08/2020
13     Papa Jara Transport          1        600         600  05/08/2020
14      Gas for Transport           1        200         200  05/08/2020
15               Iron Rods          1       4550        4550  05/10/2020
16    Iron Rods Transport           1        200         200  05/10/2020
17      Gas for Transport           1        125         125  05/10/2020
18      Gas for Transport           1        400         400  05/16/2020
19         Electric Pipes           4         35         140  05/16/2020
20   Wire for Pillar Board          1        100         100  05/16/2020
21           Kilo of Nales          2         60         120  05/16/2020
22              Taxi Fare           1        250         250  05/16/2020
23    Pillar Boardrent 2Ds         14         50         700  05/16/2020
24        Pillar Iron Rods          4        600        2400  05/16/2020
25                 Cement           4        285        1150  05/22/2020
26      Gas for Transport           1        200         200  05/22/2020
27     Pillar Mold Rental           4        500        2000  05/22/2020
28    Pillar Board Rental           6         25         150  02/22/2020
29    Pillar & Board Trasp          1       1000        1000  05/22/2020
30           Pillar Pebbel          1       3000        3000  05/22/2020
31  Pillar Pebbel Trasport          1        400         400  05/22/2020
32           Lock for Gate          1        250         250  05/22/2020
33                    Gate          1      26000       26000  05/22/2020
34                 Cement           5        285        1425  05/22/2020
35       Cement Transport           5         15          75  05/22/2020
36      Fence Building Fee          1      12000       12000  05/24/2020
37      Water for Fencing           1       1000        1000  05/24/2020
38              Finishing           1       1000        1000  06/23/2020

In [3]:
import pandas as pd
import numpy as np

In [107]:
otherExp = pd.read_excel("ParadiseView\Paradise View Expenditures 4.xlsx", skiprows=55, sheet_name="Fencing")

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\mrsuf\AppData\Local\Temp\ipykernel_13112\138199166.py:1: SyntaxWarning: invalid escape sequence '\P'
  otherExp = pd.read_excel("ParadiseView\Paradise View Expenditures 4.xlsx", skiprows=55, sheet_name="Fencing")

In [108]:
otherExp

,WHO,AMOUNT(D),AMOUNT($),DATE,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Papa jara,2000.0,40.816327,2020-03-23,NaN,NaN,NaN,NaN,NaN
1,Bubacarr Fai,1500.0,30.612245,2020-04-29,NaN,NaN,NaN,NaN,NaN
2,Papa jara,2000.0,40.816327,2020-05-23,NaN,NaN,NaN,NaN,NaN
3,Bubacarr Fai,2000.0,40.816327,2020-05-23,NaN,NaN,NaN,NaN,NaN
4,Papa Jara,2500.0,51.020408,2022-04-23,NaN,NaN,NaN,NaN,NaN
5,Bubacarr Fai,2500.0,51.020408,2022-04-23,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
7,Total,12500.0,255.102041,NaT,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
9,1 Dollar = 49 Dalasis,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [109]:
otherExp.drop(['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',], axis=1, inplace=True)

In [110]:
otherExp

                     WHO  AMOUNT(D)   AMOUNT($)       DATE
0              Papa jara     2000.0   40.816327 2020-03-23
1           Bubacarr Fai     1500.0   30.612245 2020-04-29
2              Papa jara     2000.0   40.816327 2020-05-23
3           Bubacarr Fai     2000.0   40.816327 2020-05-23
4             Papa Jara      2500.0   51.020408 2022-04-23
5           Bubacarr Fai     2500.0   51.020408 2022-04-23
6                    NaN        NaN         NaN        NaT
7                  Total    12500.0  255.102041        NaT
8                    NaN        NaN         NaN        NaT
9  1 Dollar = 49 Dalasis        NaN         NaN        NaT

In [111]:
otherExp.dropna(inplace=True)

In [112]:
otherExp

            WHO  AMOUNT(D)  AMOUNT($)       DATE
0     Papa jara     2000.0  40.816327 2020-03-23
1  Bubacarr Fai     1500.0  30.612245 2020-04-29
2     Papa jara     2000.0  40.816327 2020-05-23
3  Bubacarr Fai     2000.0  40.816327 2020-05-23
4    Papa Jara      2500.0  51.020408 2022-04-23
5  Bubacarr Fai     2500.0  51.020408 2022-04-23

In [113]:
otherExp.rename(columns={'WHO': 'item', 'AMOUNT(D)': 'unit_cost'}, inplace=True)

In [114]:
otherExp

           item  unit_cost  AMOUNT($)       DATE
0     Papa jara     2000.0  40.816327 2020-03-23
1  Bubacarr Fai     1500.0  30.612245 2020-04-29
2     Papa jara     2000.0  40.816327 2020-05-23
3  Bubacarr Fai     2000.0  40.816327 2020-05-23
4    Papa Jara      2500.0  51.020408 2022-04-23
5  Bubacarr Fai     2500.0  51.020408 2022-04-23

In [115]:
otherExp.columns

Index(['item', 'unit_cost', 'AMOUNT($)', 'DATE'], dtype='str')

In [116]:
otherExp.drop('AMOUNT($)', axis=1, inplace=True)

In [117]:
otherExp

           item  unit_cost       DATE
0     Papa jara     2000.0 2020-03-23
1  Bubacarr Fai     1500.0 2020-04-29
2     Papa jara     2000.0 2020-05-23
3  Bubacarr Fai     2000.0 2020-05-23
4    Papa Jara      2500.0 2022-04-23
5  Bubacarr Fai     2500.0 2022-04-23

In [118]:
otherExp.columns = otherExp.columns.str.lower()

In [119]:
otherExp

           item  unit_cost       date
0     Papa jara     2000.0 2020-03-23
1  Bubacarr Fai     1500.0 2020-04-29
2     Papa jara     2000.0 2020-05-23
3  Bubacarr Fai     2000.0 2020-05-23
4    Papa Jara      2500.0 2022-04-23
5  Bubacarr Fai     2500.0 2022-04-23

In [120]:
otherExp['date'] = otherExp['date'].dt.strftime('%m/%d/%Y')

In [121]:
otherExp

           item  unit_cost        date
0     Papa jara     2000.0  03/23/2020
1  Bubacarr Fai     1500.0  04/29/2020
2     Papa jara     2000.0  05/23/2020
3  Bubacarr Fai     2000.0  05/23/2020
4    Papa Jara      2500.0  04/23/2022
5  Bubacarr Fai     2500.0  04/23/2022

In [122]:
otherExp['quantity'] = 1

otherExp

In [123]:
otherExp

           item  unit_cost        date  quantity
0     Papa jara     2000.0  03/23/2020         1
1  Bubacarr Fai     1500.0  04/29/2020         1
2     Papa jara     2000.0  05/23/2020         1
3  Bubacarr Fai     2000.0  05/23/2020         1
4    Papa Jara      2500.0  04/23/2022         1
5  Bubacarr Fai     2500.0  04/23/2022         1

In [124]:
otherExp['total_cost'] = otherExp['unit_cost'] * otherExp['quantity']

In [125]:
otherExp

           item  unit_cost        date  quantity  total_cost
0     Papa jara     2000.0  03/23/2020         1      2000.0
1  Bubacarr Fai     1500.0  04/29/2020         1      1500.0
2     Papa jara     2000.0  05/23/2020         1      2000.0
3  Bubacarr Fai     2000.0  05/23/2020         1      2000.0
4    Papa Jara      2500.0  04/23/2022         1      2500.0
5  Bubacarr Fai     2500.0  04/23/2022         1      2500.0

In [129]:
otherExp = otherExp.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date'])

In [130]:
otherExp

           item  quantity  unit_cost  total_cost        date
0     Papa jara         1     2000.0      2000.0  03/23/2020
1  Bubacarr Fai         1     1500.0      1500.0  04/29/2020
2     Papa jara         1     2000.0      2000.0  05/23/2020
3  Bubacarr Fai         1     2000.0      2000.0  05/23/2020
4    Papa Jara          1     2500.0      2500.0  04/23/2022
5  Bubacarr Fai         1     2500.0      2500.0  04/23/2022

In [132]:
otherExp.to_csv('ParadiseView/out/df_otherExp_clean.csv', index=False)

In [4]:
otherExp = pd.read_csv('ParadiseView/out/df_otherExp_clean.csv')

In [5]:
otherExp

           item  quantity  unit_cost  total_cost        date
0     Papa jara         1     2000.0      2000.0  03/23/2020
1  Bubacarr Fai         1     1500.0      1500.0  04/29/2020
2     Papa jara         1     2000.0      2000.0  05/23/2020
3  Bubacarr Fai         1     2000.0      2000.0  05/23/2020
4    Papa Jara          1     2500.0      2500.0  04/23/2022
5  Bubacarr Fai         1     2500.0      2500.0  04/23/2022

In [20]:
otherExp['item'] = np.where(otherExp['item'].str.contains('Papa jara', case=False, na=False), 'Papa Jara', otherExp['item'])

In [21]:
otherExp['item'] = np.where(otherExp['item'].str.contains('Bubacarr Fai', case=False, na=False), 'Bubacarr Faye', otherExp['item'])

In [22]:
otherExp

            item  quantity  unit_cost  total_cost        date
0      Papa Jara         1     2000.0      2000.0  03/23/2020
1  Bubacarr Faye         1     1500.0      1500.0  04/29/2020
2      Papa Jara         1     2000.0      2000.0  05/23/2020
3  Bubacarr Faye         1     2000.0      2000.0  05/23/2020
4      Papa Jara         1     2500.0      2500.0  04/23/2022
5  Bubacarr Faye         1     2500.0      2500.0  04/23/2022

In [37]:
otherExp['sub_category'] = 'Fencing'
otherExp['category'] = 'Preconstruction'
otherExp['exchange_rate'] = 49.00

In [46]:
otherExp['date'] = np.where(otherExp['date'] == pd.to_datetime('2022-04-23'), pd.to_datetime('2020-04-23'), otherExp['date'])

In [48]:
otherExp['date'] = pd.to_datetime(otherExp['date'])

In [49]:
otherExp

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Papa Jara,1,2000.0,2000.0,2020-03-23,Fencing,Preconstruction,49.0
1,Bubacarr Faye,1,1500.0,1500.0,2020-04-29,Fencing,Preconstruction,49.0
2,Papa Jara,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
3,Bubacarr Faye,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
4,Papa Jara,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0
5,Bubacarr Faye,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0

In [50]:
otherExp.to_csv('ParadiseView/out/df_otherExp_clean.csv', index=False)

In [4]:
filepath = "ParadiseView/Paradise View Expenditures 4.xlsx"
outFilePath = 'ParadiseView/out',

In [5]:
f_floorMolding = pd.read_excel(filepath, sheet_name='Brick Molding', skiprows=4)

In [6]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00,NaN,NaN,NaN,NaN
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00,NaN,NaN,NaN,NaN
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total,NaN,7750,7750,155,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,BRICK MOLDING EXPENSES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE,NaN,NaN,NaN,NaN
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00,NaN,NaN,NaN,NaN
13,Cement,75,320,24000,480,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00,NaN,NaN,NaN,"D1,500 missing from the D50,000"
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
21,Gasoline,1,300,300,6,2022-04-18 00:00:00,NaN,NaN,NaN,NaN
22,Missing,—-,—,1500,30,NaN,NaN,NaN,NaN,"D1,000 given to Kasaru"
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00,NaN,NaN,NaN,NaN
24,Cement,120,325,39000,780,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
27,Small Tank,1,800,800,16,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
29,Gasoline,1,500,500,10,2022-04-20 00:00:00,NaN,NaN,NaN,NaN
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00,NaN,NaN,NaN,NaN
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00,NaN,NaN,NaN,NaN
32,Bricks Payment,4210,6,25260,505.2,NaN,NaN,NaN,NaN,NaN
33,Over Payment,1,1800,1800,36,NaN,NaN,NaN,NaN,NaN
34,Big Sand Trip,1,8000,8000,160,NaN,NaN,NaN,NaN,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN,NaN,NaN,NaN,NaN
36,Cement,55,330,18150,363,NaN,NaN,NaN,NaN,NaN
37,Cement Transport,55,15,825,16.5,NaN,NaN,NaN,NaN,NaN
38,Bricks payment,2675,6,16050,321,NaN,NaN,NaN,NaN,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Total,NaN,NaN,195000,3900,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
f_floorMolding.drop(columns=['Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'], inplace=True)

In [8]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Total,NaN,7750,7750,155,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,BRICK MOLDING EXPENSES,NaN,NaN,NaN
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----
40,NaN,NaN,NaN,NaN,NaN,NaN
41,Total,NaN,NaN,195000,3900,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN
43,1 Dollar = 50 Dalasis,NaN,NaN,NaN,NaN,NaN

In [9]:
f_floorMolding.dropna(thresh=len(f_floorMolding.columns) - 1, inplace=True)

In [10]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----

In [11]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
11,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----

In [12]:
f_floorMolding.drop(f_floorMolding[f_floorMolding['ITEM'] == 'ITEM'].index, inplace =True)

In [13]:
f_floorMolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00
14,Cement Transport,75,20,1500,30,2022-04-18 00:00:00
15,Wheelbarrow,1,3000,3000,60,2022-04-18 00:00:00
16,50m Hose/Pipe,1,1400,1400,28,2022-04-18 00:00:00
17,Small Bucket,2,100,200,4,2022-04-18 00:00:00
18,Big Sand Trip,2,8000,16000,320,2022-04-18 00:00:00
19,Small Tank,1,1600,1600,32,2022-04-18 00:00:00
20,Cement Watchman,1,500,500,10,2022-04-18 00:00:00
21,Gasoline,1,300,300,6,2022-04-18 00:00:00
22,Missing,—-,—,1500,30,NaN
23,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-19 00:00:00
24,Cement,120,325,39000,780,2022-04-20 00:00:00
25,Cement Transport,120,15,1800,36,2022-04-20 00:00:00
26,Big Sand Trip,1,8000,8000,160,2022-04-20 00:00:00
27,Small Tank,1,800,800,16,2022-04-20 00:00:00
28,Wheelbarrow Tire,1,700,700,14,2022-04-20 00:00:00
29,Gasoline,1,500,500,10,2022-04-20 00:00:00
30,"$1,000 Transfer Fee",1,600,600,12,2022-04-22 00:00:00
31,Big Sand Trip,2,8000,16000,320,2022-04-23 00:00:00
32,Bricks Payment,4210,6,25260,505.2,NaN
33,Over Payment,1,1800,1800,36,NaN
34,Big Sand Trip,1,8000,8000,160,NaN
35,6Wheel Sand Trip,1,5500,5500,110,NaN
36,Cement,55,330,18150,363,NaN
37,Cement Transport,55,15,825,16.5,NaN
38,Bricks payment,2675,6,16050,321,NaN
39,Needs To Be Determined,.---,.---,15,0.3,.----

In [14]:
f_floorMolding.columns = f_floorMolding.columns.str.lower()

In [15]:
f_floorMolding.head()

,item,quantity,unit price(d),total cost(d),cost($),date
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00

In [16]:
f_floorMolding.rename(columns={'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [17]:
f_floorMolding.head()

,item,quantity,unit_cost,total_cost,cost($),date
0,$100 Transfer Fee,1,250,250,5,2022-03-27 00:00:00
1,Cutting Trees,1,5000,5000,100,2022-04-03 00:00:00
2,Clearing Plot,1,2500,2500,50,2022-04-03 00:00:00
12,"$1,000 Transfer Fee",1,1000,1000,20,2022-04-16 00:00:00
13,Cement,75,320,24000,480,2022-04-18 00:00:00

In [18]:
f_floorMolding.drop(columns='cost($)', inplace=True)

In [19]:
#f_floorMolding['date'] = f_floorMolding['date'].dt.strftime('%m/%d/%Y')

In [20]:
f_floorMolding

                      item quantity  unit_cost total_cost                 date
0        $100 Transfer Fee         1       250        250  2022-03-27 00:00:00
1            Cutting Trees         1      5000       5000  2022-04-03 00:00:00
2            Clearing Plot         1      2500       2500  2022-04-03 00:00:00
12     $1,000 Transfer Fee         1      1000       1000  2022-04-16 00:00:00
13                 Cement         75       320      24000  2022-04-18 00:00:00
14        Cement Transport        75        20       1500  2022-04-18 00:00:00
15            Wheelbarrow          1      3000       3000  2022-04-18 00:00:00
16          50m Hose/Pipe          1      1400       1400  2022-04-18 00:00:00
17           Small Bucket          2       100        200  2022-04-18 00:00:00
18           Big Sand Trip         2      8000      16000  2022-04-18 00:00:00
19             Small Tank          1      1600       1600  2022-04-18 00:00:00
20         Cement Watchman         1       500        500  2022-04-18 00:00:00
21               Gasoline          1       300        300  2022-04-18 00:00:00
22                Missing         —-         —       1500                  NaN
23     $1,000 Transfer Fee         1      1000       1000  2022-04-19 00:00:00
24                 Cement        120       325      39000  2022-04-20 00:00:00
25        Cement Transport       120        15       1800  2022-04-20 00:00:00
26           Big Sand Trip         1      8000       8000  2022-04-20 00:00:00
27             Small Tank          1       800        800  2022-04-20 00:00:00
28       Wheelbarrow Tire          1       700        700  2022-04-20 00:00:00
29               Gasoline          1       500        500  2022-04-20 00:00:00
30     $1,000 Transfer Fee         1       600        600  2022-04-22 00:00:00
31          Big Sand Trip          2      8000      16000  2022-04-23 00:00:00
32         Bricks Payment       4210         6      25260                  NaN
33           Over Payment          1      1800       1800                  NaN
34           Big Sand Trip         1      8000       8000                  NaN
35        6Wheel Sand Trip         1      5500       5500                  NaN
36                 Cement         55       330      18150                  NaN
37       Cement Transport         55        15        825                  NaN
38         Bricks payment       2675         6      16050                  NaN
39  Needs To Be Determined      .---      .---         15                .----

In [21]:
import pandas as pd
from datetime import date, datetime

In [22]:
f_floorMolding.at[22, 'date'] = '2022-04-18 00:00:00'

In [23]:
f_floorMolding.loc[32:, 'date'] = '2022-04-23 00:00:00'

In [24]:
f_floorMolding.loc[f_floorMolding['item'] == 'Missing', 'date'] = 1

In [25]:
f_floorMolding.at[32, 'unit_cost'] = 6.00

In [26]:
f_floorMolding.at[22, 'unit_cost'] = 1500

In [27]:
f_floorMolding.at[39, 'quantity '] = 1
f_floorMolding.at[39, 'unit_cost'] = 15

In [48]:
f_floorMolding.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [31]:
f_floorMolding['date'] = pd.to_datetime(f_floorMolding['date'])

In [32]:
f_floorMolding['date'].info

<bound method Series.info of 0    2022-03-27
1    2022-04-03
2    2022-04-03
12   2022-04-16
13   2022-04-18
14   2022-04-18
15   2022-04-18
16   2022-04-18
17   2022-04-18
18   2022-04-18
19   2022-04-18
20   2022-04-18
21   2022-04-18
22   2022-04-18
23   2022-04-19
24   2022-04-20
25   2022-04-20
26   2022-04-20
27   2022-04-20
28   2022-04-20
29   2022-04-20
30   2022-04-22
31   2022-04-23
32   2022-04-23
33   2022-04-23
34   2022-04-23
35   2022-04-23
36   2022-04-23
37   2022-04-23
38   2022-04-23
39   2022-04-23
Name: date, dtype: datetime64[us]>

In [33]:
f_floorMolding['date'] = f_floorMolding['date'].dt.strftime('%m/%d/%Y')

In [49]:
f_floorMolding

                      item quantity unit_cost total_cost        date
0        $100 Transfer Fee        1       250        250  03/27/2022
1            Cutting Trees        1      5000       5000  04/03/2022
2            Clearing Plot        1      2500       2500  04/03/2022
12     $1,000 Transfer Fee        1      1000       1000  04/16/2022
13                 Cement        75       320      24000  04/18/2022
14        Cement Transport       75        20       1500  04/18/2022
15            Wheelbarrow         1      3000       3000  04/18/2022
16          50m Hose/Pipe         1      1400       1400  04/18/2022
17           Small Bucket         2       100        200  04/18/2022
18           Big Sand Trip        2      8000      16000  04/18/2022
19             Small Tank         1      1600       1600  04/18/2022
20         Cement Watchman        1       500        500  04/18/2022
21               Gasoline         1       300        300  04/18/2022
22                Missing        —-      1500       1500  04/18/2022
23     $1,000 Transfer Fee        1      1000       1000  04/19/2022
24                 Cement       120       325      39000  04/20/2022
25        Cement Transport      120        15       1800  04/20/2022
26           Big Sand Trip        1      8000       8000  04/20/2022
27             Small Tank         1       800        800  04/20/2022
28       Wheelbarrow Tire         1       700        700  04/20/2022
29               Gasoline         1       500        500  04/20/2022
30     $1,000 Transfer Fee        1       600        600  04/22/2022
31          Big Sand Trip         2      8000      16000  04/23/2022
32         Bricks Payment      4210       6.0      25260  04/23/2022
33           Over Payment         1      1800       1800  04/23/2022
34           Big Sand Trip        1      8000       8000  04/23/2022
35        6Wheel Sand Trip        1      5500       5500  04/23/2022
36                 Cement        55       330      18150  04/23/2022
37       Cement Transport        55        15        825  04/23/2022
38         Bricks payment      2675         6      16050  04/23/2022
39  Needs To Be Determined        1        15         15  04/23/2022

In [59]:
f_floorMolding['sub_category'] = 'Brick Molding'

In [60]:
f_floorMolding['category'] = '1st Floor'

In [61]:
f_floorMolding

,item,quantity,unit_cost,total_cost,date,sub_category,category
0,$100 Transfer Fee,1,250,250,03/27/2022,Brick Molding,1st Floor
1,Cutting Trees,1,5000,5000,04/03/2022,Brick Molding,1st Floor
2,Clearing Plot,1,2500,2500,04/03/2022,Brick Molding,1st Floor
12,"$1,000 Transfer Fee",1,1000,1000,04/16/2022,Brick Molding,1st Floor
13,Cement,75,320,24000,04/18/2022,Brick Molding,1st Floor
14,Cement Transport,75,20,1500,04/18/2022,Brick Molding,1st Floor
15,Wheelbarrow,1,3000,3000,04/18/2022,Brick Molding,1st Floor
16,50m Hose/Pipe,1,1400,1400,04/18/2022,Brick Molding,1st Floor
17,Small Bucket,2,100,200,04/18/2022,Brick Molding,1st Floor
18,Big Sand Trip,2,8000,16000,04/18/2022,Brick Molding,1st Floor
19,Small Tank,1,1600,1600,04/18/2022,Brick Molding,1st Floor
20,Cement Watchman,1,500,500,04/18/2022,Brick Molding,1st Floor
21,Gasoline,1,300,300,04/18/2022,Brick Molding,1st Floor
22,Missing,1,1500,1500,04/18/2022,Brick Molding,1st Floor
23,"$1,000 Transfer Fee",1,1000,1000,04/19/2022,Brick Molding,1st Floor
24,Cement,120,325,39000,04/20/2022,Brick Molding,1st Floor
25,Cement Transport,120,15,1800,04/20/2022,Brick Molding,1st Floor
26,Big Sand Trip,1,8000,8000,04/20/2022,Brick Molding,1st Floor
27,Small Tank,1,800,800,04/20/2022,Brick Molding,1st Floor
28,Wheelbarrow Tire,1,700,700,04/20/2022,Brick Molding,1st Floor
29,Gasoline,1,500,500,04/20/2022,Brick Molding,1st Floor
30,"$1,000 Transfer Fee",1,600,600,04/22/2022,Brick Molding,1st Floor
31,Big Sand Trip,2,8000,16000,04/23/2022,Brick Molding,1st Floor
32,Bricks Payment,4210,6.0,25260,04/23/2022,Brick Molding,1st Floor
33,Over Payment,1,1800,1800,04/23/2022,Brick Molding,1st Floor
34,Big Sand Trip,1,8000,8000,04/23/2022,Brick Molding,1st Floor
35,6Wheel Sand Trip,1,5500,5500,04/23/2022,Brick Molding,1st Floor
36,Cement,55,330,18150,04/23/2022,Brick Molding,1st Floor
37,Cement Transport,55,15,825,04/23/2022,Brick Molding,1st Floor
38,Bricks payment,2675,6,16050,04/23/2022,Brick Molding,1st Floor
39,Needs To Be Determined,1,15,15,04/23/2022,Brick Molding,1st Floor

In [ ]:
f_floorMolding.to_csv('ParadiseView/out/df_ffBrickMoldingClean.csv', index=False)  # 'ParadiseView/out/df_otherExp_clean.csv'

In [63]:
pd.read_csv('ParadiseView/out/df_ffBrickMoldingClean.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category
0,$100 Transfer Fee,1,250.0,250,03/27/2022,Brick Molding,1st Floor
1,Cutting Trees,1,5000.0,5000,04/03/2022,Brick Molding,1st Floor
2,Clearing Plot,1,2500.0,2500,04/03/2022,Brick Molding,1st Floor
3,"$1,000 Transfer Fee",1,1000.0,1000,04/16/2022,Brick Molding,1st Floor
4,Cement,75,320.0,24000,04/18/2022,Brick Molding,1st Floor
5,Cement Transport,75,20.0,1500,04/18/2022,Brick Molding,1st Floor
6,Wheelbarrow,1,3000.0,3000,04/18/2022,Brick Molding,1st Floor
7,50m Hose/Pipe,1,1400.0,1400,04/18/2022,Brick Molding,1st Floor
8,Small Bucket,2,100.0,200,04/18/2022,Brick Molding,1st Floor
9,Big Sand Trip,2,8000.0,16000,04/18/2022,Brick Molding,1st Floor
10,Small Tank,1,1600.0,1600,04/18/2022,Brick Molding,1st Floor
11,Cement Watchman,1,500.0,500,04/18/2022,Brick Molding,1st Floor
12,Gasoline,1,300.0,300,04/18/2022,Brick Molding,1st Floor
13,Missing,1,1500.0,1500,04/18/2022,Brick Molding,1st Floor
14,"$1,000 Transfer Fee",1,1000.0,1000,04/19/2022,Brick Molding,1st Floor
15,Cement,120,325.0,39000,04/20/2022,Brick Molding,1st Floor
16,Cement Transport,120,15.0,1800,04/20/2022,Brick Molding,1st Floor
17,Big Sand Trip,1,8000.0,8000,04/20/2022,Brick Molding,1st Floor
18,Small Tank,1,800.0,800,04/20/2022,Brick Molding,1st Floor
19,Wheelbarrow Tire,1,700.0,700,04/20/2022,Brick Molding,1st Floor
20,Gasoline,1,500.0,500,04/20/2022,Brick Molding,1st Floor
21,"$1,000 Transfer Fee",1,600.0,600,04/22/2022,Brick Molding,1st Floor
22,Big Sand Trip,2,8000.0,16000,04/23/2022,Brick Molding,1st Floor
23,Bricks Payment,4210,6.0,25260,04/23/2022,Brick Molding,1st Floor
24,Over Payment,1,1800.0,1800,04/23/2022,Brick Molding,1st Floor
25,Big Sand Trip,1,8000.0,8000,04/23/2022,Brick Molding,1st Floor
26,6Wheel Sand Trip,1,5500.0,5500,04/23/2022,Brick Molding,1st Floor
27,Cement,55,330.0,18150,04/23/2022,Brick Molding,1st Floor
28,Cement Transport,55,15.0,825,04/23/2022,Brick Molding,1st Floor
29,Bricks payment,2675,6.0,16050,04/23/2022,Brick Molding,1st Floor
30,Needs To Be Determined,1,15.0,15,04/23/2022,Brick Molding,1st Floor