In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, date

In [17]:
contractor_consul = pd.read_excel('ParadiseView/Paradise View Expenditures 4.xlsx', sheet_name='Consultation', skiprows= 4)

In [25]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,Consulting Contractors,1,4000,4000,65.04065,2023-09-25 00:00:00
1,NaN,NaN,NaN,NaN,NaN,NaN
2,Total,NaN,4000,4000,65.04065,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,1 Dollar = 61.5 Dalasis,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Preparing Land for Construction,NaN,NaN,NaN,NaN
9,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
10,Clearing the Area,1,8000,8000,125,2023-12-21 00:00:00
11,Transportation,1,2000,2000,31.25,2023-12-21 00:00:00
12,Total,NaN,10000,10000,156.25,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Other Expenses,NaN,NaN,NaN,NaN
21,WHO,AMOUNT(D),AMOUNT($),DATE,NaN,NaN
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN
24,Total,2000,31.25,NaN,NaN,NaN
25,1 Dollar = 64 Dalasis,NaN,NaN,NaN,NaN,NaN

In [55]:
contractor_consul.dropna(thresh = (len(contractor_consul.columns) - 2), axis=0, inplace=True)

In [56]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,Consulting Contractors,1,4000,4000,65.04065,2023-09-25 00:00:00
2,Total,NaN,4000,4000,65.04065,NaN
9,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
10,Clearing the Area,1,8000,8000,125,2023-12-21 00:00:00
11,Transportation,1,2000,2000,31.25,2023-12-21 00:00:00
12,Total,NaN,10000,10000,156.25,NaN
21,WHO,AMOUNT(D),AMOUNT($),DATE,NaN,NaN
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN,NaN

In [59]:
contractor_consul = contractor_consul.drop(index=[2,9,12,21])

In [60]:
contractor_consul

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),COST($),DATE
0,Consulting Contractors,1,4000,4000,65.04065,2023-09-25 00:00:00
10,Clearing the Area,1,8000,8000,125,2023-12-21 00:00:00
11,Transportation,1,2000,2000,31.25,2023-12-21 00:00:00
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN,NaN

In [67]:
contractor_consul.drop(columns='COST($)')

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),DATE,QUANTITY
0,Consulting Contractors,1,4000,4000,2023-09-25 00:00:00,NaN
10,Clearing the Area,1,8000,8000,2023-12-21 00:00:00,NaN
11,Transportation,1,2000,2000,2023-12-21 00:00:00,NaN
22,Bubacarr Fai,2000,31.25,2023-12-20 00:00:00,NaN,1.0

In [83]:
contractor_consul.columns =contractor_consul.columns.str.lower()
contractor_consul.rename(columns={'quantity ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [92]:
contractor_consul.loc[22, 'date'] ='2023-12-20 00:00:00'

In [98]:
 contractor_consul.drop(columns='cost($)', inplace=True)

In [111]:
contractor_consul

                      item quantity unit_cost total_cost                 date
0   Consulting Contractors        1      4000       4000  2023-09-25 00:00:00
10       Clearing the Area        1      8000       8000  2023-12-21 00:00:00
11         Transportation         1      2000       2000  2023-12-21 00:00:00
22            Bubacarr Fai        1      2000       2000  2023-12-20 00:00:00

In [159]:
contractor_consul['date'] = pd.to_datetime(contractor_consul['date'])

In [161]:
contractor_consul['date'] = contractor_consul['date'].dt.strftime('%m/%d/%Y')

In [168]:
contractor_consul['sub_category'] = 'Contractor Consultation'
contractor_consul['category'] = 'Preconstruction'

In [186]:
contractor_consul['exchange_rate'] = 61.50

In [187]:
contractor_consul.loc[1:, 'exchange_rate'] = 64.00

In [6]:
contractor_consul

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Consulting Contractors,1,4000,4000,2023-09-25,Contractor Consultation,Preconstruction,61.5
1,Clearing the Area,1,8000,8000,2023-12-21,Contractor Consultation,Preconstruction,64.0
2,Transportation,1,2000,2000,2023-12-21,Contractor Consultation,Preconstruction,64.0
3,Bubacarr Fai,1,2000,2000,2023-12-20,Contractor Consultation,Preconstruction,64.0

In [ ]:
contractor_consul['date'] = pd.to_datetime(contractor_consul['date'])

In [7]:
contractor_consul.to_csv('ParadiseView/out/df_contractor_consul.csv', index=False)

In [8]:
contractor_consul = pd.read_csv('ParadiseView/out/df_contractor_consul.csv')

In [10]:
contractor_consul

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Consulting Contractors,1,4000,4000,2023-09-25,Contractor Consultation,Preconstruction,61.5
1,Clearing the Area,1,8000,8000,2023-12-21,Contractor Consultation,Preconstruction,64.0
2,Transportation,1,2000,2000,2023-12-21,Contractor Consultation,Preconstruction,64.0
3,Bubacarr Fai,1,2000,2000,2023-12-20,Contractor Consultation,Preconstruction,64.0