In [1]:
import pandas as pd
import numpy as np
from datetime import date, datetime

In [297]:
firstFloor_const = pd.read_excel('ParadiseView/Paradise View Expenditures 4.xlsx', sheet_name='1st Floor Construction ', skiprows=5)

In [298]:
firstFloor_const

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL COST($),Date,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,1 by 2 wood,25,100.0,2500.0,37.037037,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wooden Pake,15,35.0,500.0,7.407407,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3 Inches Nale(kg),2,100.0,200.0,2.962963,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D50 each for D525 for 15 pieces but he let it ...,NaN
3,2 and half Inches Nale(kg),2,100.0,200.0,2.962963,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Materials Transportation,1,500.0,500.0,7.407407,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50m Water hose is 1800 but got it 1500,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103865,NaN,NaN,NaN,NaN,NaN,NaN

In [299]:
firstFloor_const.drop(columns=['Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15'], inplace=True)

In [300]:
firstFloor_const.drop(firstFloor_const[360:].index, inplace=True)

In [301]:
firstFloor_const.tail(20)

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL COST($),Date
340,Cement,25,NaN,NaN,NaN,2025-04-24 00:00:00
341,Momo Waggeh Watering,1,2100.0,2100.0,NaN,2025-05-10 00:00:00
342,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,NaN,2025-05-10 00:00:00
343,Returning Roof Concrete Materials,1,8500.0,8500.0,NaN,2025-05-17 00:00:00
344,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN
346,NaN,NaN,369010.0,596800.0,NaN,NaN
347,NaN,NaN,NaN,NaN,NaN,NaN
348,NaN,NaN,NaN,NaN,NaN,NaN
349,NaN,NaN,NaN,NaN,NaN,NaN
350,NaN,NaN,965810.0,NaN,NaN,NaN
351,NaN,NaN,NaN,NaN,NaN,NaN
352,NaN,NaN,NaN,NaN,NaN,NaN
353,NaN,NaN,NaN,NaN,NaN,NaN
354,NaN,NaN,NaN,NaN,NaN,NaN
355,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,NaN,NaN,NaN,NaN,NaN
357,Total,NaN,NaN,3458385.0,7667.11329,NaN
358,NaN,NaN,NaN,NaN,NaN,NaN
359,1 Dollar = 67.50 Dalasis,NaN,NaN,NaN,NaN,NaN

In [302]:
firstFloor_const.drop(firstFloor_const.tail(16).index, inplace=True)

In [303]:
firstFloor_const.dropna(thresh=2, inplace=True)

In [304]:
firstFloor_const.tail()

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),TOTAL COST($),Date
339,Stone(10 Wheels),1,14000.0,14000.0,NaN,2025-04-24 00:00:00
340,Cement,25,NaN,NaN,NaN,2025-04-24 00:00:00
341,Momo Waggeh Watering,1,2100.0,2100.0,NaN,2025-05-10 00:00:00
342,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,NaN,2025-05-10 00:00:00
343,Returning Roof Concrete Materials,1,8500.0,8500.0,NaN,2025-05-17 00:00:00

In [305]:
firstFloor_const.columns= firstFloor_const.columns.str.lower()

In [306]:
firstFloor_const.columns

Index(['item', 'quantity ', 'unit price(d)', 'total cost(d)', 'total cost($)',
       'date'],
      dtype='str')

In [307]:
firstFloor_const.rename(columns={'quantity ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [308]:
firstFloor_const.drop(columns='total cost($)', inplace=True)

In [309]:
firstFloor_const.tail()

,item,quantity,unit_cost,total_cost,date
339,Stone(10 Wheels),1,14000.0,14000.0,2025-04-24 00:00:00
340,Cement,25,NaN,NaN,2025-04-24 00:00:00
341,Momo Waggeh Watering,1,2100.0,2100.0,2025-05-10 00:00:00
342,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,2025-05-10 00:00:00
343,Returning Roof Concrete Materials,1,8500.0,8500.0,2025-05-17 00:00:00

In [310]:
firstFloor_const.at[340, 'unit_cost'] = 390

In [311]:
firstFloor_const.at[340, 'total_cost'] = 390 * 25

In [312]:
firstFloor_const.info()

<class 'pandas.DataFrame'>
Index: 338 entries, 0 to 343
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    object
 1   quantity    338 non-null    object
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        337 non-null    object
dtypes: float64(2), object(3)
memory usage: 23.9+ KB

In [313]:
firstFloor_const.tail(10)

,item,quantity,unit_cost,total_cost,date
334,Cement,350,385.0,134750.0,2025-04-23 00:00:00
335,Generator Rope repair,1,150.0,150.0,2025-04-24 00:00:00
336,Sulayman Juwara 4th Payment,1,100000.0,100000.0,2025-04-24 00:00:00
337,Workers' Lunch for Concreting Day,1,2500.0,2500.0,2025-04-24 00:00:00
338,Sand(10 Wheels),1,8000.0,8000.0,2025-04-24 00:00:00
339,Stone(10 Wheels),1,14000.0,14000.0,2025-04-24 00:00:00
340,Cement,25,390.0,9750.0,2025-04-24 00:00:00
341,Momo Waggeh Watering,1,2100.0,2100.0,2025-05-10 00:00:00
342,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,2025-05-10 00:00:00
343,Returning Roof Concrete Materials,1,8500.0,8500.0,2025-05-17 00:00:00

In [314]:
firstFloor_const.info()

<class 'pandas.DataFrame'>
Index: 338 entries, 0 to 343
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    object
 1   quantity    338 non-null    object
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        337 non-null    object
dtypes: float64(2), object(3)
memory usage: 23.9+ KB

In [315]:
#firstFloor_const.loc[len(firstFloor_const)] = ['Cement Transport', 25, 20, 500, '2025-04-24 01:00:00']

In [316]:
firstFloor_const.info()

<class 'pandas.DataFrame'>
Index: 338 entries, 0 to 343
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    object
 1   quantity    338 non-null    object
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        337 non-null    object
dtypes: float64(2), object(3)
memory usage: 23.9+ KB

In [317]:
firstFloor_const[firstFloor_const['total_cost'] == 500]

,item,quantity,unit_cost,total_cost,date
1,Wooden Pake,15,35.0,500.0,2024-01-01 00:00:00
4,Materials Transportation,1,500.0,500.0,2024-01-01 00:00:00
40,Momo Waggeh,1,500.0,500.0,2024-02-20 00:00:00
57,Gas + Nails,1,500.0,500.0,3/13-23/24
72,"Nail(kg) 3""",5,100.0,500.0,2024-04-04 00:00:00
73,"Nail(kg) 2 1/2""",5,100.0,500.0,2024-04-04 00:00:00
75,Timber 1 by 6 Transport,1,500.0,500.0,2024-04-07 00:00:00
99,Watering the Bricks,1,500.0,500.0,2024-05-10 00:00:00
126,Binding Wire(Bundle),1,500.0,500.0,2024-07-04 00:00:00
137,Cement Transport,25,20.0,500.0,2024-09-04 00:00:00
138,Momo Waggeh arranging Bricks,1,500.0,500.0,2025-09-04 00:00:00
141,Cement Transport,25,20.0,500.0,2024-09-09 00:00:00
168,Cement Transport,25,20.0,500.0,2024-10-24 00:00:00
180,1x2 Wood,5,100.0,500.0,2024-11-04 00:00:00
197,Manganasy uprooting,1,500.0,500.0,2024-12-18 00:00:00
211,Gas for the Generator,1,500.0,500.0,2025-02-18 00:00:00
214,Gas for the Generator,1,500.0,500.0,2025-03-04 00:00:00
238,Cement Transport,25,20.0,500.0,2025-03-26 00:00:00
240,Gas for the Generator,1,500.0,500.0,2025-03-26 00:00:00
243,Binding Wire(Bundle),1,500.0,500.0,2025-03-27 00:00:00
252,Cement Transport,25,20.0,500.0,2025-04-03 00:00:00
281,12mm Plywood Transport,1,500.0,500.0,2025-04-14 00:00:00
296,Pick Axe,1,500.0,500.0,2025-04-18 00:00:00
316,Oil for Generator,1,500.0,500.0,2025-05-02 00:00:00

In [320]:
firstFloor_const.to_csv('ParadiseView/out/firstFloor_const.csv', index=False)

In [3]:
firstFloor_Construction = pd.read_csv('ParadiseView/out/firstFloor_const.csv')

In [4]:
firstFloor_Construction

,item,quantity,unit_cost,total_cost,date
0,1 by 2 wood,25,100.0,2500.0,2024-01-01 00:00:00
1,Wooden Pake,15,35.0,500.0,2024-01-01 00:00:00
2,3 Inches Nale(kg),2,100.0,200.0,2024-01-01 00:00:00
3,2 and half Inches Nale(kg),2,100.0,200.0,2024-01-01 00:00:00
4,Materials Transportation,1,500.0,500.0,2024-01-01 00:00:00
...,...,...,...,...,...
333,Stone(10 Wheels),1,14000.0,14000.0,2025-04-24 00:00:00
334,Cement,25,390.0,9750.0,2025-04-24 00:00:00
335,Momo Waggeh Watering,1,2100.0,2100.0,2025-05-10 00:00:00
336,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,2025-05-10 00:00:00
337,Returning Roof Concrete Materials,1,8500.0,8500.0,2025-05-17 00:00:00

In [5]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    str
 1   quantity    338 non-null    int64
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        337 non-null    str
dtypes: float64(2), int64(1), str(2)
memory usage: 13.3 KB

In [6]:
#firstFloor_Construction.loc[len(firstFloor_Construction)] = ['Cement Transport', 25, 20, 500, '2025-04-24 01:00:00']

In [7]:
firstFloor_Construction.head()

,item,quantity,unit_cost,total_cost,date
0,1 by 2 wood,25,100.0,2500.0,2024-01-01 00:00:00
1,Wooden Pake,15,35.0,500.0,2024-01-01 00:00:00
2,3 Inches Nale(kg),2,100.0,200.0,2024-01-01 00:00:00
3,2 and half Inches Nale(kg),2,100.0,200.0,2024-01-01 00:00:00
4,Materials Transportation,1,500.0,500.0,2024-01-01 00:00:00

In [8]:
firstFloor_Construction[firstFloor_Construction['item'] == 'Sadaqa']

       item  quantity  unit_cost  total_cost date
102  Sadaqa         1     3000.0      3000.0  NaN

In [29]:
#firstFloor_Construction.at[102, 'date'] = '2024-05-26 00:00:00'

In [30]:
firstFloor_Construction.loc[57]

item                 Gas + Nails
quantity                        1
unit_cost                   500.0
total_cost                  500.0
date          2024-03-13 00:00:00
Name: 57, dtype: object

In [31]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    str
 1   quantity    338 non-null    int64
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        338 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 13.3 KB

In [50]:
firstFloor_Construction.at[57, 'date'] = '2024-03-13 00:00:00'

In [62]:
firstFloor_Construction.at[46, 'date'] = '2024-03-05'

In [89]:
firstFloor_Construction.at[106, 'date'] = '2024-05-28'

In [90]:
firstFloor_Construction.at[122, 'date'] = '2024-06-14'

In [98]:
firstFloor_Construction.at[119, 'date'] = '2024-06-10'

In [99]:
firstFloor_Construction.at[134, 'date'] = '2024-08-05'

In [115]:
firstFloor_Construction.at[135, 'date'] = '2024-08-04'

In [116]:
firstFloor_Construction.at[138, 'date'] = '2024-09-04'

In [136]:
firstFloor_Construction.at[139, 'date'] = '2024-09-04'

In [141]:
firstFloor_Construction.at[146, 'date'] = '2024-09-18'

In [146]:
firstFloor_Construction.at[155, 'date'] = '2024-09-30'

In [154]:
firstFloor_Construction.at[176, 'date'] = '2024-10-28'

In [155]:
firstFloor_Construction.at[196, 'date'] = '2024-12-04'

In [33]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    str
 1   quantity    338 non-null    int64
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        338 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 13.3 KB

In [34]:
firstFloor_Construction['date'] = pd.to_datetime(firstFloor_Construction['date']) #, dayfirst=True)

In [35]:
firstFloor_Construction.head()

                          item  quantity  unit_cost  total_cost       date
0                  1 by 2 wood        25      100.0      2500.0 2024-01-01
1                  Wooden Pake        15       35.0       500.0 2024-01-01
2           3 Inches Nale(kg)          2      100.0       200.0 2024-01-01
3  2 and half Inches Nale(kg)          2      100.0       200.0 2024-01-01
4    Materials Transportation          1      500.0       500.0 2024-01-01

In [23]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    str
 1   quantity    338 non-null    int64
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        337 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 13.3 KB

In [24]:
#firstFloor_Construction['date'] = firstFloor_Construction['date'].dt.strftime('%m/%d/%Y')

In [36]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        338 non-null    str
 1   quantity    338 non-null    int64
 2   unit_cost   338 non-null    float64
 3   total_cost  338 non-null    float64
 4   date        338 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 13.3 KB

In [37]:
firstFloor_Construction.head()

                          item  quantity  unit_cost  total_cost       date
0                  1 by 2 wood        25      100.0      2500.0 2024-01-01
1                  Wooden Pake        15       35.0       500.0 2024-01-01
2           3 Inches Nale(kg)          2      100.0       200.0 2024-01-01
3  2 and half Inches Nale(kg)          2      100.0       200.0 2024-01-01
4    Materials Transportation          1      500.0       500.0 2024-01-01

In [38]:
firstFloor_Construction['sub_category'] = 'Construction'
firstFloor_Construction['category'] = '1st Floor'

In [41]:
start_date = '01/01/2024'
end_date = '03/03/2024'
mask = firstFloor_Construction[firstFloor_Construction['date'].between(start_date, end_date)]

In [42]:
mask;

In [125]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between(start_date, end_date), 'exchange_rate'] = 67.50

In [126]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('03/04/2024', '03/27/2024'), 'exchange_rate'] = 68.00

In [127]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('03/28/2024', '04/23/2024'), 'exchange_rate'] = 68.20

In [128]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('04/24/2024', '05/26/2024'), 'exchange_rate'] = 68.80

In [156]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('05/27/2024', '06/01/2024'), 'exchange_rate'] = 69.70

In [157]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('06/02/2024', '09/16/2024'), 'exchange_rate'] = 69.25

In [158]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('09/17/2024', '11/11/2024'), 'exchange_rate'] = 71.00

In [159]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('1/12/2024', '03/26/2025'), 'exchange_rate'] = 71.20

In [163]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('03/27/2025', '04/07/2025'), 'exchange_rate'] = 72.25

In [165]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('04/08/2025', '04/12/2025'), 'exchange_rate'] = 72.50

In [167]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('04/13/2025', '04/18/2025'), 'exchange_rate'] = 72.60

In [169]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('04/19/2025', '05/04/2025'), 'exchange_rate'] = 72.85

In [171]:
firstFloor_Construction.loc[firstFloor_Construction['date'].between('05/05/2025', '05/17/2025'), 'exchange_rate'] = 72.25

In [175]:
firstFloor_Construction.drop(columns='data', inplace=True)

In [182]:
print(firstFloor_Construction.to_string())

                                     item  quantity  unit_cost  total_cost                 date  sub_category   category  exchange_rate
0                             1 by 2 wood        25      100.0      2500.0  2024-01-01 00:00:00  Construction  1st Floor          67.50
1                             Wooden Pake        15       35.0       500.0  2024-01-01 00:00:00  Construction  1st Floor          67.50
2                      3 Inches Nale(kg)          2      100.0       200.0  2024-01-01 00:00:00  Construction  1st Floor          67.50
3             2 and half Inches Nale(kg)          2      100.0       200.0  2024-01-01 00:00:00  Construction  1st Floor          67.50
4               Materials Transportation          1      500.0       500.0  2024-01-01 00:00:00  Construction  1st Floor          67.50
5              Floor Plan Copy/Laminating         1      550.0       550.0  2024-01-02 00:00:00  Construction  1st Floor          67.50
6                     50m Water Hose/Pipe         1     1500.0      1500.0  2024-01-06 00:00:00  Construction  1st Floor          67.50
7                          Iron Rod(12mm)       100      540.0     54000.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
8                           Iron Rod(6mm)       100      150.0     15000.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
9                                  Cement       100      405.0     40500.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
10                           Wheelbarrow          1     2700.0      2700.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
11                   Binding Wire(Bundle)         2      425.0       850.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
12              Materials Transportation          1     3800.0      3800.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
13                        Sand(10 Wheels)         1     7500.0      7500.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
14               Clean Pebble(10 Wheels)          1    12000.0     12000.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
15            Sulaiman Juwara(Contractor)         1   100000.0    100000.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
16                   Bubacar Fai Payment          1    12000.0     12000.0  2024-01-11 00:00:00  Construction  1st Floor          67.50
17            Asphalt Stones(double trip)         1    84000.0     84000.0  2024-01-27 00:00:00  Construction  1st Floor          71.20
18               Cement For Guard's Room          7      400.0      2800.0  2024-01-29 00:00:00  Construction  1st Floor          71.20
19                     Transport(Cements)         1      150.0       150.0  2024-01-29 00:00:00  Construction  1st Floor          71.20
20              Guard's Room Fl Concrete          1     3000.0      3000.0  2024-01-29 00:00:00  Construction  1st Floor          71.20
21                              Mattress          1     2300.0      2300.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
22                    Mattress Transport          1      300.0       300.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
23                         Machete Knife          1      200.0       200.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
24                                   Lock         2      125.0       250.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
25                  Kettle and Prayer Mat         1      275.0       275.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
26                     Chain For Door(1m)         1      300.0       300.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
27                        Slide Bolt Lock         1       60.0        60.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
28               Flashlight with Battery          1       90.0        90.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
29                   Carpenter for Locks          1      200.0       200.0  2024-02-05 00:00:00  Construction  1st Floor          71.20
30               Borehole Reinstallation          1      800.0       800.0  2024-02-13 00:00:00  Construction  1st Floor          71.20
31                  Guard Room Door locks         1      125.0       125.0  2024-02-13 00:00:00  Construction  1st Floor          71.20
32                             Carpenter          1      200.0       200.0  2024-02-13 00:00:00  Construction  1st Floor          71.20
33                               Tap Head         1      350.0       350.0  2024-02-13 00:00:00  Construction  1st Floor          71.20
34                    Generator Transport         1      600.0       600.0  2024-02-14 00:00:00  Construction  1st Floor          71.20
35                           1 by 12 Wood         8      650.0      5200.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
36                1 by 12 Wood Transport          1      700.0       700.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
37                             Generator          1    11000.0     11000.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
38                   Generator Transport          1      600.0       600.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
39                 Gas for the Generator          1      400.0       400.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
40                            Momo Waggeh         1      500.0       500.0  2024-02-20 00:00:00  Construction  1st Floor          71.20
41             Rice(50kg) for Momo Waggeh         1     2000.0      2000.0  2024-02-24 00:00:00  Construction  1st Floor          71.20
42                        Sand(10 Wheels)         1     7500.0      7500.0  2024-03-01 00:00:00  Construction  1st Floor          71.20
43                                Cement        100      395.0     39500.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
44                      Cement Transport          1     2000.0      2000.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
45                            1 by 2 Wood        60      100.0      6000.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
46                         Plywood(12mm)         10     1550.0     15500.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
47                Splitting 12mm plywood         10       75.0       750.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
48                12mm plywood Transport          1      700.0       700.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
49            Momo Waggeh Salary (March)          1     4000.0      4000.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
50                               Nail(kg)         9      100.0       900.0  2024-03-05 00:00:00  Construction  1st Floor          71.20
51                   Binding Wire(Bundle)         2      475.0       950.0  2024-03-12 00:00:00  Construction  1st Floor          71.20
52                       PS 10mm Iron Rod       100      340.0     34000.0  2024-03-12 00:00:00  Construction  1st Floor          71.20
53             Binding Wire+IronRod Trans         1      800.0       800.0  2024-03-12 00:00:00  Construction  1st Floor          71.20
54                   Workers Ramadan Gift         1      400.0       400.0  2024-03-12 00:00:00  Construction  1st Floor          71.20
55                          Iron Rod(6mm)        25      150.0      3750.0  2024-03-13 00:00:00  Construction  1st Floor          71.20
56                         6mm Transport          1      400.0       400.0  2024-03-13 00:00:00  Construction  1st Floor          71.20
57                           Gas + Nails          1      500.0       500.0  2024-03-13 00:00:00  Construction  1st Floor          71.20
58                        Sand(10 Wheels)         1     7500.0      7500.0  2024-03-23 00:00:00  Construction  1st Floor          71.20
59                            BCF Ramadan         1     2000.0      2000.0  2024-03-24 00:00:00  Construction  1st Floor          71.20
60                                 Cement        50      390.0     19500.0  2024-03-25 00:00:00  Construction  1st Floor          71.20
61                      Cement Transport         50       20.0      1000.0  2024-03-25 00:00:00  Construction  1st Floor          71.20
62                 Gas for the Generator          1      300.0       300.0  2024-03-27 00:00:00  Construction  1st Floor          71.20
63                         Iron Rod(12mm)        90      510.0     45900.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
64                         Iron Rod(10mm)       100      325.0     32500.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
65                        PS 6mm Iron Rod        85      135.0     11400.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
66                   Binding Wire(Bundle)         3      400.0      1200.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
67          Iron Rod + Binding Wire Trans         1     2000.0      2000.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
68                       Timber for Sappo        20      200.0      4000.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
69                      Timber Transport          1      650.0       650.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
70                        Sand(10 Wheels)         1     7500.0      7500.0  2024-03-29 00:00:00  Construction  1st Floor          71.20
71             Momo Waggeh Salary (April)         1     4000.0      4000.0  2024-04-04 00:00:00  Construction  1st Floor          71.20
72                            Nail(kg) 3"         5      100.0       500.0  2024-04-04 00:00:00  Construction  1st Floor          71.20
73                        Nail(kg) 2 1/2"         5      100.0       500.0  2024-04-04 00:00:00  Construction  1st Floor          71.20
74                          Timber 1 by 6        10      300.0      3000.0  2024-04-07 00:00:00  Construction  1st Floor          71.20
75               Timber 1 by 6 Transport          1      500.0       500.0  2024-04-07 00:00:00  Construction  1st Floor          71.20
76               Wheelbarrow Maintenance          2     1000.0      2000.0  2024-04-08 00:00:00  Construction  1st Floor          71.20
77           Momo Waggeh Salary(advanced)         1     4000.0      4000.0  2024-04-19 00:00:00  Construction  1st Floor          71.20
78         Moving Sand from the Yard(1st)         1      350.0       350.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
79         Moving Sand from the Yard(2nd)         2      350.0       700.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
80         Moving Sand from the Yard(3rd)         4      400.0      1600.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
81         Moving Sand from the Yard(4th)         3      500.0      1500.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
82                                 Cement        50      390.0     19500.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
83                      Cement Transport         50       20.0      1000.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
84                              Tape Head         1      350.0       350.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
85                             Tape Cover         1      150.0       150.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
86                    Lock for Tape Cover         1      100.0       100.0  2024-04-23 00:00:00  Construction  1st Floor          71.20
87                        Sand(10 Wheels)         1     7500.0      7500.0  2024-04-26 00:00:00  Construction  1st Floor          71.20
88                 Gas for the Generator          1      375.0       375.0  2024-04-29 00:00:00  Construction  1st Floor          71.20
89      Generator Leaking Repair + Trans          1      700.0       700.0  2024-04-29 00:00:00  Construction  1st Floor          71.20
90                                 Cement        50      395.0     19750.0  2024-05-01 00:00:00  Construction  1st Floor          71.20
91                      Cement Transport         50       20.0      1000.0  2024-05-01 00:00:00  Construction  1st Floor          71.20
92                        Sand(10 Wheels)         1     7500.0      7500.0  2024-05-02 00:00:00  Construction  1st Floor          71.20
93                                 Cement        50      380.0     19000.0  2024-05-04 00:00:00  Construction  1st Floor          71.20
94                      Cement Transport         50       20.0      1000.0  2024-05-04 00:00:00  Construction  1st Floor          71.20
95                 Generator Repair + Gas         1     1200.0      1200.0  2024-05-04 00:00:00  Construction  1st Floor          71.20
96                     Oil for Generator          1      150.0       150.0  2024-05-06 00:00:00  Construction  1st Floor          71.20
97                        Sand(10 Wheels)         1     7500.0      7500.0  2024-05-07 00:00:00  Construction  1st Floor          71.20
98                 Gas for the Generator          1      350.0       350.0  2024-05-07 00:00:00  Construction  1st Floor          71.20
99                   Watering the Bricks          1      500.0       500.0  2024-05-10 00:00:00  Construction  1st Floor          71.20
100                       Bricks Molding       3708        6.0     22250.0  2024-05-18 00:00:00  Construction  1st Floor          71.20
101                Gas for the Generator          1      400.0       400.0  2024-05-25 00:00:00  Construction  1st Floor          71.20
102                                Sadaqa         1     3000.0      3000.0  2024-05-26 00:00:00  Construction  1st Floor          71.20
103         Sulaiman Juwarra 2nd Payment          1    80000.0     80000.0  2024-05-27 00:00:00  Construction  1st Floor          71.20
104                        Iron Rod(12mm)       100      540.0     54000.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
105                         Iron Rod(6mm)        25      150.0      3750.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
106                                Cement        30      400.0     12000.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
107              Cement + Rods Transport          1     1400.0      1400.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
108              Clean Pebble(10 Wheels)          1    13500.0     13500.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
109           Asphalt Stones(double trip)         1    95000.0     95000.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
110                       Sand(10 Wheels)         1     7500.0      7500.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
111          Bubacar Fai Advance Payment          6    12000.0     72000.0  2024-05-28 00:00:00  Construction  1st Floor          71.20
112                               Cement         50      400.0     20000.0  2024-05-30 00:00:00  Construction  1st Floor          71.20
113                     Cement Transport         50       30.0      1500.0  2024-05-30 00:00:00  Construction  1st Floor          71.20
114            Momo Waggeh Salary (June)          1     4000.0      4000.0  2024-06-03 00:00:00  Construction  1st Floor          71.20
115                                Cement       100      430.0     43000.0  2024-06-03 00:00:00  Construction  1st Floor          71.20
116                     Cement Transport        100       30.0      3000.0  2024-06-03 00:00:00  Construction  1st Floor          71.20
117                       Sand(10 Wheels)         1     7500.0      7500.0  2024-06-03 00:00:00  Construction  1st Floor          71.20
118                Gas for the Generator          1      950.0       950.0  2024-06-04 00:00:00  Construction  1st Floor          71.20
119                       Sand(10 Wheels)         1     7500.0      7500.0  2024-06-10 00:00:00  Construction  1st Floor          71.20
120                                Cement       100      415.0     41500.0  2024-06-11 00:00:00  Construction  1st Floor          71.20
121                     Cement Transport        100       30.0      3000.0  2024-06-11 00:00:00  Construction  1st Floor          71.20
122                              Nail(kg)         4      100.0       400.0  2024-06-14 00:00:00  Construction  1st Floor          71.20
123             Momo Waggeh Salary (July)         1     4000.0      4000.0  2024-07-05 00:00:00  Construction  1st Floor          71.20
124                       Soft Plywood 6m         1      850.0       850.0  2024-07-04 00:00:00  Construction  1st Floor          71.20
125                              Nail(kg)         2      100.0       200.0  2024-07-04 00:00:00  Construction  1st Floor          71.20
126                  Binding Wire(Bundle)         1      500.0       500.0  2024-07-04 00:00:00  Construction  1st Floor          71.20
127             Plywood + Nail Transport          1      200.0       200.0  2024-07-04 00:00:00  Construction  1st Floor          71.20
128                         1 by 6 Timber         3      350.0      1050.0  2024-07-09 00:00:00  Construction  1st Floor          71.20
129                           1 by 2 Wood         2      100.0       200.0  2024-07-09 00:00:00  Construction  1st Floor          71.20
130                            Cardboard          1      350.0       350.0  2024-07-09 00:00:00  Construction  1st Floor          71.20
131                 1by6 & 1x2 Transport          1      300.0       300.0  2024-07-09 00:00:00  Construction  1st Floor          71.20
132                Gas for the Generator          1      300.0       300.0  2024-07-09 00:00:00  Construction  1st Floor          71.20
133                       Sand(10 Wheels)         1     7500.0      7500.0  2024-07-11 00:00:00  Construction  1st Floor          71.20
134             Momo Waggeh Salary (Aug)          1     4000.0      4000.0  2024-08-05 00:00:00  Construction  1st Floor          71.20
135                       Bricks Molding          1     7140.0      7140.0  2024-08-04 00:00:00  Construction  1st Floor          71.20
136                                Cement        25      400.0     10000.0  2024-09-04 00:00:00  Construction  1st Floor          71.20
137                     Cement Transport         25       20.0       500.0  2024-09-04 00:00:00  Construction  1st Floor          71.20
138          Momo Waggeh arranging Bricks         1      500.0       500.0  2024-09-04 00:00:00  Construction  1st Floor          71.20
139            Momo Waggeh Salary (Sept)          1     4000.0      4000.0  2024-09-04 00:00:00  Construction  1st Floor          71.20
140                                Cement        25      400.0     10000.0  2024-09-09 00:00:00  Construction  1st Floor          71.20
141                     Cement Transport         25       20.0       500.0  2024-09-09 00:00:00  Construction  1st Floor          71.20
142                Gas for the Generator          1      300.0       300.0  2024-09-09 00:00:00  Construction  1st Floor          71.20
143                                Zakaat         1     4000.0      4000.0  2024-09-14 00:00:00  Construction  1st Floor          71.20
144           Sulaiman Juwara 3rd Payment         1    80000.0     80000.0  2024-09-18 00:00:00  Construction  1st Floor          71.20
145                               Cement         50      400.0     20000.0  2024-09-18 00:00:00  Construction  1st Floor          71.20

In [183]:
firstFloor_Construction.info()

<class 'pandas.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           339 non-null    str
 1   quantity       339 non-null    int64
 2   unit_cost      339 non-null    float64
 3   total_cost     339 non-null    float64
 4   date           339 non-null    object
 5   sub_category   339 non-null    str
 6   category       339 non-null    str
 7   exchange_rate  339 non-null    float64
dtypes: float64(3), int64(1), object(1), str(3)
memory usage: 21.3+ KB

In [178]:
firstFloor_Construction[firstFloor_Construction['total_cost'] == 500]

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
1,Wooden Pake,15,35.0,500.0,2024-01-01,Construction,1st Floor,67.50
4,Materials Transportation,1,500.0,500.0,2024-01-01,Construction,1st Floor,67.50
40,Momo Waggeh,1,500.0,500.0,2024-02-20,Construction,1st Floor,71.20
57,Gas + Nails,1,500.0,500.0,2024-03-13,Construction,1st Floor,71.20
72,"Nail(kg) 3""",5,100.0,500.0,2024-04-04,Construction,1st Floor,71.20
73,"Nail(kg) 2 1/2""",5,100.0,500.0,2024-04-04,Construction,1st Floor,71.20
75,Timber 1 by 6 Transport,1,500.0,500.0,2024-04-07,Construction,1st Floor,71.20
99,Watering the Bricks,1,500.0,500.0,2024-05-10,Construction,1st Floor,71.20
126,Binding Wire(Bundle),1,500.0,500.0,2024-07-04,Construction,1st Floor,71.20
137,Cement Transport,25,20.0,500.0,2024-09-04,Construction,1st Floor,71.20
138,Momo Waggeh arranging Bricks,1,500.0,500.0,2024-09-04,Construction,1st Floor,71.20
141,Cement Transport,25,20.0,500.0,2024-09-09,Construction,1st Floor,71.20
168,Cement Transport,25,20.0,500.0,2024-10-24,Construction,1st Floor,71.20
180,1x2 Wood,5,100.0,500.0,2024-11-04,Construction,1st Floor,71.20
197,Manganasy uprooting,1,500.0,500.0,2024-12-18,Construction,1st Floor,71.20
211,Gas for the Generator,1,500.0,500.0,2025-02-18,Construction,1st Floor,71.20
214,Gas for the Generator,1,500.0,500.0,2025-03-04,Construction,1st Floor,71.20
238,Cement Transport,25,20.0,500.0,2025-03-26,Construction,1st Floor,71.20
240,Gas for the Generator,1,500.0,500.0,2025-03-26,Construction,1st Floor,71.20
243,Binding Wire(Bundle),1,500.0,500.0,2025-03-27,Construction,1st Floor,72.25
252,Cement Transport,25,20.0,500.0,2025-04-03,Construction,1st Floor,72.25
281,12mm Plywood Transport,1,500.0,500.0,2025-04-14,Construction,1st Floor,72.60
296,Pick Axe,1,500.0,500.0,2025-04-18,Construction,1st Floor,72.60
316,Oil for Generator,1,500.0,500.0,2025-05-02,Construction,1st Floor,72.85

In [181]:
firstFloor_Construction.loc[len(firstFloor_Construction)] = ['Cement Transport', 25, 20, 500, '2025-04-24 01:00:00', 'Construction', '1st Floor', 72.85]

In [184]:
#Start from here

In [190]:
firstFloor_Construction.to_csv('ParadiseView/out/firstFloor_const.csv', index=False)

In [197]:
first_floor_const['date'] = first_floor_const['date'].dt.date

In [200]:
first_floor_const.to_csv('ParadiseView/out/firstFloor_const.csv', index=False)

In [202]:
first_floor_const = pd.read_csv('ParadiseView/out/firstFloor_const.csv')

In [203]:
first_floor_const

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,1 by 2 wood,25,100.0,2500.0,2024-01-01,Construction,1st Floor,67.50
1,Wooden Pake,15,35.0,500.0,2024-01-01,Construction,1st Floor,67.50
2,3 Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.50
3,2 and half Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.50
4,Materials Transportation,1,500.0,500.0,2024-01-01,Construction,1st Floor,67.50
...,...,...,...,...,...,...,...,...
334,Cement,25,390.0,9750.0,2025-04-24,Construction,1st Floor,72.85
335,Momo Waggeh Watering,1,2100.0,2100.0,2025-05-10,Construction,1st Floor,72.25
336,Momo Waggeh Salary(Upto May 7),1,1000.0,1000.0,2025-05-10,Construction,1st Floor,72.25
337,Returning Roof Concrete Materials,1,8500.0,8500.0,2025-05-17,Construction,1st Floor,72.25
338,Cement Transport,25,20.0,500.0,2025-04-24,Construction,1st Floor,72.85

In [262]:
first_floor_const[first_floor_const['sub_category'] == 'Brick Molding']

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate,sub-category
82,Cement,50,390.0,19500.0,2024-04-23,Brick Molding,1st Floor,71.2,NaN
83,Cement Transport,50,20.0,1000.0,2024-04-23,Brick Molding,1st Floor,71.2,NaN
87,Sand(10 Wheels),1,7500.0,7500.0,2024-04-26,Brick Molding,1st Floor,71.2,NaN
90,Cement,50,395.0,19750.0,2024-05-01,Brick Molding,1st Floor,71.2,NaN
91,Cement Transport,50,20.0,1000.0,2024-05-01,Brick Molding,1st Floor,71.2,NaN
92,Sand(10 Wheels),1,7500.0,7500.0,2024-05-02,Brick Molding,1st Floor,71.2,NaN
93,Cement,50,380.0,19000.0,2024-05-04,Brick Molding,1st Floor,71.2,NaN
94,Cement Transport,50,20.0,1000.0,2024-05-04,Brick Molding,1st Floor,71.2,NaN
97,Sand(10 Wheels),1,7500.0,7500.0,2024-05-07,Brick Molding,1st Floor,71.2,NaN
100,Bricks Molding,3708,6.0,22250.0,2024-05-18,Brick Molding,1st Floor,71.2,NaN
133,Sand(10 Wheels),1,7500.0,7500.0,2024-07-11,Brick Molding,1st Floor,71.2,NaN
135,Bricks Molding,1,7140.0,7140.0,2024-08-04,Brick Molding,1st Floor,71.2,NaN
138,Momo Waggeh arranging Bricks,1,500.0,500.0,2024-09-04,Brick Molding,1st Floor,71.2,Brick Molding
339,Cemennt,38,415.0,15770.0,2024-06-11,Brick Molding,1st Floor,71.2,NaN
340,Cemennt Transport,38,30.0,1140.0,2024-06-11,Brick Molding,1st Floor,71.2,NaN
341,Cemennt Transport,38,30.0,1140.0,2024-06-11,Brick Molding,1st Floor,71.2,NaN

In [211]:
first_floor_const.loc[121, ['quantity', 'total_cost']] = [62, 1860]

In [214]:
first_floor_const.loc[len(first_floor_const)] = ['Cemennt', 38, 415.00, 15770.00, '2024-06-11', 'Brick Molding', '1st Floor', 71.20]

In [221]:
first_floor_const.loc[len(first_floor_const)] = ['Cemennt Transport', 38, 30, 1140.00, '2024-06-11', 'Brick Molding', '1st Floor', 71.20]

In [230]:
first_floor_const.loc[138, 'sub_category'] = 'Brick Molding'

In [234]:
first_floor_const.loc[133, 'sub_category'] = 'Brick Molding'

In [238]:
first_floor_const.loc[135, 'sub_category'] = 'Brick Molding'

In [241]:
first_floor_const.loc[82, 'sub_category'] = 'Brick Molding'

In [243]:
first_floor_const.loc[83, 'sub_category'] = 'Brick Molding'

In [244]:
first_floor_const.loc[90, 'sub_category'] = 'Brick Molding'

In [247]:
first_floor_const.loc[91, 'sub_category'] = 'Brick Molding'

In [248]:
first_floor_const.loc[93, 'sub_category'] = 'Brick Molding'

In [252]:
first_floor_const.loc[94, 'sub_category'] = 'Brick Molding'

In [253]:
first_floor_const.loc[87, 'sub_category'] = 'Brick Molding'

In [254]:
first_floor_const.loc[92, 'sub_category'] = 'Brick Molding'

In [258]:
first_floor_const.loc[97, 'sub_category'] = 'Brick Molding'

In [259]:
first_floor_const.loc[100, 'sub_category'] = 'Brick Molding'

In [265]:
first_floor_const.drop(columns='sub-category', inplace=True)

In [280]:
print(first_floor_const.to_string())

                                     item  quantity  unit_cost  total_cost       date   sub_category   category  exchange_rate
0                             1 by 2 wood        25      100.0      2500.0 2024-01-01   Construction  1st Floor          67.50
1                             Wooden Pake        15       35.0       500.0 2024-01-01   Construction  1st Floor          67.50
2                      3 Inches Nale(kg)          2      100.0       200.0 2024-01-01   Construction  1st Floor          67.50
3             2 and half Inches Nale(kg)          2      100.0       200.0 2024-01-01   Construction  1st Floor          67.50
4               Materials Transportation          1      500.0       500.0 2024-01-01   Construction  1st Floor          67.50
5              Floor Plan Copy/Laminating         1      550.0       550.0 2024-01-02   Construction  1st Floor          67.50
6                     50m Water Hose/Pipe         1     1500.0      1500.0 2024-01-06   Construction  1st Floor          67.50
7                          Iron Rod(12mm)       100      540.0     54000.0 2024-01-11   Construction  1st Floor          67.50
8                           Iron Rod(6mm)       100      150.0     15000.0 2024-01-11   Construction  1st Floor          67.50
9                                  Cement       100      405.0     40500.0 2024-01-11   Construction  1st Floor          67.50
10                           Wheelbarrow          1     2700.0      2700.0 2024-01-11   Construction  1st Floor          67.50
11                   Binding Wire(Bundle)         2      425.0       850.0 2024-01-11   Construction  1st Floor          67.50
12              Materials Transportation          1     3800.0      3800.0 2024-01-11   Construction  1st Floor          67.50
13                        Sand(10 Wheels)         1     7500.0      7500.0 2024-01-11   Construction  1st Floor          67.50
14               Clean Pebble(10 Wheels)          1    12000.0     12000.0 2024-01-11   Construction  1st Floor          67.50
15            Sulaiman Juwara(Contractor)         1   100000.0    100000.0 2024-01-11   Construction  1st Floor          67.50
16                   Bubacar Fai Payment          1    12000.0     12000.0 2024-01-11   Construction  1st Floor          67.50
17            Asphalt Stones(double trip)         1    84000.0     84000.0 2024-01-27   Construction  1st Floor          71.20
18               Cement For Guard's Room          7      400.0      2800.0 2024-01-29   Construction  1st Floor          71.20
19                     Transport(Cements)         1      150.0       150.0 2024-01-29   Construction  1st Floor          71.20
20              Guard's Room Fl Concrete          1     3000.0      3000.0 2024-01-29   Construction  1st Floor          71.20
21                              Mattress          1     2300.0      2300.0 2024-02-05   Construction  1st Floor          71.20
22                    Mattress Transport          1      300.0       300.0 2024-02-05   Construction  1st Floor          71.20
23                         Machete Knife          1      200.0       200.0 2024-02-05   Construction  1st Floor          71.20
24                                   Lock         2      125.0       250.0 2024-02-05   Construction  1st Floor          71.20
25                  Kettle and Prayer Mat         1      275.0       275.0 2024-02-05   Construction  1st Floor          71.20
26                     Chain For Door(1m)         1      300.0       300.0 2024-02-05   Construction  1st Floor          71.20
27                        Slide Bolt Lock         1       60.0        60.0 2024-02-05   Construction  1st Floor          71.20
28               Flashlight with Battery          1       90.0        90.0 2024-02-05   Construction  1st Floor          71.20
29                   Carpenter for Locks          1      200.0       200.0 2024-02-05   Construction  1st Floor          71.20
30               Borehole Reinstallation          1      800.0       800.0 2024-02-13   Construction  1st Floor          71.20
31                  Guard Room Door locks         1      125.0       125.0 2024-02-13   Construction  1st Floor          71.20
32                             Carpenter          1      200.0       200.0 2024-02-13   Construction  1st Floor          71.20
33                               Tap Head         1      350.0       350.0 2024-02-13   Construction  1st Floor          71.20
34                    Generator Transport         1      600.0       600.0 2024-02-14   Construction  1st Floor          71.20
35                           1 by 12 Wood         8      650.0      5200.0 2024-02-20   Construction  1st Floor          71.20
36                1 by 12 Wood Transport          1      700.0       700.0 2024-02-20   Construction  1st Floor          71.20
37                             Generator          1    11000.0     11000.0 2024-02-20   Construction  1st Floor          71.20
38                   Generator Transport          1      600.0       600.0 2024-02-20   Construction  1st Floor          71.20
39                 Gas for the Generator          1      400.0       400.0 2024-02-20   Construction  1st Floor          71.20
40                            Momo Waggeh         1      500.0       500.0 2024-02-20   Construction  1st Floor          71.20
41             Rice(50kg) for Momo Waggeh         1     2000.0      2000.0 2024-02-24   Construction  1st Floor          71.20
42                        Sand(10 Wheels)         1     7500.0      7500.0 2024-03-01   Construction  1st Floor          71.20
43                                Cement        100      395.0     39500.0 2024-03-05   Construction  1st Floor          71.20
44                      Cement Transport          1     2000.0      2000.0 2024-03-05   Construction  1st Floor          71.20
45                            1 by 2 Wood        60      100.0      6000.0 2024-03-05   Construction  1st Floor          71.20
46                         Plywood(12mm)         10     1550.0     15500.0 2024-03-05   Construction  1st Floor          71.20
47                Splitting 12mm plywood         10       75.0       750.0 2024-03-05   Construction  1st Floor          71.20
48                12mm plywood Transport          1      700.0       700.0 2024-03-05   Construction  1st Floor          71.20
49            Momo Waggeh Salary (March)          1     4000.0      4000.0 2024-03-05   Construction  1st Floor          71.20
50                               Nail(kg)         9      100.0       900.0 2024-03-05   Construction  1st Floor          71.20
51                   Binding Wire(Bundle)         2      475.0       950.0 2024-03-12   Construction  1st Floor          71.20
52                       PS 10mm Iron Rod       100      340.0     34000.0 2024-03-12   Construction  1st Floor          71.20
53             Binding Wire+IronRod Trans         1      800.0       800.0 2024-03-12   Construction  1st Floor          71.20
54                   Workers Ramadan Gift         1      400.0       400.0 2024-03-12   Construction  1st Floor          71.20
55                          Iron Rod(6mm)        25      150.0      3750.0 2024-03-13   Construction  1st Floor          71.20
56                         6mm Transport          1      400.0       400.0 2024-03-13   Construction  1st Floor          71.20
57                           Gas + Nails          1      500.0       500.0 2024-03-13   Construction  1st Floor          71.20
58                        Sand(10 Wheels)         1     7500.0      7500.0 2024-03-23   Construction  1st Floor          71.20
59                            BCF Ramadan         1     2000.0      2000.0 2024-03-24   Construction  1st Floor          71.20
60                                 Cement        50      390.0     19500.0 2024-03-25   Construction  1st Floor          71.20
61                      Cement Transport         50       20.0      1000.0 2024-03-25   Construction  1st Floor          71.20
62                 Gas for the Generator          1      300.0       300.0 2024-03-27   Construction  1st Floor          71.20
63                         Iron Rod(12mm)        90      510.0     45900.0 2024-03-29   Construction  1st Floor          71.20
64                         Iron Rod(10mm)       100      325.0     32500.0 2024-03-29   Construction  1st Floor          71.20
65                        PS 6mm Iron Rod        85      135.0     11400.0 2024-03-29   Construction  1st Floor          71.20
66                   Binding Wire(Bundle)         3      400.0      1200.0 2024-03-29   Construction  1st Floor          71.20
67          Iron Rod + Binding Wire Trans         1     2000.0      2000.0 2024-03-29   Construction  1st Floor          71.20
68                       Timber for Sappo        20      200.0      4000.0 2024-03-29   Construction  1st Floor          71.20
69                      Timber Transport          1      650.0       650.0 2024-03-29   Construction  1st Floor          71.20
70                        Sand(10 Wheels)         1     7500.0      7500.0 2024-03-29   Construction  1st Floor          71.20
71             Momo Waggeh Salary (April)         1     4000.0      4000.0 2024-04-04   Construction  1st Floor          71.20
72                            Nail(kg) 3"         5      100.0       500.0 2024-04-04   Construction  1st Floor          71.20
73                        Nail(kg) 2 1/2"         5      100.0       500.0 2024-04-04   Construction  1st Floor          71.20
74                          Timber 1 by 6        10      300.0      3000.0 2024-04-07   Construction  1st Floor          71.20
75               Timber 1 by 6 Transport          1      500.0       500.0 2024-04-07   Construction  1st Floor          71.20
76               Wheelbarrow Maintenance          2     1000.0      2000.0 2024-04-08   Construction  1st Floor          71.20
77           Momo Waggeh Salary(advanced)         1     4000.0      4000.0 2024-04-19   Construction  1st Floor          71.20
78         Moving Sand from the Yard(1st)         1      350.0       350.0 2024-04-23   Construction  1st Floor          71.20
79         Moving Sand from the Yard(2nd)         2      350.0       700.0 2024-04-23   Construction  1st Floor          71.20
80         Moving Sand from the Yard(3rd)         4      400.0      1600.0 2024-04-23   Construction  1st Floor          71.20
81         Moving Sand from the Yard(4th)         3      500.0      1500.0 2024-04-23   Construction  1st Floor          71.20
82                                 Cement        50      390.0     19500.0 2024-04-23  Brick Molding  1st Floor          71.20
83                      Cement Transport         50       20.0      1000.0 2024-04-23  Brick Molding  1st Floor          71.20
84                              Tape Head         1      350.0       350.0 2024-04-23   Construction  1st Floor          71.20
85                             Tape Cover         1      150.0       150.0 2024-04-23   Construction  1st Floor          71.20
86                    Lock for Tape Cover         1      100.0       100.0 2024-04-23   Construction  1st Floor          71.20
87                        Sand(10 Wheels)         1     7500.0      7500.0 2024-04-26  Brick Molding  1st Floor          71.20
88                 Gas for the Generator          1      375.0       375.0 2024-04-29   Construction  1st Floor          71.20
89      Generator Leaking Repair + Trans          1      700.0       700.0 2024-04-29   Construction  1st Floor          71.20
90                                 Cement        50      395.0     19750.0 2024-05-01  Brick Molding  1st Floor          71.20
91                      Cement Transport         50       20.0      1000.0 2024-05-01  Brick Molding  1st Floor          71.20
92                        Sand(10 Wheels)         1     7500.0      7500.0 2024-05-02  Brick Molding  1st Floor          71.20
93                                 Cement        50      380.0     19000.0 2024-05-04  Brick Molding  1st Floor          71.20
94                      Cement Transport         50       20.0      1000.0 2024-05-04  Brick Molding  1st Floor          71.20
95                 Generator Repair + Gas         1     1200.0      1200.0 2024-05-04   Construction  1st Floor          71.20
96                     Oil for Generator          1      150.0       150.0 2024-05-06   Construction  1st Floor          71.20
97                        Sand(10 Wheels)         1     7500.0      7500.0 2024-05-07  Brick Molding  1st Floor          71.20
98                 Gas for the Generator          1      350.0       350.0 2024-05-07   Construction  1st Floor          71.20
99                   Watering the Bricks          1      500.0       500.0 2024-05-10   Construction  1st Floor          71.20
100                       Bricks Molding       3708        6.0     22250.0 2024-05-18  Brick Molding  1st Floor          71.20
101                Gas for the Generator          1      400.0       400.0 2024-05-25   Construction  1st Floor          71.20
102                                Sadaqa         1     3000.0      3000.0 2024-05-26   Construction  1st Floor          71.20
103         Sulaiman Juwarra 2nd Payment          1    80000.0     80000.0 2024-05-27   Construction  1st Floor          71.20
104                        Iron Rod(12mm)       100      540.0     54000.0 2024-05-28   Construction  1st Floor          71.20
105                         Iron Rod(6mm)        25      150.0      3750.0 2024-05-28   Construction  1st Floor          71.20
106                                Cement        30      400.0     12000.0 2024-05-28   Construction  1st Floor          71.20
107              Cement + Rods Transport          1     1400.0      1400.0 2024-05-28   Construction  1st Floor          71.20
108              Clean Pebble(10 Wheels)          1    13500.0     13500.0 2024-05-28   Construction  1st Floor          71.20
109           Asphalt Stones(double trip)         1    95000.0     95000.0 2024-05-28   Construction  1st Floor          71.20
110                       Sand(10 Wheels)         1     7500.0      7500.0 2024-05-28   Construction  1st Floor          71.20
111          Bubacar Fai Advance Payment          6    12000.0     72000.0 2024-05-28   Construction  1st Floor          71.20
112                               Cement         50      400.0     20000.0 2024-05-30   Construction  1st Floor          71.20
113                     Cement Transport         50       30.0      1500.0 2024-05-30   Construction  1st Floor          71.20
114            Momo Waggeh Salary (June)          1     4000.0      4000.0 2024-06-03   Construction  1st Floor          71.20
115                                Cement       100      430.0     43000.0 2024-06-03   Construction  1st Floor          71.20
116                     Cement Transport        100       30.0      3000.0 2024-06-03   Construction  1st Floor          71.20
117                       Sand(10 Wheels)         1     7500.0      7500.0 2024-06-03   Construction  1st Floor          71.20
118                Gas for the Generator          1      950.0       950.0 2024-06-04   Construction  1st Floor          71.20
119                       Sand(10 Wheels)         1     7500.0      7500.0 2024-06-10   Construction  1st Floor          71.20
120                                Cement        62      415.0     25730.0 2024-06-11   Construction  1st Floor          71.20
121                     Cement Transport         62       30.0      1860.0 2024-06-11   Construction  1st Floor          71.20
122                              Nail(kg)         4      100.0       400.0 2024-06-14   Construction  1st Floor          71.20
123             Momo Waggeh Salary (July)         1     4000.0      4000.0 2024-07-05   Construction  1st Floor          71.20
124                       Soft Plywood 6m         1      850.0       850.0 2024-07-04   Construction  1st Floor          71.20
125                              Nail(kg)         2      100.0       200.0 2024-07-04   Construction  1st Floor          71.20
126                  Binding Wire(Bundle)         1      500.0       500.0 2024-07-04   Construction  1st Floor          71.20
127             Plywood + Nail Transport          1      200.0       200.0 2024-07-04   Construction  1st Floor          71.20
128                         1 by 6 Timber         3      350.0      1050.0 2024-07-09   Construction  1st Floor          71.20
129                           1 by 2 Wood         2      100.0       200.0 2024-07-09   Construction  1st Floor          71.20
130                            Cardboard          1      350.0       350.0 2024-07-09   Construction  1st Floor          71.20
131                 1by6 & 1x2 Transport          1      300.0       300.0 2024-07-09   Construction  1st Floor          71.20
132                Gas for the Generator          1      300.0       300.0 2024-07-09   Construction  1st Floor          71.20
133                       Sand(10 Wheels)         1     7500.0      7500.0 2024-07-11  Brick Molding  1st Floor          71.20
134             Momo Waggeh Salary (Aug)          1     4000.0      4000.0 2024-08-05   Construction  1st Floor          71.20
135                       Bricks Molding          1     7140.0      7140.0 2024-08-04  Brick Molding  1st Floor          71.20
136                                Cement        25      400.0     10000.0 2024-09-04   Construction  1st Floor          71.20
137                     Cement Transport         25       20.0       500.0 2024-09-04   Construction  1st Floor          71.20
138          Momo Waggeh arranging Bricks         1      500.0       500.0 2024-09-04  Brick Molding  1st Floor          71.20
139            Momo Waggeh Salary (Sept)          1     4000.0      4000.0 2024-09-04   Construction  1st Floor          71.20
140                                Cement        25      400.0     10000.0 2024-09-09   Construction  1st Floor          71.20
141                     Cement Transport         25       20.0       500.0 2024-09-09   Construction  1st Floor          71.20
142                Gas for the Generator          1      300.0       300.0 2024-09-09   Construction  1st Floor          71.20
143                                Zakaat         1     4000.0      4000.0 2024-09-14   Construction  1st Floor          71.20
144           Sulaiman Juwara 3rd Payment         1    80000.0     80000.0 2024-09-18   Construction  1st Floor          71.20
145                               Cement         50      400.0     20000.0 2024-09-18   Construction  1st Floor          71.20
146                  Binding Wire(Bundle)         2      500.0      1000.0 2024-09-18   Construction  1st Floor          71.20
147                     Cement Transport         50       20.0      1000.0 2024-09-18   Construction  1st Floor          71.20
148                        Iron Rod(10mm)       120      340.0     40800.0 2024-09-19   Construction  1st Floor          71.20
149                         Iron Rod(6mm)        80      150.0     12000.0 2024-09-19   Construction  1st Floor          71.20
150                    Iron Rod Transport         1     1200.0      1200.0 2024-09-19   Construction  1st Floor          71.20
151              Asphalt Stones(10 wheel)         1    46000.0     46000.0 2024-09-19   Construction  1st Floor          71.20
152                       Sand(10 Wheels)         1     7500.0      7500.0 2024-09-20   Construction  1st Floor          71.20
153                      Generator Repair         1      900.0       900.0 2024-09-28   Construction  1st Floor          71.20
154               Momo Waggeh Salary(Oct)         1     4000.0      4000.0 2024-09-30   Construction  1st Floor          71.20
155                              Nail(kg)         2      100.0       200.0 2024-09-30   Construction  1st Floor          71.20

In [279]:
first_floor_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 342 entries, 0 to 341
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           342 non-null    str
 1   quantity       342 non-null    int64
 2   unit_cost      342 non-null    float64
 3   total_cost     342 non-null    float64
 4   date           342 non-null    datetime64[us]
 5   sub_category   342 non-null    str
 6   category       342 non-null    str
 7   exchange_rate  342 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 21.5 KB

In [274]:
first_floor_const['date'] = pd.to_datetime(first_floor_const['date'])

In [277]:
first_floor_const.head()

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,1 by 2 wood,25,100.0,2500.0,2024-01-01,Construction,1st Floor,67.5
1,Wooden Pake,15,35.0,500.0,2024-01-01,Construction,1st Floor,67.5
2,3 Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.5
3,2 and half Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.5
4,Materials Transportation,1,500.0,500.0,2024-01-01,Construction,1st Floor,67.5

In [2]:
first_floor_const.to_csv('ParadiseView/out/firstFloor_const.csv', index=False)

NameError: name 'first_floor_const' is not defined

In [6]:
first_floor_const = pd.read_csv('ParadiseView/out/firstFloor_const.csv')

In [52]:
print(first_floor_const.to_string())

                                    item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                            1 by 2 wood        25      100.0      2500.0  2024-01-01     Construction  1st Floor          67.50
1                            Wooden Pake        15       35.0       500.0  2024-01-01     Construction  1st Floor          67.50
2                     3 Inches Nale(kg)          2      100.0       200.0  2024-01-01     Construction  1st Floor          67.50
3            2 and half Inches Nale(kg)          2      100.0       200.0  2024-01-01     Construction  1st Floor          67.50
4              Materials Transportation          1      500.0       500.0  2024-01-01     Construction  1st Floor          67.50
5             Floor Plan Copy/Laminating         1      550.0       550.0  2024-01-02     Construction  1st Floor          67.50
6                    50m Water Hose/Pipe         1     1500.0      1500.0  2024-01-06     Construction  1st Floor          67.50
7                         Iron Rod(12mm)       100      540.0     54000.0  2024-01-11     Construction  1st Floor          67.50
8                          Iron Rod(6mm)       100      150.0     15000.0  2024-01-11     Construction  1st Floor          67.50
9                                 Cement       100      405.0     40500.0  2024-01-11     Construction  1st Floor          67.50
10                          Wheelbarrow          1     2700.0      2700.0  2024-01-11     Construction  1st Floor          67.50
11                  Binding Wire(Bundle)         2      425.0       850.0  2024-01-11     Construction  1st Floor          67.50
12             Materials Transportation          1     3800.0      3800.0  2024-01-11     Construction  1st Floor          67.50
13                       Sand (10 Wheel)         1     7500.0      7500.0  2024-01-11     Construction  1st Floor          67.50
14              Clean Pebble(10 Wheels)          1    12000.0     12000.0  2024-01-11     Construction  1st Floor          67.50
15           Sulaiman Juwara(Contractor)         1   100000.0    100000.0  2024-01-11     Construction  1st Floor          67.50
16                  Bubacar Fai Payment          1    12000.0     12000.0  2024-01-11     Construction  1st Floor          67.50
17           Asphalt Stones(double trip)         1    84000.0     84000.0  2024-01-27     Construction  1st Floor          71.20
18              Cement For Guard's Room          7      400.0      2800.0  2024-01-29     Construction  1st Floor          71.20
19                    Transport(Cements)         1      150.0       150.0  2024-01-29     Construction  1st Floor          71.20
20             Guard's Room Fl Concrete          1     3000.0      3000.0  2024-01-29     Construction  1st Floor          71.20
21                             Mattress          1     2300.0      2300.0  2024-02-05     Construction  1st Floor          71.20
22                   Mattress Transport          1      300.0       300.0  2024-02-05     Construction  1st Floor          71.20
23                        Machete Knife          1      200.0       200.0  2024-02-05     Construction  1st Floor          71.20
24                                  Lock         2      125.0       250.0  2024-02-05     Construction  1st Floor          71.20
25                 Kettle and Prayer Mat         1      275.0       275.0  2024-02-05     Construction  1st Floor          71.20
26                    Chain For Door(1m)         1      300.0       300.0  2024-02-05     Construction  1st Floor          71.20
27                       Slide Bolt Lock         1       60.0        60.0  2024-02-05     Construction  1st Floor          71.20
28              Flashlight with Battery          1       90.0        90.0  2024-02-05     Construction  1st Floor          71.20
29                  Carpenter for Locks          1      200.0       200.0  2024-02-05     Construction  1st Floor          71.20
30              Borehole Reinstallation          1      800.0       800.0  2024-02-13     Construction  1st Floor          71.20
31                 Guard Room Door locks         1      125.0       125.0  2024-02-13     Construction  1st Floor          71.20
32                            Carpenter          1      200.0       200.0  2024-02-13     Construction  1st Floor          71.20
33                              Tap Head         1      350.0       350.0  2024-02-13     Construction  1st Floor          71.20
34                   Generator Transport         1      600.0       600.0  2024-02-14     Construction  1st Floor          71.20
35                          1 by 12 Wood         8      650.0      5200.0  2024-02-20     Construction  1st Floor          71.20
36               1 by 12 Wood Transport          1      700.0       700.0  2024-02-20     Construction  1st Floor          71.20
37                            Generator          1    11000.0     11000.0  2024-02-20     Construction  1st Floor          71.20
38                  Generator Transport          1      600.0       600.0  2024-02-20     Construction  1st Floor          71.20
39                Gas for the Generator          1      400.0       400.0  2024-02-20     Construction  1st Floor          71.20
40                           Momo Waggeh         1      500.0       500.0  2024-02-20     Construction  1st Floor          71.20
41            Rice(50kg) for Momo Waggeh         1     2000.0      2000.0  2024-02-24     Construction  1st Floor          71.20
42                       Sand (10 Wheel)         1     7500.0      7500.0  2024-03-01     Construction  1st Floor          71.20
43                               Cement        100      395.0     39500.0  2024-03-05     Construction  1st Floor          71.20
44                     Cement Transport          1     2000.0      2000.0  2024-03-05     Construction  1st Floor          71.20
45                           1 by 2 Wood        60      100.0      6000.0  2024-03-05     Construction  1st Floor          71.20
46                        Plywood(12mm)         10     1550.0     15500.0  2024-03-05     Construction  1st Floor          71.20
47               Splitting 12mm plywood         10       75.0       750.0  2024-03-05     Construction  1st Floor          71.20
48               12mm plywood Transport          1      700.0       700.0  2024-03-05     Construction  1st Floor          71.20
49           Momo Waggeh Salary (March)          1     4000.0      4000.0  2024-03-05     Construction  1st Floor          71.20
50                              Nail(kg)         9      100.0       900.0  2024-03-05     Construction  1st Floor          71.20
51                  Binding Wire(Bundle)         2      475.0       950.0  2024-03-12     Construction  1st Floor          71.20
52                      PS 10mm Iron Rod       100      340.0     34000.0  2024-03-12     Construction  1st Floor          71.20
53            Binding Wire+IronRod Trans         1      800.0       800.0  2024-03-12     Construction  1st Floor          71.20
54                  Workers Ramadan Gift         1      400.0       400.0  2024-03-12     Construction  1st Floor          71.20
55                         Iron Rod(6mm)        25      150.0      3750.0  2024-03-13     Construction  1st Floor          71.20
56                        6mm Transport          1      400.0       400.0  2024-03-13     Construction  1st Floor          71.20
57                          Gas + Nails          1      500.0       500.0  2024-03-13     Construction  1st Floor          71.20
58                       Sand (10 Wheel)         1     7500.0      7500.0  2024-03-23     Construction  1st Floor          71.20
59                           BCF Ramadan         1     2000.0      2000.0  2024-03-24     Construction  1st Floor          71.20
60                                Cement        50      390.0     19500.0  2024-03-25     Construction  1st Floor          71.20
61                     Cement Transport         50       20.0      1000.0  2024-03-25     Construction  1st Floor          71.20
62                Gas for the Generator          1      300.0       300.0  2024-03-27     Construction  1st Floor          71.20
63                        Iron Rod(12mm)        90      510.0     45900.0  2024-03-29     Construction  1st Floor          71.20
64                        Iron Rod(10mm)       100      325.0     32500.0  2024-03-29     Construction  1st Floor          71.20
65                       PS 6mm Iron Rod        85      135.0     11400.0  2024-03-29     Construction  1st Floor          71.20
66                  Binding Wire(Bundle)         3      400.0      1200.0  2024-03-29     Construction  1st Floor          71.20
67         Iron Rod + Binding Wire Trans         1     2000.0      2000.0  2024-03-29     Construction  1st Floor          71.20
68                      Timber for Sappo        20      200.0      4000.0  2024-03-29     Construction  1st Floor          71.20
69                     Timber Transport          1      650.0       650.0  2024-03-29     Construction  1st Floor          71.20
70                       Sand (10 Wheel)         1     7500.0      7500.0  2024-03-29     Construction  1st Floor          71.20
71            Momo Waggeh Salary (April)         1     4000.0      4000.0  2024-04-04     Construction  1st Floor          71.20
72                           Nail(kg) 3"         5      100.0       500.0  2024-04-04     Construction  1st Floor          71.20
73                       Nail(kg) 2 1/2"         5      100.0       500.0  2024-04-04     Construction  1st Floor          71.20
74                         Timber 1 by 6        10      300.0      3000.0  2024-04-07     Construction  1st Floor          71.20
75              Timber 1 by 6 Transport          1      500.0       500.0  2024-04-07     Construction  1st Floor          71.20
76              Wheelbarrow Maintenance          2     1000.0      2000.0  2024-04-08     Construction  1st Floor          71.20
77          Momo Waggeh Salary(advanced)         1     4000.0      4000.0  2024-04-19     Construction  1st Floor          71.20
78        Moving Sand from the Yard(1st)         1      350.0       350.0  2024-04-23     Construction  1st Floor          71.20
79        Moving Sand from the Yard(2nd)         2      350.0       700.0  2024-04-23     Construction  1st Floor          71.20
80        Moving Sand from the Yard(3rd)         4      400.0      1600.0  2024-04-23     Construction  1st Floor          71.20
81        Moving Sand from the Yard(4th)         3      500.0      1500.0  2024-04-23     Construction  1st Floor          71.20
82                                Cement        50      390.0     19500.0  2024-04-23    Brick Molding  1st Floor          71.20
83                     Cement Transport         50       20.0      1000.0  2024-04-23    Brick Molding  1st Floor          71.20
84                             Tape Head         1      350.0       350.0  2024-04-23     Construction  1st Floor          71.20
85                            Tape Cover         1      150.0       150.0  2024-04-23     Construction  1st Floor          71.20
86                   Lock for Tape Cover         1      100.0       100.0  2024-04-23     Construction  1st Floor          71.20
87                       Sand (10 Wheel)         1     7500.0      7500.0  2024-04-26    Brick Molding  1st Floor          71.20
88                Gas for the Generator          1      375.0       375.0  2024-04-29     Construction  1st Floor          71.20
89     Generator Leaking Repair + Trans          1      700.0       700.0  2024-04-29     Construction  1st Floor          71.20
90                                Cement        50      395.0     19750.0  2024-05-01    Brick Molding  1st Floor          71.20
91                     Cement Transport         50       20.0      1000.0  2024-05-01    Brick Molding  1st Floor          71.20
92                       Sand (10 Wheel)         1     7500.0      7500.0  2024-05-02    Brick Molding  1st Floor          71.20
93                                Cement        50      380.0     19000.0  2024-05-04    Brick Molding  1st Floor          71.20
94                     Cement Transport         50       20.0      1000.0  2024-05-04    Brick Molding  1st Floor          71.20
95                Generator Repair + Gas         1     1200.0      1200.0  2024-05-04     Construction  1st Floor          71.20
96                    Oil for Generator          1      150.0       150.0  2024-05-06     Construction  1st Floor          71.20
97                       Sand (10 Wheel)         1     7500.0      7500.0  2024-05-07    Brick Molding  1st Floor          71.20
98                Gas for the Generator          1      350.0       350.0  2024-05-07     Construction  1st Floor          71.20
99                  Watering the Bricks          1      500.0       500.0  2024-05-10     Construction  1st Floor          71.20
100                      Bricks Molding       3708        6.0     22250.0  2024-05-18    Brick Molding  1st Floor          71.20
101               Gas for the Generator          1      400.0       400.0  2024-05-25     Construction  1st Floor          71.20
102                               Sadaqa         1     3000.0      3000.0  2024-05-26     Construction  1st Floor          71.20
103        Sulaiman Juwarra 2nd Payment          1    80000.0     80000.0  2024-05-27     Construction  1st Floor          71.20
104                       Iron Rod(12mm)       100      540.0     54000.0  2024-05-28     Construction  1st Floor          71.20
105                        Iron Rod(6mm)        25      150.0      3750.0  2024-05-28     Construction  1st Floor          71.20
106                               Cement        30      400.0     12000.0  2024-05-28     Construction  1st Floor          71.20
107             Cement + Rods Transport          1     1400.0      1400.0  2024-05-28     Construction  1st Floor          71.20
108             Clean Pebble(10 Wheels)          1    13500.0     13500.0  2024-05-28     Construction  1st Floor          71.20
109          Asphalt Stones(double trip)         1    95000.0     95000.0  2024-05-28     Construction  1st Floor          71.20
110                      Sand(10 Wheels)         1     7500.0      7500.0  2024-05-28     Construction  1st Floor          71.20
111         Bubacar Fai Advance Payment          6    12000.0     72000.0  2024-05-28     Construction  1st Floor          71.20
112                              Cement         50      400.0     20000.0  2024-05-30     Construction  1st Floor          71.20
113                    Cement Transport         50       30.0      1500.0  2024-05-30     Construction  1st Floor          71.20
114           Momo Waggeh Salary (June)          1     4000.0      4000.0  2024-06-03     Construction  1st Floor          71.20
115                               Cement       100      430.0     43000.0  2024-06-03     Construction  1st Floor          71.20
116                    Cement Transport        100       30.0      3000.0  2024-06-03     Construction  1st Floor          71.20
117                      Sand (10 Wheel)         1     7500.0      7500.0  2024-06-03     Construction  1st Floor          71.20
118               Gas for the Generator          1      950.0       950.0  2024-06-04     Construction  1st Floor          71.20
119                      Sand (10 Wheel)         1     7500.0      7500.0  2024-06-10     Construction  1st Floor          71.20
120                               Cement        62      415.0     25730.0  2024-06-11     Construction  1st Floor          71.20
121                    Cement Transport         62       30.0      1860.0  2024-06-11     Construction  1st Floor          71.20
122                             Nail(kg)         4      100.0       400.0  2024-06-14     Construction  1st Floor          71.20
123            Momo Waggeh Salary (July)         1     4000.0      4000.0  2024-07-05     Construction  1st Floor          71.20
124                      Soft Plywood 6m         1      850.0       850.0  2024-07-04     Construction  1st Floor          71.20
125                             Nail(kg)         2      100.0       200.0  2024-07-04     Construction  1st Floor          71.20
126                 Binding Wire(Bundle)         1      500.0       500.0  2024-07-04     Construction  1st Floor          71.20
127            Plywood + Nail Transport          1      200.0       200.0  2024-07-04     Construction  1st Floor          71.20
128                        1 by 6 Timber         3      350.0      1050.0  2024-07-09     Construction  1st Floor          71.20
129                          1 by 2 Wood         2      100.0       200.0  2024-07-09     Construction  1st Floor          71.20
130                           Cardboard          1      350.0       350.0  2024-07-09     Construction  1st Floor          71.20
131                1by6 & 1x2 Transport          1      300.0       300.0  2024-07-09     Construction  1st Floor          71.20
132               Gas for the Generator          1      300.0       300.0  2024-07-09     Construction  1st Floor          71.20
133                      Sand(10 Wheels)         1     7500.0      7500.0  2024-07-11    Brick Molding  1st Floor          71.20
134            Momo Waggeh Salary (Aug)          1     4000.0      4000.0  2024-08-05     Construction  1st Floor          71.20
135                      Bricks Molding          1     7140.0      7140.0  2024-08-04    Brick Molding  1st Floor          71.20
136                               Cement        25      400.0     10000.0  2024-09-04     Construction  1st Floor          71.20
137                    Cement Transport         25       20.0       500.0  2024-09-04     Construction  1st Floor          71.20
138         Momo Waggeh arranging Bricks         1      500.0       500.0  2024-09-04    Brick Molding  1st Floor          71.20
139           Momo Waggeh Salary (Sept)          1     4000.0      4000.0  2024-09-04     Construction  1st Floor          71.20
140                               Cement        25      400.0     10000.0  2024-09-09     Construction  1st Floor          71.20
141                    Cement Transport         25       20.0       500.0  2024-09-09     Construction  1st Floor          71.20
142               Gas for the Generator          1      300.0       300.0  2024-09-09     Construction  1st Floor          71.20
143                               Zakaat         1     4000.0      4000.0  2024-09-14     Construction  1st Floor          71.20
144          Sulaiman Juwara 3rd Payment         1    80000.0     80000.0  2024-09-18     Construction  1st Floor          71.20
145                              Cement         50      400.0     20000.0  2024-09-18     Construction  1st Floor          71.20
146                 Binding Wire(Bundle)         2      500.0      1000.0  2024-09-18     Construction  1st Floor          71.20
147                    Cement Transport         50       20.0      1000.0  2024-09-18     Construction  1st Floor          71.20
148                       Iron Rod(10mm)       120      340.0     40800.0  2024-09-19     Construction  1st Floor          71.20
149                        Iron Rod(6mm)        80      150.0     12000.0  2024-09-19     Construction  1st Floor          71.20
150                   Iron Rod Transport         1     1200.0      1200.0  2024-09-19     Construction  1st Floor          71.20
151             Asphalt Stones(10 wheel)         1    46000.0     46000.0  2024-09-19     Construction  1st Floor          71.20
152                      Sand (10 Wheel)         1     7500.0      7500.0  2024-09-20     Construction  1st Floor          71.20
153                     Generator Repair         1      900.0       900.0  2024-09-28     Construction  1st Floor          71.20

In [9]:
first_floor_const.iloc[258:338, 5:6] = 'Roof Concreting'

In [10]:
first_floor_const.at[263, 'sub_category'] = 'Construction'

In [13]:
first_floor_const.at[338, 'sub_category'] = 'Roof Concreting'

In [21]:
first_floor_const['item'] = first_floor_const['item'].str.replace('-', '', regex=True)

In [26]:
first_floor_const['item'] = first_floor_const['item'].str.replace('---Momo', 'Momo', regex=True)

In [32]:
first_floor_const.at[317, 'item'] = 'Momo Waggeh Putting Sand inside'

In [50]:
first_floor_const.at[285, 'item'] = '2nd Floor Architect Transport'

In [51]:
first_floor_const.at[302, 'item'] = 'Gas for Generator'

In [46]:
first_floor_const.iloc[[13, 42, 58, 87, 92, 117, 119, 152, 187, 236, 267, 295, 300, 301, 303, 309, 326, 332], 0:1] = 'Sand (10 Wheel)'

In [53]:
first_floor_const.to_csv('ParadiseView/out/firstFloor_const.csv', index=False)

In [54]:
pd.read_csv('ParadiseView/out/firstFloor_const.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 342 entries, 0 to 341
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           342 non-null    str
 1   quantity       342 non-null    int64
 2   unit_cost      342 non-null    float64
 3   total_cost     342 non-null    float64
 4   date           342 non-null    str
 5   sub_category   342 non-null    str
 6   category       342 non-null    str
 7   exchange_rate  342 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 21.5 KB