In [1]:
import pandas as pd
import numpy as np

In [2]:
secondfloor_brick = pd.read_csv('ParadiseView/out/df_secondfloor_bricks.csv')

In [3]:
secondfloor_const = pd.read_csv('ParadiseView/out/df_secondfloor_const.csv')

In [4]:
secondfloor_roof = pd.read_csv('ParadiseView/out/df_secondfloor_roof.csv')

In [5]:
print(secondfloor_brick.to_string())

                                 item  quantity  unit_cost  total_cost        date   sub_category   category  exchange_rate
0           Clearing Momo Haja's plot       1.0     3500.0      3500.0  2025-04-14  Brick Molding  2nd Floor           71.2
1   2nd Floor Plan Consultation(gas)        1.0      600.0       600.0  2025-04-15  Brick Molding  2nd Floor           71.2
2                             Cement       25.0      390.0      9750.0  2025-04-16  Brick Molding  2nd Floor           71.2
3                   Cement Transport       25.0       20.0       500.0  2025-04-16  Brick Molding  2nd Floor           71.2
4                       Sand(10Wheel)       1.0     8000.0      8000.0  2025-04-19  Brick Molding  2nd Floor           71.2
5                       Sand Wave Fee       1.0       80.0        80.0  2025-04-19  Brick Molding  2nd Floor           71.2
6                   Gas for Generator       1.0      400.0       400.0  2025-04-21  Brick Molding  2nd Floor           71.2
7                       Sand(10Wheel)       1.0     8000.0      8000.0  2025-04-22  Brick Molding  2nd Floor           71.2
8          Waggeh-putting sand inside       1.0     1300.0      1300.0  2025-05-04  Brick Molding  2nd Floor           71.2
9                       50 meter Hose       1.0     1600.0      1600.0  2025-04-19  Brick Molding  2nd Floor           71.2
10                            Cement      150.0      465.0     69750.0  2025-07-08  Brick Molding  2nd Floor           69.0
11                  Cement Transport      150.0       20.0      3000.0  2025-07-08  Brick Molding  2nd Floor           69.0
12                     Sand(10Wheel)        1.0     8000.0      8000.0  2025-07-08  Brick Molding  2nd Floor           69.0
13                     Sand(10Wheel)        1.0     8000.0      8000.0  2025-07-16  Brick Molding  2nd Floor           68.9
14                 Wheelbarrow Repair       1.0      400.0       400.0  2025-07-17  Brick Molding  2nd Floor           69.0
15                  Wheelbarrow Wheel       1.0      700.0       700.0  2025-07-17  Brick Molding  2nd Floor           68.9
16                               Lock       1.0      100.0       100.0  2025-07-17  Brick Molding  2nd Floor           69.0
17                     Sand(10Wheel)        2.0     8000.0     16000.0  2025-07-21  Brick Molding  2nd Floor           69.0
18                 Wheelbarrow Repair       1.0      150.0       150.0  2025-07-22  Brick Molding  2nd Floor           69.0
19                           Watering       1.0     2350.0      2350.0  2025-07-23  Brick Molding  2nd Floor           69.0
20                  Borehole Machine        1.0     3500.0      3500.0  2025-07-23  Brick Molding  2nd Floor           69.0
21                              Guard       1.0      500.0       500.0  2025-07-25  Brick Molding  2nd Floor           69.0
22                     Sand(10Wheel)        2.0     8000.0     16000.0  2025-07-26  Brick Molding  2nd Floor           69.0
23                            Cement       50.0      475.0     23750.0  2025-07-30  Brick Molding  2nd Floor           69.0
24                  Cement Transport       50.0       25.0      1250.0  2025-07-30  Brick Molding  2nd Floor           69.0
25              Brick Molding(200x25)    5000.0        7.0     35000.0  2025-08-05  Brick Molding  2nd Floor           69.0
26    Guard Transport during Bricking       1.0     1000.0      1000.0  2025-08-05  Brick Molding  2nd Floor           69.0
27               Watering & Transport       1.0     3000.0      3000.0  2025-08-25  Brick Molding  2nd Floor           69.0

In [6]:
print(secondfloor_const.to_string())

                                           item  quantity  unit_cost  total_cost        date  sub_category   category  exchange_rate
0                       Rope for Lifting Bricks         1      400.0       400.0  2025-08-28  Construction  2nd Floor           73.5
1                                 Iron Rod 12mm        70      550.0     38500.0  2025-08-30  Construction  2nd Floor           73.5
2                                  Iron Rod 6mm        40      150.0      6000.0  2025-08-30  Construction  2nd Floor           73.5
3                                   Wheelbarrow         1     2800.0      2800.0  2025-08-30  Construction  2nd Floor           73.5
4                            Binding Wire(Roll)         2      500.0      1000.0  2025-08-30  Construction  2nd Floor           73.5
5                            Materials Transpot         1     1000.0      1000.0  2025-08-30  Construction  2nd Floor           73.5
6                                        Cement        50      480.0     24000.0  2025-08-30  Construction  2nd Floor           73.5
7                              Cement Transport        50       20.0      1000.0  2025-08-30  Construction  2nd Floor           73.5
8              Contractor Momodou Njaye Payment         1    90000.0     90000.0  2025-08-30  Construction  2nd Floor           73.5
9                             Gas for Generator         1      530.0       530.0  2025-08-31  Construction  2nd Floor           73.5
10                             Generator Repair         1     1200.0      1200.0  2025-09-05  Construction  2nd Floor           73.5
11                                Sand(10Wheel)         1     8300.0      8300.0  2025-09-06  Construction  2nd Floor           73.5
12             Contractor Momodou Njaye Payment         1   100000.0    100000.0  2025-09-08  Construction  2nd Floor           73.5
13                                       Cement        50      480.0     24000.0  2025-09-10  Construction  2nd Floor           73.5
14                             Cement Transport        50       20.0      1000.0  2025-09-10  Construction  2nd Floor           73.5
15                                  1 by 2 wood        40      100.0      4000.0  2025-09-13  Construction  2nd Floor           73.5
16                           Splitting Plywoods         1      650.0       650.0  2025-09-13  Construction  2nd Floor           73.5
17                           Materials Transpot         1      600.0       600.0  2025-09-13  Construction  2nd Floor           73.5
18                                Nail(kg) 3 in         3      100.0       300.0  2025-09-13  Construction  2nd Floor           73.5
19                                Nail(kg) 3 in         4      100.0       400.0  2025-09-15  Construction  2nd Floor           73.5
20                                       Cement        50      480.0     24000.0  2025-09-16  Construction  2nd Floor           73.5
21                             Cement Transport        50       20.0      1000.0  2025-09-16  Construction  2nd Floor           73.5
22                      Asphalt Stone(19 cubic)         1    95000.0     95000.0  2025-09-17  Construction  2nd Floor           73.5
23                                Iron Rod 12mm        25      540.0     13500.0  2025-09-17  Construction  2nd Floor           73.5
24                                Iron Rod 10mm       280      330.0     92400.0  2025-09-17  Construction  2nd Floor           73.5
25                                 Iron Rod 6mm       125      140.0     17500.0  2025-09-17  Construction  2nd Floor           73.5
26                           Binding Wire(Roll)         3      400.0      1200.0  2025-09-17  Construction  2nd Floor           73.5
27                          Iron Rods Transport         1     3000.0      3000.0  2025-09-17  Construction  2nd Floor           73.5
28                                    Chain(2m)         1      700.0       700.0  2025-09-17  Construction  2nd Floor           73.5
29                                         Lock         1      250.0       250.0  2025-09-17  Construction  2nd Floor           73.5
30                                       1 by 6        10      400.0      4000.0  2025-09-17  Construction  2nd Floor           73.5
31                  1 by 6 & 12mm Rod Transport         1      600.0       600.0  2025-09-17  Construction  2nd Floor           73.5
32                                Nail(kg) 3 in         2      100.0       200.0  2025-09-17  Construction  2nd Floor           73.5
33                                Sand(10Wheel)         1     8300.0      8300.0  2025-09-17  Construction  2nd Floor           73.5
34             Contractor Momodou Njaye Payment         1   100000.0    100000.0  2025-09-21  Construction  2nd Floor           73.6
35                                       Bucket         3      100.0       300.0  2025-09-22  Construction  2nd Floor           73.6
36                           Binding Wire(Roll)         2      500.0      1000.0  2025-09-22  Construction  2nd Floor           73.6
37                                  1 by 2 wood        20      100.0      2000.0  2025-09-24  Construction  2nd Floor           73.6
38               Splitting Rest of the Plywoods         1     1125.0      1125.0  2025-09-24  Construction  2nd Floor           73.6
39                   Plywood & 1 by 2 Transport         1      800.0       800.0  2025-09-24  Construction  2nd Floor           73.6
40                                Nail(kg) 3 in         5      100.0       500.0  2025-09-29  Construction  2nd Floor           73.6
41                                Nail(kg) 2 in         2      100.0       200.0  2025-09-29  Construction  2nd Floor           73.6
42                                Nail(kg) 1 in         2      100.0       200.0  2025-09-29  Construction  2nd Floor           73.6
43                                       Cement        50      480.0     24000.0  2025-09-30  Construction  2nd Floor           73.6
44                             Cement Transport        50       20.0      1000.0  2025-09-30  Construction  2nd Floor           73.6
45                    Momo Waggeh's Sept Salary         1     4000.0      4000.0  2025-09-30  Construction  2nd Floor           73.6
46                            Gas for Generator         1      500.0       500.0  2025-10-01  Construction  2nd Floor           73.6
47             Njaye Extra- Transporting Bricks         1     5000.0      5000.0  2025-10-04  Construction  2nd Floor           73.6
48                            For Bubacarr Faye         1     5000.0      5000.0  2025-10-09  Construction  2nd Floor           73.6
49                                       Cement        50      480.0     24000.0  2025-10-11  Construction  2nd Floor           73.6
50                             Cement Transport        50       20.0      1000.0  2025-10-11  Construction  2nd Floor           73.6
51                            Gas for Generator         1      400.0       400.0  2025-10-13  Construction  2nd Floor           73.6
52                             Generator Repair         1     2700.0      2700.0  2025-10-14  Construction  2nd Floor           73.6
53                          Generator Transport         1      600.0       600.0  2025-10-14  Construction  2nd Floor           73.6
54                           Wheelbarrow Repair         1      800.0       800.0  2025-10-14  Construction  2nd Floor           73.6
55                                Sand(10Wheel)         1     8500.0      8500.0  2025-10-17  Construction  2nd Floor           73.6
56                           Binding Wire(Roll)         1      500.0       500.0  2025-10-17  Construction  2nd Floor           73.6
57                                Nail(kg) 3 in         3      100.0       300.0  2025-10-17  Construction  2nd Floor           73.6
58                            Gas for Generator         1      435.0       435.0  2025-10-19  Construction  2nd Floor           73.6
59                                Nail(kg) 3 in         7      100.0       700.0  2025-10-20  Construction  2nd Floor           73.6
60                                Nail(kg) 2 in         3      100.0       300.0  2025-10-20  Construction  2nd Floor           73.6
61                            Momo Waggeh's Bed         1     2000.0      2000.0  2025-10-20  Construction  2nd Floor           73.6
62             Contractor Momodou Njaye Payment         1    10000.0     10000.0  2025-10-20  Construction  2nd Floor           73.6
63                            Gas for Generator         1      440.0       440.0  2025-10-23  Construction  2nd Floor           73.6
64                           Wheelbarrow Repair         1     1500.0      1500.0  2025-10-23  Construction  2nd Floor           73.6
65                                       Cement        25      480.0     12000.0  2025-10-24  Construction  2nd Floor           73.6
66                             Cement Transport        25       20.0       500.0  2025-10-24  Construction  2nd Floor           73.6
67                           Pilar Mold Rental          3     2000.0      6000.0  2025-10-24  Construction  2nd Floor           73.6
68                                Tank Removal          1     5000.0      5000.0  2025-10-24  Construction  2nd Floor           73.6
69                            Gas for Generator         1      500.0       500.0  2025-10-26  Construction  2nd Floor           74.0
70                                       Cement        25      480.0     12000.0  2025-10-27  Construction  2nd Floor           74.0
71                             Cement Transport        25       20.0       500.0  2025-10-27  Construction  2nd Floor           74.0
72                                 Plywood 12mm         4     1725.0      6900.0  2025-10-27  Construction  2nd Floor           74.0
73                                   Cardboard          3      350.0      1050.0  2025-10-27  Construction  2nd Floor           74.0
74                                  1 by 2 wood         4      100.0       400.0  2025-10-27  Construction  2nd Floor           74.0
75                Plywood & cardboard Transport         1      400.0       400.0  2025-10-27  Construction  2nd Floor           74.0
76                             Generator Repair         1     1650.0      1650.0  2025-10-27  Construction  2nd Floor           74.0
77                           six Pilar Iron Man         1     2500.0      2500.0  2025-10-28  Construction  2nd Floor           74.0
78                        Momo Waggeh's Salary          1     4000.0      4000.0  2025-10-31  Construction  2nd Floor           74.0
79   Workers Bathroom Plumbing Materials +Trans         1     5975.0      5975.0  2025-11-01  Construction  2nd Floor           74.0
80                            Four Pillars Mold         3     1000.0      3000.0  2025-11-01  Construction  2nd Floor           74.0
81                 Four Pillars Mold Transport          2      500.0      1000.0  2025-11-01  Construction  2nd Floor           74.0
82                                  1 by 2 wood         5      100.0       500.0  2025-11-03  Construction  2nd Floor           74.0
83                                Nail(kg) 3 in         1      100.0       100.0  2025-11-03  Construction  2nd Floor           74.0
84                                  1 by 6 Wood         2      400.0       800.0  2025-11-04  Construction  2nd Floor           74.0
85                                Nail(kg) 3 in         3      100.0       300.0  2025-11-04  Construction  2nd Floor           74.0
86                  Bathroom Plumbing Materials         1      500.0       500.0  2025-11-04  Construction  2nd Floor           74.0
87                                Borehole Pile         1     2050.0      2050.0  2025-11-04  Construction  2nd Floor           74.0
88                                       Cement        25      480.0     12000.0  2025-11-04  Construction  2nd Floor           74.0
89                             Cement Transport        25       20.0       500.0  2025-11-04  Construction  2nd Floor           74.0
90                          Joins For Plumbing          2      150.0       300.0  2025-11-04  Construction  2nd Floor           74.0
91                      Tube for Plumbing(15mm)        15       50.0       750.0  2025-11-04  Construction  2nd Floor           74.0
92                                Soft Plywood          1     1000.0      1000.0  2025-11-04  Construction  2nd Floor           74.0
93                           Plywood Transport          1      400.0       400.0  2025-11-04  Construction  2nd Floor           74.0
94                                 Plumber Fees         1     4500.0      4500.0  2025-11-05  Construction  2nd Floor           74.0
95                                    Wave Fees         1      120.0       120.0  2025-11-05  Construction  2nd Floor           74.0
96                                    Scarfing          3      450.0      1350.0  2025-11-06  Construction  2nd Floor           74.0
97                          Scarfing Transport          1      400.0       400.0  2025-11-06  Construction  2nd Floor           74.0
98                                  1 by 2 wood         5      100.0       500.0  2025-11-07  Construction  2nd Floor           74.0
99                       1 by 2 wood Transport          1      300.0       300.0  2025-11-07  Construction  2nd Floor           74.0
100    Bathroom Manual and plastering the floor         1     2500.0      2500.0  2025-11-07  Construction  2nd Floor           74.0
101                          Pilar Mold Rental          4     2000.0      8000.0  2025-11-11  Construction  2nd Floor           74.0
102                          Balcony Extension          1     2000.0      2000.0  2025-11-14  Construction  2nd Floor           74.0
103            Contractor Momodou Njaye Payment         1    10000.0     10000.0  2025-11-14  Construction  2nd Floor           74.0
104                              Bathroom Door          1     2600.0      2600.0  2025-11-15  Construction  2nd Floor           74.0
105                                 Ali Salary          1     5500.0      5500.0  2025-11-15  Construction  2nd Floor           74.0
106                        Scarfing + Acro Jack         1     2994.0      2994.0  2025-11-17  Construction  2nd Floor           74.0
107             Scarfing + Acro Jack Transport          1     1000.0      1000.0  2025-11-17  Construction  2nd Floor           74.0
108                            Miss Calculation         1      500.0       500.0  2025-12-17  Construction  2nd Floor           74.0

In [7]:
print(secondfloor_roof.to_string())

                                     item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                                1/2 wood     100.0      100.0     10000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
1                     1/2 Wood Transport        1.0     1000.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
2                  Concrete Nail 2 1/2 in       5.0      200.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
3                      Concrete Nail 2 in      45.0       30.0      1350.0  2025-12-05  Roof Concreting  2nd Floor          74.25
4                                1/2 Wood      35.0      100.0      3500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
5                                1/6 Wood       2.0      350.0       700.0  2025-12-06  Roof Concreting  2nd Floor          74.25
6                         Wood Transport        1.0      500.0       500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
7                 Carpenter Sana Payment        1.0    15000.0     15000.0  2025-12-06  Roof Concreting  2nd Floor          74.25
8                         2/3 Wood Rental     350.0        5.0     52500.0  2025-12-13  Roof Concreting  2nd Floor          74.25
9                               Nail(pkg)      17.0      100.0      1700.0  2025-12-13  Roof Concreting  2nd Floor          74.25
10                   Materials Transport        4.0     2500.0     10000.0  2025-12-13  Roof Concreting  2nd Floor          74.25
11                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
12                        Arcojack Rental     400.0        2.5     27000.0  2025-12-15  Roof Concreting  2nd Floor          74.25
13                      Generator Repair        1.0      600.0       600.0  2025-12-17  Roof Concreting  2nd Floor          74.25
14                   Generator Transport        2.0      300.0       600.0  2025-12-17  Roof Concreting  2nd Floor          74.25
15                     Gas for Generator        1.0      500.0       500.0  2025-12-17  Roof Concreting  2nd Floor          74.25
16                        Plywood Rental       65.0       20.0     32500.0  2025-12-18  Roof Concreting  2nd Floor          74.25
17                               Nail(kg)       8.0      100.0       800.0  2025-12-20  Roof Concreting  2nd Floor          74.25
18                           Plywood 12mm      30.0     1700.0     51000.0  2025-12-22  Roof Concreting  2nd Floor          74.25
19                        Arcojack Rental      50.0        2.5       400.0  2025-12-22  Roof Concreting  2nd Floor          74.25
20                   Materials Transport        1.0     2000.0      2000.0  2025-12-22  Roof Concreting  2nd Floor          74.25
21                          Iron Rod 10mm     500.0      330.0    165000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
22                          Iron Rod 12mm      30.0      500.0     15000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
23                           Iron Rod 6mm      35.0      130.0      4550.0  2025-12-23  Roof Concreting  2nd Floor          74.25
24                           Binding Wire       3.0      400.0      1200.0  2025-12-23  Roof Concreting  2nd Floor          74.25
25                   Materials Transport        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
26                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
27                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
28                      Wave Transfer Fee       1.0      110.0       110.0  2025-12-23  Roof Concreting  2nd Floor          74.25
29                           Plywood 12mm      12.0     1700.0     20400.0  2025-12-24  Roof Concreting  2nd Floor          74.25
30                     Plywood Transport        1.0      500.0       500.0  2025-12-24  Roof Concreting  2nd Floor          74.25
31                              10m Rope        1.0      500.0       500.0  2025-12-24  Roof Concreting  2nd Floor          74.25
32                                   Poly       1.0      200.0       200.0  2025-12-24  Roof Concreting  2nd Floor          74.25
33                    Plumbing Materials        1.0    19132.0     19000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
34                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
35                           Plywood 12mm      10.0     1700.0     17000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
36                             Cardboard        2.0      400.0       800.0  2025-12-26  Roof Concreting  2nd Floor          74.10
37                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
38                   Electrical Materials       1.0    12475.0     12475.0  2025-12-26  Roof Concreting  2nd Floor          74.10
39         Electrical Material Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
40                             Wash Stone       3.0    14000.0     42000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
41                           Asphalt 19cu       1.0    94500.0     94500.0  2025-12-26  Roof Concreting  2nd Floor          74.10
42                                   Sand       2.0     8000.0     16000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
43                           Buba Tunkara       1.0     8000.0      8000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
44                          Nail(Box) 2in      25.0       30.0       750.0  2025-12-27  Roof Concreting  2nd Floor          74.10
45                                  Nails       1.0     1200.0      1200.0  2025-12-27  Roof Concreting  2nd Floor          74.10
46                        Arcojack Rental      25.0        2.5      1000.0  2025-12-27  Roof Concreting  2nd Floor          74.10
47                        2/3 Wood Rental      30.0        5.0      2400.0  2025-12-27  Roof Concreting  2nd Floor          74.10
48                   Materials Transport        1.0      600.0       600.0  2025-12-27  Roof Concreting  2nd Floor          74.10
49                               1/6 Wood      18.0      375.0      6750.0  2025-12-27  Roof Concreting  2nd Floor          74.10
50                               1/2 Wood       2.0      100.0       200.0  2025-12-27  Roof Concreting  2nd Floor          74.10
51                    Acrojack Transport        1.0      350.0       350.0  2025-12-27  Roof Concreting  2nd Floor          74.10
52                           Electrician        1.0     9000.0      9000.0  2025-12-27  Roof Concreting  2nd Floor          74.10
53                   Electrical Materials       2.0      500.0      1000.0  2025-12-28  Roof Concreting  2nd Floor          74.10
54                   Electrical Material        1.0     3100.0      3100.0  2025-12-29  Roof Concreting  2nd Floor          74.00
55         Electrical Material Transport        1.0      300.0       300.0  2025-12-29  Roof Concreting  2nd Floor          74.00
56                     Binding Wire(Roll)       1.0      500.0       500.0  2025-12-29  Roof Concreting  2nd Floor          74.00
57                 Adjusting the Pillars        1.0     1000.0      1000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
58                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
59                               Plumber        1.0    16000.0     16000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
60                   Ali Clearly pathway        1.0     1000.0      1000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
61                                Cement      364.0      480.0    174720.0  2025-12-29  Roof Concreting  2nd Floor          74.00
62                      Cement Transport      364.0       20.0      7280.0  2025-12-29  Roof Concreting  2nd Floor          74.00
63                               1/2 Wood      10.0      100.0      1000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
64                    1/2 Wood Transport        1.0      500.0       500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
65        1/12 Wood Rental and Transport        3.0      400.0       400.0  2025-12-30  Roof Concreting  2nd Floor          74.00
66                 Supervising Contractor       1.0     1500.0      1500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
67                         Stone(6 wheel)       1.0     8000.0      8000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
68                    Stone(6 wheel mini)       1.0     6500.0      6500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
69              Gas for Generator and Tea       1.0     1000.0      1000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
70                           Electrician        1.0      300.0       300.0  2025-12-30  Roof Concreting  2nd Floor          74.00
71                           Concrete Man       1.0    40000.0     40000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
72                       Food for Workers       1.0     2000.0      2000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
73                          Bubacarr Faye       1.0     5000.0      5000.0  2025-12-31  Roof Concreting  2nd Floor          74.00
74                     Gas for Generator        1.0      500.0       500.0  2025-12-31  Roof Concreting  2nd Floor          74.00
75                     Gas for Generator        1.0      500.0       500.0  2025-12-31  Roof Concreting  2nd Floor          74.00
76                             Ali Salary       1.0     5500.0      5500.0  2026-01-07  Roof Concreting  2nd Floor          74.00
77                   Ali Watering Rooftop       1.0     2000.0      2000.0  2026-01-07  Roof Concreting  2nd Floor          74.00
78  Ali Bringing Down Woods and Acrojacks       1.0     3500.0      3500.0  2026-01-15  Roof Concreting  2nd Floor          74.00
79              Roof Materials Transport        1.0    10000.0     10000.0  2026-01-15  Roof Concreting  2nd Floor          74.00
80        Plywood Rental 2Days Extension       60.0       20.0      3600.0  2026-01-18  Roof Concreting  2nd Floor          74.00
81       2/3 Wood Rental 2Days Extension      375.0        5.0      5625.0  2026-01-18  Roof Concreting  2nd Floor          74.00
82       Acrojack Rental 2Days Extension      475.0        2.5      3565.0  2026-01-18  Roof Concreting  2nd Floor          74.00
83                Carpenter Sana Payment        1.0     1500.0      1500.0  2026-01-20  Roof Concreting  2nd Floor          74.00
84                 Bubacarr Faye Payment        1.0    12000.0     12000.0  2026-01-22  Roof Concreting  2nd Floor          74.00
85      Ali moving the Woods  to the Room       1.0      481.0       481.0  2026-01-22  Roof Concreting  2nd Floor          74.00

In [8]:
secondfloor = pd.concat([secondfloor_brick, secondfloor_const, secondfloor_roof], axis=0, ignore_index=True)

In [9]:
secondfloor

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14,Brick Molding,2nd Floor,71.2
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15,Brick Molding,2nd Floor,71.2
2,Cement,25.0,390.0,9750.0,2025-04-16,Brick Molding,2nd Floor,71.2
3,Cement Transport,25.0,20.0,500.0,2025-04-16,Brick Molding,2nd Floor,71.2
4,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19,Brick Molding,2nd Floor,71.2
...,...,...,...,...,...,...,...,...
218,2/3 Wood Rental 2Days Extension,375.0,5.0,5625.0,2026-01-18,Roof Concreting,2nd Floor,74.0
219,Acrojack Rental 2Days Extension,475.0,2.5,3565.0,2026-01-18,Roof Concreting,2nd Floor,74.0
220,Carpenter Sana Payment,1.0,1500.0,1500.0,2026-01-20,Roof Concreting,2nd Floor,74.0
221,Bubacarr Faye Payment,1.0,12000.0,12000.0,2026-01-22,Roof Concreting,2nd Floor,74.0
222,Ali moving the Woods to the Room,1.0,481.0,481.0,2026-01-22,Roof Concreting,2nd Floor,74.0

In [10]:
print(secondfloor.to_string())

                                           item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                     Clearing Momo Haja's plot       1.0     3500.0      3500.0  2025-04-14    Brick Molding  2nd Floor          71.20
1             2nd Floor Plan Consultation(gas)        1.0      600.0       600.0  2025-04-15    Brick Molding  2nd Floor          71.20
2                                       Cement       25.0      390.0      9750.0  2025-04-16    Brick Molding  2nd Floor          71.20
3                             Cement Transport       25.0       20.0       500.0  2025-04-16    Brick Molding  2nd Floor          71.20
4                                 Sand(10Wheel)       1.0     8000.0      8000.0  2025-04-19    Brick Molding  2nd Floor          71.20
5                                 Sand Wave Fee       1.0       80.0        80.0  2025-04-19    Brick Molding  2nd Floor          71.20
6                             Gas for Generator       1.0      400.0       400.0  2025-04-21    Brick Molding  2nd Floor          71.20
7                                 Sand(10Wheel)       1.0     8000.0      8000.0  2025-04-22    Brick Molding  2nd Floor          71.20
8                    Waggeh-putting sand inside       1.0     1300.0      1300.0  2025-05-04    Brick Molding  2nd Floor          71.20
9                                 50 meter Hose       1.0     1600.0      1600.0  2025-04-19    Brick Molding  2nd Floor          71.20
10                                      Cement      150.0      465.0     69750.0  2025-07-08    Brick Molding  2nd Floor          69.00
11                            Cement Transport      150.0       20.0      3000.0  2025-07-08    Brick Molding  2nd Floor          69.00
12                               Sand(10Wheel)        1.0     8000.0      8000.0  2025-07-08    Brick Molding  2nd Floor          69.00
13                               Sand(10Wheel)        1.0     8000.0      8000.0  2025-07-16    Brick Molding  2nd Floor          68.90
14                           Wheelbarrow Repair       1.0      400.0       400.0  2025-07-17    Brick Molding  2nd Floor          69.00
15                            Wheelbarrow Wheel       1.0      700.0       700.0  2025-07-17    Brick Molding  2nd Floor          68.90
16                                         Lock       1.0      100.0       100.0  2025-07-17    Brick Molding  2nd Floor          69.00
17                               Sand(10Wheel)        2.0     8000.0     16000.0  2025-07-21    Brick Molding  2nd Floor          69.00
18                           Wheelbarrow Repair       1.0      150.0       150.0  2025-07-22    Brick Molding  2nd Floor          69.00
19                                     Watering       1.0     2350.0      2350.0  2025-07-23    Brick Molding  2nd Floor          69.00
20                            Borehole Machine        1.0     3500.0      3500.0  2025-07-23    Brick Molding  2nd Floor          69.00
21                                        Guard       1.0      500.0       500.0  2025-07-25    Brick Molding  2nd Floor          69.00
22                               Sand(10Wheel)        2.0     8000.0     16000.0  2025-07-26    Brick Molding  2nd Floor          69.00
23                                      Cement       50.0      475.0     23750.0  2025-07-30    Brick Molding  2nd Floor          69.00
24                            Cement Transport       50.0       25.0      1250.0  2025-07-30    Brick Molding  2nd Floor          69.00
25                        Brick Molding(200x25)    5000.0        7.0     35000.0  2025-08-05    Brick Molding  2nd Floor          69.00
26              Guard Transport during Bricking       1.0     1000.0      1000.0  2025-08-05    Brick Molding  2nd Floor          69.00
27                         Watering & Transport       1.0     3000.0      3000.0  2025-08-25    Brick Molding  2nd Floor          69.00
28                      Rope for Lifting Bricks       1.0      400.0       400.0  2025-08-28     Construction  2nd Floor          73.50
29                                Iron Rod 12mm      70.0      550.0     38500.0  2025-08-30     Construction  2nd Floor          73.50
30                                 Iron Rod 6mm      40.0      150.0      6000.0  2025-08-30     Construction  2nd Floor          73.50
31                                  Wheelbarrow       1.0     2800.0      2800.0  2025-08-30     Construction  2nd Floor          73.50
32                           Binding Wire(Roll)       2.0      500.0      1000.0  2025-08-30     Construction  2nd Floor          73.50
33                           Materials Transpot       1.0     1000.0      1000.0  2025-08-30     Construction  2nd Floor          73.50
34                                       Cement      50.0      480.0     24000.0  2025-08-30     Construction  2nd Floor          73.50
35                             Cement Transport      50.0       20.0      1000.0  2025-08-30     Construction  2nd Floor          73.50
36             Contractor Momodou Njaye Payment       1.0    90000.0     90000.0  2025-08-30     Construction  2nd Floor          73.50
37                            Gas for Generator       1.0      530.0       530.0  2025-08-31     Construction  2nd Floor          73.50
38                             Generator Repair       1.0     1200.0      1200.0  2025-09-05     Construction  2nd Floor          73.50
39                                Sand(10Wheel)       1.0     8300.0      8300.0  2025-09-06     Construction  2nd Floor          73.50
40             Contractor Momodou Njaye Payment       1.0   100000.0    100000.0  2025-09-08     Construction  2nd Floor          73.50
41                                       Cement      50.0      480.0     24000.0  2025-09-10     Construction  2nd Floor          73.50
42                             Cement Transport      50.0       20.0      1000.0  2025-09-10     Construction  2nd Floor          73.50
43                                  1 by 2 wood      40.0      100.0      4000.0  2025-09-13     Construction  2nd Floor          73.50
44                           Splitting Plywoods       1.0      650.0       650.0  2025-09-13     Construction  2nd Floor          73.50
45                           Materials Transpot       1.0      600.0       600.0  2025-09-13     Construction  2nd Floor          73.50
46                                Nail(kg) 3 in       3.0      100.0       300.0  2025-09-13     Construction  2nd Floor          73.50
47                                Nail(kg) 3 in       4.0      100.0       400.0  2025-09-15     Construction  2nd Floor          73.50
48                                       Cement      50.0      480.0     24000.0  2025-09-16     Construction  2nd Floor          73.50
49                             Cement Transport      50.0       20.0      1000.0  2025-09-16     Construction  2nd Floor          73.50
50                      Asphalt Stone(19 cubic)       1.0    95000.0     95000.0  2025-09-17     Construction  2nd Floor          73.50
51                                Iron Rod 12mm      25.0      540.0     13500.0  2025-09-17     Construction  2nd Floor          73.50
52                                Iron Rod 10mm     280.0      330.0     92400.0  2025-09-17     Construction  2nd Floor          73.50
53                                 Iron Rod 6mm     125.0      140.0     17500.0  2025-09-17     Construction  2nd Floor          73.50
54                           Binding Wire(Roll)       3.0      400.0      1200.0  2025-09-17     Construction  2nd Floor          73.50
55                          Iron Rods Transport       1.0     3000.0      3000.0  2025-09-17     Construction  2nd Floor          73.50
56                                    Chain(2m)       1.0      700.0       700.0  2025-09-17     Construction  2nd Floor          73.50
57                                         Lock       1.0      250.0       250.0  2025-09-17     Construction  2nd Floor          73.50
58                                       1 by 6      10.0      400.0      4000.0  2025-09-17     Construction  2nd Floor          73.50
59                  1 by 6 & 12mm Rod Transport       1.0      600.0       600.0  2025-09-17     Construction  2nd Floor          73.50
60                                Nail(kg) 3 in       2.0      100.0       200.0  2025-09-17     Construction  2nd Floor          73.50
61                                Sand(10Wheel)       1.0     8300.0      8300.0  2025-09-17     Construction  2nd Floor          73.50
62             Contractor Momodou Njaye Payment       1.0   100000.0    100000.0  2025-09-21     Construction  2nd Floor          73.60
63                                       Bucket       3.0      100.0       300.0  2025-09-22     Construction  2nd Floor          73.60
64                           Binding Wire(Roll)       2.0      500.0      1000.0  2025-09-22     Construction  2nd Floor          73.60
65                                  1 by 2 wood      20.0      100.0      2000.0  2025-09-24     Construction  2nd Floor          73.60
66               Splitting Rest of the Plywoods       1.0     1125.0      1125.0  2025-09-24     Construction  2nd Floor          73.60
67                   Plywood & 1 by 2 Transport       1.0      800.0       800.0  2025-09-24     Construction  2nd Floor          73.60
68                                Nail(kg) 3 in       5.0      100.0       500.0  2025-09-29     Construction  2nd Floor          73.60
69                                Nail(kg) 2 in       2.0      100.0       200.0  2025-09-29     Construction  2nd Floor          73.60
70                                Nail(kg) 1 in       2.0      100.0       200.0  2025-09-29     Construction  2nd Floor          73.60
71                                       Cement      50.0      480.0     24000.0  2025-09-30     Construction  2nd Floor          73.60
72                             Cement Transport      50.0       20.0      1000.0  2025-09-30     Construction  2nd Floor          73.60
73                    Momo Waggeh's Sept Salary       1.0     4000.0      4000.0  2025-09-30     Construction  2nd Floor          73.60
74                            Gas for Generator       1.0      500.0       500.0  2025-10-01     Construction  2nd Floor          73.60
75             Njaye Extra- Transporting Bricks       1.0     5000.0      5000.0  2025-10-04     Construction  2nd Floor          73.60
76                            For Bubacarr Faye       1.0     5000.0      5000.0  2025-10-09     Construction  2nd Floor          73.60
77                                       Cement      50.0      480.0     24000.0  2025-10-11     Construction  2nd Floor          73.60
78                             Cement Transport      50.0       20.0      1000.0  2025-10-11     Construction  2nd Floor          73.60
79                            Gas for Generator       1.0      400.0       400.0  2025-10-13     Construction  2nd Floor          73.60
80                             Generator Repair       1.0     2700.0      2700.0  2025-10-14     Construction  2nd Floor          73.60
81                          Generator Transport       1.0      600.0       600.0  2025-10-14     Construction  2nd Floor          73.60
82                           Wheelbarrow Repair       1.0      800.0       800.0  2025-10-14     Construction  2nd Floor          73.60
83                                Sand(10Wheel)       1.0     8500.0      8500.0  2025-10-17     Construction  2nd Floor          73.60
84                           Binding Wire(Roll)       1.0      500.0       500.0  2025-10-17     Construction  2nd Floor          73.60
85                                Nail(kg) 3 in       3.0      100.0       300.0  2025-10-17     Construction  2nd Floor          73.60
86                            Gas for Generator       1.0      435.0       435.0  2025-10-19     Construction  2nd Floor          73.60
87                                Nail(kg) 3 in       7.0      100.0       700.0  2025-10-20     Construction  2nd Floor          73.60
88                                Nail(kg) 2 in       3.0      100.0       300.0  2025-10-20     Construction  2nd Floor          73.60
89                            Momo Waggeh's Bed       1.0     2000.0      2000.0  2025-10-20     Construction  2nd Floor          73.60
90             Contractor Momodou Njaye Payment       1.0    10000.0     10000.0  2025-10-20     Construction  2nd Floor          73.60
91                            Gas for Generator       1.0      440.0       440.0  2025-10-23     Construction  2nd Floor          73.60
92                           Wheelbarrow Repair       1.0     1500.0      1500.0  2025-10-23     Construction  2nd Floor          73.60
93                                       Cement      25.0      480.0     12000.0  2025-10-24     Construction  2nd Floor          73.60
94                             Cement Transport      25.0       20.0       500.0  2025-10-24     Construction  2nd Floor          73.60
95                           Pilar Mold Rental        3.0     2000.0      6000.0  2025-10-24     Construction  2nd Floor          73.60
96                                Tank Removal        1.0     5000.0      5000.0  2025-10-24     Construction  2nd Floor          73.60
97                            Gas for Generator       1.0      500.0       500.0  2025-10-26     Construction  2nd Floor          74.00
98                                       Cement      25.0      480.0     12000.0  2025-10-27     Construction  2nd Floor          74.00
99                             Cement Transport      25.0       20.0       500.0  2025-10-27     Construction  2nd Floor          74.00
100                                Plywood 12mm       4.0     1725.0      6900.0  2025-10-27     Construction  2nd Floor          74.00
101                                  Cardboard        3.0      350.0      1050.0  2025-10-27     Construction  2nd Floor          74.00
102                                 1 by 2 wood       4.0      100.0       400.0  2025-10-27     Construction  2nd Floor          74.00
103               Plywood & cardboard Transport       1.0      400.0       400.0  2025-10-27     Construction  2nd Floor          74.00
104                            Generator Repair       1.0     1650.0      1650.0  2025-10-27     Construction  2nd Floor          74.00
105                          six Pilar Iron Man       1.0     2500.0      2500.0  2025-10-28     Construction  2nd Floor          74.00
106                       Momo Waggeh's Salary        1.0     4000.0      4000.0  2025-10-31     Construction  2nd Floor          74.00
107  Workers Bathroom Plumbing Materials +Trans       1.0     5975.0      5975.0  2025-11-01     Construction  2nd Floor          74.00
108                           Four Pillars Mold       3.0     1000.0      3000.0  2025-11-01     Construction  2nd Floor          74.00
109                Four Pillars Mold Transport        2.0      500.0      1000.0  2025-11-01     Construction  2nd Floor          74.00
110                                 1 by 2 wood       5.0      100.0       500.0  2025-11-03     Construction  2nd Floor          74.00
111                               Nail(kg) 3 in       1.0      100.0       100.0  2025-11-03     Construction  2nd Floor          74.00
112                                 1 by 6 Wood       2.0      400.0       800.0  2025-11-04     Construction  2nd Floor          74.00
113                               Nail(kg) 3 in       3.0      100.0       300.0  2025-11-04     Construction  2nd Floor          74.00
114                 Bathroom Plumbing Materials       1.0      500.0       500.0  2025-11-04     Construction  2nd Floor          74.00
115                               Borehole Pile       1.0     2050.0      2050.0  2025-11-04     Construction  2nd Floor          74.00
116                                      Cement      25.0      480.0     12000.0  2025-11-04     Construction  2nd Floor          74.00
117                            Cement Transport      25.0       20.0       500.0  2025-11-04     Construction  2nd Floor          74.00
118                         Joins For Plumbing        2.0      150.0       300.0  2025-11-04     Construction  2nd Floor          74.00
119                     Tube for Plumbing(15mm)      15.0       50.0       750.0  2025-11-04     Construction  2nd Floor          74.00
120                               Soft Plywood        1.0     1000.0      1000.0  2025-11-04     Construction  2nd Floor          74.00
121                          Plywood Transport        1.0      400.0       400.0  2025-11-04     Construction  2nd Floor          74.00
122                                Plumber Fees       1.0     4500.0      4500.0  2025-11-05     Construction  2nd Floor          74.00
123                                   Wave Fees       1.0      120.0       120.0  2025-11-05     Construction  2nd Floor          74.00
124                                   Scarfing        3.0      450.0      1350.0  2025-11-06     Construction  2nd Floor          74.00
125                         Scarfing Transport        1.0      400.0       400.0  2025-11-06     Construction  2nd Floor          74.00
126                                 1 by 2 wood       5.0      100.0       500.0  2025-11-07     Construction  2nd Floor          74.00
127                      1 by 2 wood Transport        1.0      300.0       300.0  2025-11-07     Construction  2nd Floor          74.00
128    Bathroom Manual and plastering the floor       1.0     2500.0      2500.0  2025-11-07     Construction  2nd Floor          74.00
129                          Pilar Mold Rental        4.0     2000.0      8000.0  2025-11-11     Construction  2nd Floor          74.00
130                          Balcony Extension        1.0     2000.0      2000.0  2025-11-14     Construction  2nd Floor          74.00
131            Contractor Momodou Njaye Payment       1.0    10000.0     10000.0  2025-11-14     Construction  2nd Floor          74.00
132                              Bathroom Door        1.0     2600.0      2600.0  2025-11-15     Construction  2nd Floor          74.00
133                                 Ali Salary        1.0     5500.0      5500.0  2025-11-15     Construction  2nd Floor          74.00
134                        Scarfing + Acro Jack       1.0     2994.0      2994.0  2025-11-17     Construction  2nd Floor          74.00
135             Scarfing + Acro Jack Transport        1.0     1000.0      1000.0  2025-11-17     Construction  2nd Floor          74.00
136                            Miss Calculation       1.0      500.0       500.0  2025-12-17     Construction  2nd Floor          74.00
137                                    1/2 wood     100.0      100.0     10000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
138                         1/2 Wood Transport        1.0     1000.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
139                      Concrete Nail 2 1/2 in       5.0      200.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
140                          Concrete Nail 2 in      45.0       30.0      1350.0  2025-12-05  Roof Concreting  2nd Floor          74.25
141                                    1/2 Wood      35.0      100.0      3500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
142                                    1/6 Wood       2.0      350.0       700.0  2025-12-06  Roof Concreting  2nd Floor          74.25
143                             Wood Transport        1.0      500.0       500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
144                     Carpenter Sana Payment        1.0    15000.0     15000.0  2025-12-06  Roof Concreting  2nd Floor          74.25
145                             2/3 Wood Rental     350.0        5.0     52500.0  2025-12-13  Roof Concreting  2nd Floor          74.25

In [11]:
secondfloor['total_cost'].sum()

np.float64(2128055.0)

In [12]:
secondfloor.to_csv('ParadiseView/clean/floorTwo.csv', index=False)

In [13]:
pd.read_csv('ParadiseView/clean/floorTwo.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14,Brick Molding,2nd Floor,71.2
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15,Brick Molding,2nd Floor,71.2
2,Cement,25.0,390.0,9750.0,2025-04-16,Brick Molding,2nd Floor,71.2
3,Cement Transport,25.0,20.0,500.0,2025-04-16,Brick Molding,2nd Floor,71.2
4,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19,Brick Molding,2nd Floor,71.2
...,...,...,...,...,...,...,...,...
218,2/3 Wood Rental 2Days Extension,375.0,5.0,5625.0,2026-01-18,Roof Concreting,2nd Floor,74.0
219,Acrojack Rental 2Days Extension,475.0,2.5,3565.0,2026-01-18,Roof Concreting,2nd Floor,74.0
220,Carpenter Sana Payment,1.0,1500.0,1500.0,2026-01-20,Roof Concreting,2nd Floor,74.0
221,Bubacarr Faye Payment,1.0,12000.0,12000.0,2026-01-22,Roof Concreting,2nd Floor,74.0
222,Ali moving the Woods to the Room,1.0,481.0,481.0,2026-01-22,Roof Concreting,2nd Floor,74.0