In [1]:
import numpy as np
import pandas as pd

In [5]:
second_floor_bmolding = pd.read_excel('ParadiseView/Paradise View Expenditures 4.xlsx', skiprows=4, sheet_name='2nd Floor Brick Molding')

In [8]:
second_floor_bmolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),Date
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15
2,Cement,25.0,390.0,9750.0,2025-04-16
3,Cement Transport,25.0,20.0,500.0,2025-04-16
4,NaN,NaN,NaN,NaN,NaT
5,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19
6,Sand Wave Fee,1.0,80.0,80.0,2025-04-19
7,Gas for Generator,1.0,400.0,400.0,2025-04-21
8,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-22
9,Waggeh-putting sand inside,1.0,1300.0,1300.0,2025-05-04
10,NaN,NaN,NaN,NaN,NaT
11,50 meter Hose,1.0,1600.0,1600.0,2025-04-19
12,NaN,NaN,NaN,NaN,NaT
13,Cement,150.0,465.0,69750.0,2025-07-08
14,Cement Transport,150.0,20.0,3000.0,2025-07-08
15,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-08
16,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-16
17,Wheelbarrow Repair,1.0,400.0,400.0,2025-07-17
18,Wheelbarrow Wheel,1.0,700.0,700.0,2025-07-17
19,Lock,1.0,100.0,100.0,2025-07-17
20,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-21
21,Wheelbarrow Repair,1.0,150.0,150.0,2025-07-22
22,Watering,1.0,2350.0,2350.0,2025-07-23
23,Borehole Machine,1.0,3500.0,3500.0,2025-07-23
24,Guard,1.0,500.0,500.0,2025-07-25
25,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-26
26,Cement,50.0,475.0,23750.0,2025-07-30
27,Cement Transport,50.0,25.0,1250.0,2025-07-30
28,Brick Molding(200x25),5000.0,7.0,35000.0,2025-08-05
29,Guard Transport during Bricking,1.0,1000.0,1000.0,2025-08-05
30,Watering & Transport,1.0,3000.0,3000.0,2025-08-25
31,NaN,NaN,NaN,NaN,NaT
32,Total,NaN,NaN,226180.0,NaT

In [9]:
second_floor_bmolding.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ITEM           29 non-null     str
 1   QUANTITY       28 non-null     float64
 2   UNIT PRICE(D)  28 non-null     float64
 3   TOTAL COST(D)  29 non-null     float64
 4   Date           28 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 1.4 KB

In [14]:
second_floor_bmolding = second_floor_bmolding.dropna()

In [15]:
second_floor_bmolding

,ITEM,QUANTITY,UNIT PRICE(D),TOTAL COST(D),Date
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15
2,Cement,25.0,390.0,9750.0,2025-04-16
3,Cement Transport,25.0,20.0,500.0,2025-04-16
5,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19
6,Sand Wave Fee,1.0,80.0,80.0,2025-04-19
7,Gas for Generator,1.0,400.0,400.0,2025-04-21
8,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-22
9,Waggeh-putting sand inside,1.0,1300.0,1300.0,2025-05-04
11,50 meter Hose,1.0,1600.0,1600.0,2025-04-19
13,Cement,150.0,465.0,69750.0,2025-07-08
14,Cement Transport,150.0,20.0,3000.0,2025-07-08
15,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-08
16,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-16
17,Wheelbarrow Repair,1.0,400.0,400.0,2025-07-17
18,Wheelbarrow Wheel,1.0,700.0,700.0,2025-07-17
19,Lock,1.0,100.0,100.0,2025-07-17
20,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-21
21,Wheelbarrow Repair,1.0,150.0,150.0,2025-07-22
22,Watering,1.0,2350.0,2350.0,2025-07-23
23,Borehole Machine,1.0,3500.0,3500.0,2025-07-23
24,Guard,1.0,500.0,500.0,2025-07-25
25,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-26
26,Cement,50.0,475.0,23750.0,2025-07-30
27,Cement Transport,50.0,25.0,1250.0,2025-07-30
28,Brick Molding(200x25),5000.0,7.0,35000.0,2025-08-05
29,Guard Transport during Bricking,1.0,1000.0,1000.0,2025-08-05
30,Watering & Transport,1.0,3000.0,3000.0,2025-08-25

In [16]:
second_floor_bmolding.info()

<class 'pandas.DataFrame'>
Index: 28 entries, 0 to 30
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ITEM           28 non-null     str
 1   QUANTITY       28 non-null     float64
 2   UNIT PRICE(D)  28 non-null     float64
 3   TOTAL COST(D)  28 non-null     float64
 4   Date           28 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 1.3 KB

In [17]:
second_floor_bmolding.columns

Index(['ITEM', 'QUANTITY ', 'UNIT PRICE(D)', 'TOTAL COST(D)', 'Date'], dtype='str')

In [18]:
second_floor_bmolding.columns = second_floor_bmolding.columns.str.lower()

In [19]:
second_floor_bmolding.columns

Index(['item', 'quantity ', 'unit price(d)', 'total cost(d)', 'date'], dtype='str')

In [22]:
second_floor_bmolding.rename(columns={'quantity ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [23]:
second_floor_bmolding.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [24]:
second_floor_bmolding

,item,quantity,unit_cost,total_cost,date
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15
2,Cement,25.0,390.0,9750.0,2025-04-16
3,Cement Transport,25.0,20.0,500.0,2025-04-16
5,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19
6,Sand Wave Fee,1.0,80.0,80.0,2025-04-19
7,Gas for Generator,1.0,400.0,400.0,2025-04-21
8,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-22
9,Waggeh-putting sand inside,1.0,1300.0,1300.0,2025-05-04
11,50 meter Hose,1.0,1600.0,1600.0,2025-04-19
13,Cement,150.0,465.0,69750.0,2025-07-08
14,Cement Transport,150.0,20.0,3000.0,2025-07-08
15,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-08
16,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-16
17,Wheelbarrow Repair,1.0,400.0,400.0,2025-07-17
18,Wheelbarrow Wheel,1.0,700.0,700.0,2025-07-17
19,Lock,1.0,100.0,100.0,2025-07-17
20,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-21
21,Wheelbarrow Repair,1.0,150.0,150.0,2025-07-22
22,Watering,1.0,2350.0,2350.0,2025-07-23
23,Borehole Machine,1.0,3500.0,3500.0,2025-07-23
24,Guard,1.0,500.0,500.0,2025-07-25
25,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-26
26,Cement,50.0,475.0,23750.0,2025-07-30
27,Cement Transport,50.0,25.0,1250.0,2025-07-30
28,Brick Molding(200x25),5000.0,7.0,35000.0,2025-08-05
29,Guard Transport during Bricking,1.0,1000.0,1000.0,2025-08-05
30,Watering & Transport,1.0,3000.0,3000.0,2025-08-25

In [25]:
second_floor_bmolding['sub_category'] = 'Brick Molding'
second_floor_bmolding['category'] = '2nd Floor'

In [26]:
second_floor_bmolding.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category',
       'category'],
      dtype='str')

In [27]:
second_floor_bmolding.info()

<class 'pandas.DataFrame'>
Index: 28 entries, 0 to 30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   item          28 non-null     str
 1   quantity      28 non-null     float64
 2   unit_cost     28 non-null     float64
 3   total_cost    28 non-null     float64
 4   date          28 non-null     datetime64[us]
 5   sub_category  28 non-null     str
 6   category      28 non-null     str
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 1.8 KB

In [31]:
second_floor_bmolding['exchange_rate'] = 0.00

In [34]:
second_floor_bmolding.loc[:11, 'exchange_rate'] = 71.20

In [37]:
second_floor_bmolding.loc[12:, 'exchange_rate'] = 69.00

In [40]:
second_floor_bmolding.at[16, 'exchange_rate'] = 68.90

In [41]:
second_floor_bmolding.at[18, 'exchange_rate'] = 68.90

In [42]:
second_floor_bmolding

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14,Brick Molding,2nd Floor,71.2
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15,Brick Molding,2nd Floor,71.2
2,Cement,25.0,390.0,9750.0,2025-04-16,Brick Molding,2nd Floor,71.2
3,Cement Transport,25.0,20.0,500.0,2025-04-16,Brick Molding,2nd Floor,71.2
5,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19,Brick Molding,2nd Floor,71.2
6,Sand Wave Fee,1.0,80.0,80.0,2025-04-19,Brick Molding,2nd Floor,71.2
7,Gas for Generator,1.0,400.0,400.0,2025-04-21,Brick Molding,2nd Floor,71.2
8,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-22,Brick Molding,2nd Floor,71.2
9,Waggeh-putting sand inside,1.0,1300.0,1300.0,2025-05-04,Brick Molding,2nd Floor,71.2
11,50 meter Hose,1.0,1600.0,1600.0,2025-04-19,Brick Molding,2nd Floor,71.2
13,Cement,150.0,465.0,69750.0,2025-07-08,Brick Molding,2nd Floor,69.0
14,Cement Transport,150.0,20.0,3000.0,2025-07-08,Brick Molding,2nd Floor,69.0
15,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-08,Brick Molding,2nd Floor,69.0
16,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-16,Brick Molding,2nd Floor,68.9
17,Wheelbarrow Repair,1.0,400.0,400.0,2025-07-17,Brick Molding,2nd Floor,69.0
18,Wheelbarrow Wheel,1.0,700.0,700.0,2025-07-17,Brick Molding,2nd Floor,68.9
19,Lock,1.0,100.0,100.0,2025-07-17,Brick Molding,2nd Floor,69.0
20,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-21,Brick Molding,2nd Floor,69.0
21,Wheelbarrow Repair,1.0,150.0,150.0,2025-07-22,Brick Molding,2nd Floor,69.0
22,Watering,1.0,2350.0,2350.0,2025-07-23,Brick Molding,2nd Floor,69.0
23,Borehole Machine,1.0,3500.0,3500.0,2025-07-23,Brick Molding,2nd Floor,69.0
24,Guard,1.0,500.0,500.0,2025-07-25,Brick Molding,2nd Floor,69.0
25,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-26,Brick Molding,2nd Floor,69.0
26,Cement,50.0,475.0,23750.0,2025-07-30,Brick Molding,2nd Floor,69.0
27,Cement Transport,50.0,25.0,1250.0,2025-07-30,Brick Molding,2nd Floor,69.0
28,Brick Molding(200x25),5000.0,7.0,35000.0,2025-08-05,Brick Molding,2nd Floor,69.0
29,Guard Transport during Bricking,1.0,1000.0,1000.0,2025-08-05,Brick Molding,2nd Floor,69.0
30,Watering & Transport,1.0,3000.0,3000.0,2025-08-25,Brick Molding,2nd Floor,69.0

In [43]:
second_floor_bmolding.info()

<class 'pandas.DataFrame'>
Index: 28 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           28 non-null     str
 1   quantity       28 non-null     float64
 2   unit_cost      28 non-null     float64
 3   total_cost     28 non-null     float64
 4   date           28 non-null     datetime64[us]
 5   sub_category   28 non-null     str
 6   category       28 non-null     str
 7   exchange_rate  28 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 3.0 KB

In [44]:
second_floor_bmolding.to_csv('ParadiseView/out/df_secondfloor_bmolding.csv', index=False)

In [45]:
pd.read_csv('ParadiseView/out/df_secondfloor_bmolding.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Clearing Momo Haja's plot,1.0,3500.0,3500.0,2025-04-14,Brick Molding,2nd Floor,71.2
1,2nd Floor Plan Consultation(gas),1.0,600.0,600.0,2025-04-15,Brick Molding,2nd Floor,71.2
2,Cement,25.0,390.0,9750.0,2025-04-16,Brick Molding,2nd Floor,71.2
3,Cement Transport,25.0,20.0,500.0,2025-04-16,Brick Molding,2nd Floor,71.2
4,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-19,Brick Molding,2nd Floor,71.2
5,Sand Wave Fee,1.0,80.0,80.0,2025-04-19,Brick Molding,2nd Floor,71.2
6,Gas for Generator,1.0,400.0,400.0,2025-04-21,Brick Molding,2nd Floor,71.2
7,Sand(10Wheel),1.0,8000.0,8000.0,2025-04-22,Brick Molding,2nd Floor,71.2
8,Waggeh-putting sand inside,1.0,1300.0,1300.0,2025-05-04,Brick Molding,2nd Floor,71.2
9,50 meter Hose,1.0,1600.0,1600.0,2025-04-19,Brick Molding,2nd Floor,71.2
10,Cement,150.0,465.0,69750.0,2025-07-08,Brick Molding,2nd Floor,69.0
11,Cement Transport,150.0,20.0,3000.0,2025-07-08,Brick Molding,2nd Floor,69.0
12,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-08,Brick Molding,2nd Floor,69.0
13,Sand(10Wheel),1.0,8000.0,8000.0,2025-07-16,Brick Molding,2nd Floor,68.9
14,Wheelbarrow Repair,1.0,400.0,400.0,2025-07-17,Brick Molding,2nd Floor,69.0
15,Wheelbarrow Wheel,1.0,700.0,700.0,2025-07-17,Brick Molding,2nd Floor,68.9
16,Lock,1.0,100.0,100.0,2025-07-17,Brick Molding,2nd Floor,69.0
17,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-21,Brick Molding,2nd Floor,69.0
18,Wheelbarrow Repair,1.0,150.0,150.0,2025-07-22,Brick Molding,2nd Floor,69.0
19,Watering,1.0,2350.0,2350.0,2025-07-23,Brick Molding,2nd Floor,69.0
20,Borehole Machine,1.0,3500.0,3500.0,2025-07-23,Brick Molding,2nd Floor,69.0
21,Guard,1.0,500.0,500.0,2025-07-25,Brick Molding,2nd Floor,69.0
22,Sand(10Wheel),2.0,8000.0,16000.0,2025-07-26,Brick Molding,2nd Floor,69.0
23,Cement,50.0,475.0,23750.0,2025-07-30,Brick Molding,2nd Floor,69.0
24,Cement Transport,50.0,25.0,1250.0,2025-07-30,Brick Molding,2nd Floor,69.0
25,Brick Molding(200x25),5000.0,7.0,35000.0,2025-08-05,Brick Molding,2nd Floor,69.0
26,Guard Transport during Bricking,1.0,1000.0,1000.0,2025-08-05,Brick Molding,2nd Floor,69.0
27,Watering & Transport,1.0,3000.0,3000.0,2025-08-25,Brick Molding,2nd Floor,69.0