In [1]:
import numpy as np
import pandas as pd
from datetime import date, datetime

In [101]:
secondfloor_const = pd.read_csv("ParadiseView/2nd Floor Construction.csv")

In [102]:
secondfloor_const.columns

Index(['ITEM', 'QUALITY ', 'UNIT PRICE(D)', 'TOTAL COST(D)', 'DATE',
       'Unnamed: 5'],
      dtype='str')

In [103]:
secondfloor_const.drop(columns='Unnamed: 5', inplace=True)

In [104]:
secondfloor_const.columns

Index(['ITEM', 'QUALITY ', 'UNIT PRICE(D)', 'TOTAL COST(D)', 'DATE'], dtype='str')

In [105]:
secondfloor_const.columns = secondfloor_const.columns.str.lower()

In [106]:
secondfloor_const.columns

Index(['item', 'quality ', 'unit price(d)', 'total cost(d)', 'date'], dtype='str')

In [107]:
secondfloor_const

,item,quality,unit price(d),total cost(d),date
0,Rope for Lifting Bricks,1.0,400.00,400.00,8/28/2025
1,Iron Rod 12mm,70.0,550.00,"38,500.00",8/30/2025
2,Iron Rod 6mm,40.0,150.00,"6,000.00",8/30/2025
3,Wheelbarrow,1.0,"2,800.00","2,800.00",8/30/2025
4,Binding Wire(Roll),2.0,500.00,"1,000.00",8/30/2025
...,...,...,...,...,...
132,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,NaN,NaN
134,TOTAL AMOUNT SPENT,NaN,NaN,"911,969.00",NaN
135,NaN,NaN,NaN,NaN,NaN
136,REMAINING BALANCE IN HAND,NaN,NaN,"911,969.00",NaN

In [108]:
secondfloor_const.dropna(thresh=3, inplace=True)

In [109]:
secondfloor_const.tail(10)

,item,quality,unit price(d),total cost(d),date
105,Ali Salary,1.0,"5,500.00","5,500.00",NaN
106,Scarfing + Acro Jack,1.0,"2,994.00","2,994.00",11/17/25
107,Scarfing + Acro Jack Transport,1.0,"1,000.00","1,000.00",11/17/25
108,Miss Calculation,1.0,500.00,500.00,12/17/25
115,To Buba Tunkara,1.0,"20,000.00","20,000.00",10/9/2025
121,"On 08/26/25, from Tata",NaN,"$294,000","$4,000",$1 = 73.50
123,"On 9/09/25, from Awa",NaN,"$367,500","$5,000",$1 = 73.50
125,"On 9/21/25, from Tata",NaN,"$147,200","$2,000",$1 = 73.60
127,"On 10/26/25, from Awa",NaN,"148,000.00","$2,000",$1 = 74.00
131,TOTAL AMOUNT GIVING TO DATE,NaN,"956,700.00","$13,000",NaN

In [110]:
secondfloor_const = secondfloor_const.drop(secondfloor_const.loc[115:].index)

In [111]:
secondfloor_const.tail()

,item,quality,unit price(d),total cost(d),date
104,Bathroom Door,1.0,"2,600.00","2,600.00",NaN
105,Ali Salary,1.0,"5,500.00","5,500.00",NaN
106,Scarfing + Acro Jack,1.0,"2,994.00","2,994.00",11/17/25
107,Scarfing + Acro Jack Transport,1.0,"1,000.00","1,000.00",11/17/25
108,Miss Calculation,1.0,500.00,500.00,12/17/25

In [112]:
secondfloor_const.loc[[104, 105], 'date'] = '11/15/25'

In [113]:
secondfloor_const.tail()

,item,quality,unit price(d),total cost(d),date
104,Bathroom Door,1.0,"2,600.00","2,600.00",11/15/25
105,Ali Salary,1.0,"5,500.00","5,500.00",11/15/25
106,Scarfing + Acro Jack,1.0,"2,994.00","2,994.00",11/17/25
107,Scarfing + Acro Jack Transport,1.0,"1,000.00","1,000.00",11/17/25
108,Miss Calculation,1.0,500.00,500.00,12/17/25

In [202]:
print(secondfloor_const.to_string())

                                           item  quantity  unit_cost  total_cost       date
0                       Rope for Lifting Bricks         1      400.0       400.0 2025-08-28
1                                 Iron Rod 12mm        70      550.0     38500.0 2025-08-30
2                                  Iron Rod 6mm        40      150.0      6000.0 2025-08-30
3                                   Wheelbarrow         1     2800.0      2800.0 2025-08-30
4                            Binding Wire(Roll)         2      500.0      1000.0 2025-08-30
5                            Materials Transpot         1     1000.0      1000.0 2025-08-30
6                                        Cement        50      480.0     24000.0 2025-08-30
7                              Cement Transport        50       20.0      1000.0 2025-08-30
8              Contractor Momodou Njaye Payment         1    90000.0     90000.0 2025-08-30
9                             Gas for Generator         1      530.0       530.0 2025-08-31
10                             Generator Repair         1     1200.0      1200.0 2025-09-05
11                                Sand(10Wheel)         1     8300.0      8300.0 2025-09-06
12             Contractor Momodou Njaye Payment         1   100000.0    100000.0 2025-09-08
13                                       Cement        50      480.0     24000.0 2025-09-10
14                             Cement Transport        50       20.0      1000.0 2025-09-10
15                                  1 by 2 wood        40      100.0      4000.0 2025-09-13
16                           Splitting Plywoods         1      650.0       650.0 2025-09-13
17                           Materials Transpot         1      600.0       600.0 2025-09-13
18                                Nail(kg) 3 in         3      100.0       300.0 2025-09-13
19                                Nail(kg) 3 in         4      100.0       400.0 2025-09-15
20                                       Cement        50      480.0     24000.0 2025-09-16
21                             Cement Transport        50       20.0      1000.0 2025-09-16
22                      Asphalt Stone(19 cubic)         1    95000.0     95000.0 2025-09-17
23                                Iron Rod 12mm        25      540.0     13500.0 2025-09-17
24                                Iron Rod 10mm       280      330.0     92400.0 2025-09-17
25                                 Iron Rod 6mm       125      140.0     17500.0 2025-09-17
26                           Binding Wire(Roll)         3      400.0      1200.0 2025-09-17
27                          Iron Rods Transport         1     3000.0      3000.0 2025-09-17
28                                    Chain(2m)         1      700.0       700.0 2025-09-17
29                                         Lock         1      250.0       250.0 2025-09-17
30                                       1 by 6        10      400.0      4000.0 2025-09-17
31                  1 by 6 & 12mm Rod Transport         1      600.0       600.0 2025-09-17
32                                Nail(kg) 3 in         2      100.0       200.0 2025-09-17
33                                Sand(10Wheel)         1     8300.0      8300.0 2025-09-17
34             Contractor Momodou Njaye Payment         1   100000.0    100000.0 2025-09-21
35                                       Bucket         3      100.0       300.0 2025-09-22
36                           Binding Wire(Roll)         2      500.0      1000.0 2025-09-22
37                                  1 by 2 wood        20      100.0      2000.0 2025-09-24
38               Splitting Rest of the Plywoods         1     1125.0      1125.0 2025-09-24
39                   Plywood & 1 by 2 Transport         1      800.0       800.0 2025-09-24
40                                Nail(kg) 3 in         5      100.0       500.0 2025-09-29
41                                Nail(kg) 2 in         2      100.0       200.0 2025-09-29
42                                Nail(kg) 1 in         2      100.0       200.0 2025-09-29
43                                       Cement        50      480.0     24000.0 2025-09-30
44                             Cement Transport        50       20.0      1000.0 2025-09-30
45                    Momo Waggeh's Sept Salary         1     4000.0      4000.0 2025-09-30
46                            Gas for Generator         1      500.0       500.0 2025-10-01
47             Njaye Extra- Transporting Bricks         1     5000.0      5000.0 2025-10-04
48                            For Bubacarr Faye         1     5000.0      5000.0 2025-10-09
49                                       Cement        50      480.0     24000.0 2025-10-11
50                             Cement Transport        50       20.0      1000.0 2025-10-11
51                            Gas for Generator         1      400.0       400.0 2025-10-13
52                             Generator Repair         1     2700.0      2700.0 2025-10-14
53                          Generator Transport         1      600.0       600.0 2025-10-14
54                           Wheelbarrow Repair         1      800.0       800.0 2025-10-14
55                                Sand(10Wheel)         1     8500.0      8500.0 2025-10-17
56                           Binding Wire(Roll)         1      500.0       500.0 2025-10-17
57                                Nail(kg) 3 in         3      100.0       300.0 2025-10-17
58                            Gas for Generator         1      435.0       435.0 2025-10-19
59                                Nail(kg) 3 in         7      100.0       700.0 2025-10-20
60                                Nail(kg) 2 in         3      100.0       300.0 2025-10-20
61                            Momo Waggeh's Bed         1     2000.0      2000.0 2025-10-20
62             Contractor Momodou Njaye Payment         1    10000.0     10000.0 2025-10-20
63                            Gas for Generator         1      440.0       440.0 2025-10-23
64                           Wheelbarrow Repair         1     1500.0      1500.0 2025-10-23
65                                       Cement        25      480.0     12000.0 2025-10-24
66                             Cement Transport        25       20.0       500.0 2025-10-24
67                           Pilar Mold Rental          3     2000.0      6000.0 2025-10-24
68                                Tank Removal          1     5000.0      5000.0 2025-10-24
69                            Gas for Generator         1      500.0       500.0 2025-10-26
70                                       Cement        25      480.0     12000.0 2025-10-27
71                             Cement Transport        25       20.0       500.0 2025-10-27
72                                 Plywood 12mm         4     1725.0      6900.0 2025-10-27
73                                   Cardboard          3      350.0      1050.0 2025-10-27
74                                  1 by 2 wood         4      100.0       400.0 2025-10-27
75                Plywood & cardboard Transport         1      400.0       400.0 2025-10-27
76                             Generator Repair         1     1650.0      1650.0 2025-10-27
77                           six Pilar Iron Man         1     2500.0      2500.0 2025-10-28
78                        Momo Waggeh's Salary          1     4000.0      4000.0 2025-10-31
79   Workers Bathroom Plumbing Materials +Trans         1     5975.0      5975.0 2025-11-01
80                            Four Pillars Mold         3     1000.0      3000.0 2025-11-01
81                 Four Pillars Mold Transport          2      500.0      1000.0 2025-11-01
82                                  1 by 2 wood         5      100.0       500.0 2025-11-03
83                                Nail(kg) 3 in         1      100.0       100.0 2025-11-03
84                                  1 by 6 Wood         2      400.0       800.0 2025-11-04
85                                Nail(kg) 3 in         3      100.0       300.0 2025-11-04
86                  Bathroom Plumbing Materials         1      500.0       500.0 2025-11-04
87                                Borehole Pile         1     2050.0      2050.0 2025-11-04
88                                       Cement        25      480.0     12000.0 2025-11-04
89                             Cement Transport        25       20.0       500.0 2025-11-04
90                          Joins For Plumbing          2      150.0       300.0 2025-11-04
91                      Tube for Plumbing(15mm)        15       50.0       750.0 2025-11-04
92                                Soft Plywood          1     1000.0      1000.0 2025-11-04
93                           Plywood Transport          1      400.0       400.0 2025-11-04
94                                 Plumber Fees         1     4500.0      4500.0 2025-11-05
95                                    Wave Fees         1      120.0       120.0 2025-11-05
96                                    Scarfing          3      450.0      1350.0 2025-11-06
97                          Scarfing Transport          1      400.0       400.0 2025-11-06
98                                  1 by 2 wood         5      100.0       500.0 2025-11-07
99                       1 by 2 wood Transport          1      300.0       300.0 2025-11-07
100    Bathroom Manual and plastering the floor         1     2500.0      2500.0 2025-11-07
101                          Pilar Mold Rental          4     2000.0      8000.0 2025-11-11
102                          Balcony Extension          1     2000.0      2000.0 2025-11-14
103            Contractor Momodou Njaye Payment         1    10000.0     10000.0 2025-11-14
104                              Bathroom Door          1     2600.0      2600.0 2025-11-15
105                                 Ali Salary          1     5500.0      5500.0 2025-11-15
106                        Scarfing + Acro Jack         1     2994.0      2994.0 2025-11-17
107             Scarfing + Acro Jack Transport          1     1000.0      1000.0 2025-11-17
108                            Miss Calculation         1      500.0       500.0 2025-12-17

In [118]:
sd = secondfloor_const.loc[55:]

In [124]:
sd['date'] = pd.to_datetime(sd['date'])

In [137]:
sd['date'] = sd['date'].astype(str)

In [149]:
 secondfloor_const.loc[55:, 'date'] = sd['date']

In [154]:
sd1 = secondfloor_const.loc[:54]

In [162]:
sd1['date'] = sd1['date'].astype(str)

In [ ]:
#sd1['date'] = pd.to_datetime(sd1['date'])

In [165]:
secondfloor_const.loc[:54, 'date'] = sd1['date']

In [98]:
#secondfloor_const.at[55, 'date'] = pd.to_datetime(secondfloor_const.at[55, 'date'])

In [168]:
secondfloor_const['date'] = pd.to_datetime(secondfloor_const['date'])

In [203]:
secondfloor_const.info()

<class 'pandas.DataFrame'>
Index: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        109 non-null    str
 1   quantity    109 non-null    int64
 2   unit_cost   109 non-null    float64
 3   total_cost  109 non-null    float64
 4   date        109 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 9.2 KB

In [171]:
secondfloor_const.columns

Index(['item', 'quality ', 'unit price(d)', 'total cost(d)', 'date'], dtype='str')

In [174]:
secondfloor_const.rename(columns={'quality ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [181]:
secondfloor_const.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [188]:
secondfloor_const

                                item  quantity unit_cost total_cost       date
0            Rope for Lifting Bricks       1.0    400.00     400.00 2025-08-28
1                      Iron Rod 12mm      70.0    550.00  38,500.00 2025-08-30
2                       Iron Rod 6mm      40.0    150.00   6,000.00 2025-08-30
3                        Wheelbarrow       1.0  2,800.00   2,800.00 2025-08-30
4                 Binding Wire(Roll)       2.0    500.00   1,000.00 2025-08-30
..                               ...       ...       ...        ...        ...
104                   Bathroom Door        1.0  2,600.00   2,600.00 2025-11-15
105                      Ali Salary        1.0  5,500.00   5,500.00 2025-11-15
106             Scarfing + Acro Jack       1.0  2,994.00   2,994.00 2025-11-17
107  Scarfing + Acro Jack Transport        1.0  1,000.00   1,000.00 2025-11-17
108                 Miss Calculation       1.0    500.00     500.00 2025-12-17

[109 rows x 5 columns]

In [196]:
secondfloor_const['total_cost'] = pd.to_numeric(secondfloor_const['total_cost'].str.replace(',', '', regex=False), errors='coerce')

In [201]:
secondfloor_const.info()

<class 'pandas.DataFrame'>
Index: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        109 non-null    str
 1   quantity    109 non-null    int64
 2   unit_cost   109 non-null    float64
 3   total_cost  109 non-null    float64
 4   date        109 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 9.2 KB

In [200]:
secondfloor_const['quantity'] = secondfloor_const['quantity'].astype('int')

In [206]:
secondfloor_const['sub_category'] = 'Construction'
secondfloor_const['category'] = '2nd Floor'

In [208]:
secondfloor_const.tail(25)

,item,quantity,unit_cost,total_cost,date,sub_category,category
84,1 by 6 Wood,2,400.0,800.0,2025-11-04,Construction,2nd Floor
85,Nail(kg) 3 in,3,100.0,300.0,2025-11-04,Construction,2nd Floor
86,Bathroom Plumbing Materials,1,500.0,500.0,2025-11-04,Construction,2nd Floor
87,Borehole Pile,1,2050.0,2050.0,2025-11-04,Construction,2nd Floor
88,Cement,25,480.0,12000.0,2025-11-04,Construction,2nd Floor
89,Cement Transport,25,20.0,500.0,2025-11-04,Construction,2nd Floor
90,Joins For Plumbing,2,150.0,300.0,2025-11-04,Construction,2nd Floor
91,Tube for Plumbing(15mm),15,50.0,750.0,2025-11-04,Construction,2nd Floor
92,Soft Plywood,1,1000.0,1000.0,2025-11-04,Construction,2nd Floor
93,Plywood Transport,1,400.0,400.0,2025-11-04,Construction,2nd Floor
94,Plumber Fees,1,4500.0,4500.0,2025-11-05,Construction,2nd Floor
95,Wave Fees,1,120.0,120.0,2025-11-05,Construction,2nd Floor
96,Scarfing,3,450.0,1350.0,2025-11-06,Construction,2nd Floor
97,Scarfing Transport,1,400.0,400.0,2025-11-06,Construction,2nd Floor
98,1 by 2 wood,5,100.0,500.0,2025-11-07,Construction,2nd Floor
99,1 by 2 wood Transport,1,300.0,300.0,2025-11-07,Construction,2nd Floor
100,Bathroom Manual and plastering the floor,1,2500.0,2500.0,2025-11-07,Construction,2nd Floor
101,Pilar Mold Rental,4,2000.0,8000.0,2025-11-11,Construction,2nd Floor
102,Balcony Extension,1,2000.0,2000.0,2025-11-14,Construction,2nd Floor
103,Contractor Momodou Njaye Payment,1,10000.0,10000.0,2025-11-14,Construction,2nd Floor
104,Bathroom Door,1,2600.0,2600.0,2025-11-15,Construction,2nd Floor
105,Ali Salary,1,5500.0,5500.0,2025-11-15,Construction,2nd Floor
106,Scarfing + Acro Jack,1,2994.0,2994.0,2025-11-17,Construction,2nd Floor
107,Scarfing + Acro Jack Transport,1,1000.0,1000.0,2025-11-17,Construction,2nd Floor
108,Miss Calculation,1,500.0,500.0,2025-12-17,Construction,2nd Floor

In [209]:
secondfloor_const.to_csv('ParadiseView/out/df_secondfloor_const.csv', index=False)

In [3]:
secondfloor_const = pd.read_csv('ParadiseView/out/df_secondfloor_const.csv')

In [5]:
secondfloor_const.tail()

,item,quantity,unit_cost,total_cost,date,sub_category,category
104,Bathroom Door,1,2600.0,2600.0,2025-11-15,Construction,2nd Floor
105,Ali Salary,1,5500.0,5500.0,2025-11-15,Construction,2nd Floor
106,Scarfing + Acro Jack,1,2994.0,2994.0,2025-11-17,Construction,2nd Floor
107,Scarfing + Acro Jack Transport,1,1000.0,1000.0,2025-11-17,Construction,2nd Floor
108,Miss Calculation,1,500.0,500.0,2025-12-17,Construction,2nd Floor

In [11]:
secondfloor_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   item          109 non-null    str
 1   quantity      109 non-null    int64
 2   unit_cost     109 non-null    float64
 3   total_cost    109 non-null    float64
 4   date          109 non-null    datetime64[us]
 5   sub_category  109 non-null    str
 6   category      109 non-null    str
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.1 KB

In [10]:
secondfloor_const['date'] = pd.to_datetime(secondfloor_const['date'])

In [17]:
secondfloor_const['exchange_rate'] = np.where(secondfloor_const['date'].between('2025-08-26', '2025-09-20'), 73.50, 0)

In [21]:
secondfloor_const['exchange_rate'] = np.where(secondfloor_const['date'].between('2025-09-21', '2025-10-25'), 73.60, secondfloor_const['exchange_rate'])

In [24]:
secondfloor_const['exchange_rate'] = np.where(secondfloor_const['date'].between('2025-10-26', '2025-12-17'), 74.00, secondfloor_const['exchange_rate'])

In [29]:
print(secondfloor_const.to_string())

                                           item  quantity  unit_cost  total_cost       date  sub_category   category  exchange_rate
0                       Rope for Lifting Bricks         1      400.0       400.0 2025-08-28  Construction  2nd Floor           73.5
1                                 Iron Rod 12mm        70      550.0     38500.0 2025-08-30  Construction  2nd Floor           73.5
2                                  Iron Rod 6mm        40      150.0      6000.0 2025-08-30  Construction  2nd Floor           73.5
3                                   Wheelbarrow         1     2800.0      2800.0 2025-08-30  Construction  2nd Floor           73.5
4                            Binding Wire(Roll)         2      500.0      1000.0 2025-08-30  Construction  2nd Floor           73.5
5                            Materials Transpot         1     1000.0      1000.0 2025-08-30  Construction  2nd Floor           73.5
6                                        Cement        50      480.0     24000.0 2025-08-30  Construction  2nd Floor           73.5
7                              Cement Transport        50       20.0      1000.0 2025-08-30  Construction  2nd Floor           73.5
8              Contractor Momodou Njaye Payment         1    90000.0     90000.0 2025-08-30  Construction  2nd Floor           73.5
9                             Gas for Generator         1      530.0       530.0 2025-08-31  Construction  2nd Floor           73.5
10                             Generator Repair         1     1200.0      1200.0 2025-09-05  Construction  2nd Floor           73.5
11                                Sand(10Wheel)         1     8300.0      8300.0 2025-09-06  Construction  2nd Floor           73.5
12             Contractor Momodou Njaye Payment         1   100000.0    100000.0 2025-09-08  Construction  2nd Floor           73.5
13                                       Cement        50      480.0     24000.0 2025-09-10  Construction  2nd Floor           73.5
14                             Cement Transport        50       20.0      1000.0 2025-09-10  Construction  2nd Floor           73.5
15                                  1 by 2 wood        40      100.0      4000.0 2025-09-13  Construction  2nd Floor           73.5
16                           Splitting Plywoods         1      650.0       650.0 2025-09-13  Construction  2nd Floor           73.5
17                           Materials Transpot         1      600.0       600.0 2025-09-13  Construction  2nd Floor           73.5
18                                Nail(kg) 3 in         3      100.0       300.0 2025-09-13  Construction  2nd Floor           73.5
19                                Nail(kg) 3 in         4      100.0       400.0 2025-09-15  Construction  2nd Floor           73.5
20                                       Cement        50      480.0     24000.0 2025-09-16  Construction  2nd Floor           73.5
21                             Cement Transport        50       20.0      1000.0 2025-09-16  Construction  2nd Floor           73.5
22                      Asphalt Stone(19 cubic)         1    95000.0     95000.0 2025-09-17  Construction  2nd Floor           73.5
23                                Iron Rod 12mm        25      540.0     13500.0 2025-09-17  Construction  2nd Floor           73.5
24                                Iron Rod 10mm       280      330.0     92400.0 2025-09-17  Construction  2nd Floor           73.5
25                                 Iron Rod 6mm       125      140.0     17500.0 2025-09-17  Construction  2nd Floor           73.5
26                           Binding Wire(Roll)         3      400.0      1200.0 2025-09-17  Construction  2nd Floor           73.5
27                          Iron Rods Transport         1     3000.0      3000.0 2025-09-17  Construction  2nd Floor           73.5
28                                    Chain(2m)         1      700.0       700.0 2025-09-17  Construction  2nd Floor           73.5
29                                         Lock         1      250.0       250.0 2025-09-17  Construction  2nd Floor           73.5
30                                       1 by 6        10      400.0      4000.0 2025-09-17  Construction  2nd Floor           73.5
31                  1 by 6 & 12mm Rod Transport         1      600.0       600.0 2025-09-17  Construction  2nd Floor           73.5
32                                Nail(kg) 3 in         2      100.0       200.0 2025-09-17  Construction  2nd Floor           73.5
33                                Sand(10Wheel)         1     8300.0      8300.0 2025-09-17  Construction  2nd Floor           73.5
34             Contractor Momodou Njaye Payment         1   100000.0    100000.0 2025-09-21  Construction  2nd Floor           73.6
35                                       Bucket         3      100.0       300.0 2025-09-22  Construction  2nd Floor           73.6
36                           Binding Wire(Roll)         2      500.0      1000.0 2025-09-22  Construction  2nd Floor           73.6
37                                  1 by 2 wood        20      100.0      2000.0 2025-09-24  Construction  2nd Floor           73.6
38               Splitting Rest of the Plywoods         1     1125.0      1125.0 2025-09-24  Construction  2nd Floor           73.6
39                   Plywood & 1 by 2 Transport         1      800.0       800.0 2025-09-24  Construction  2nd Floor           73.6
40                                Nail(kg) 3 in         5      100.0       500.0 2025-09-29  Construction  2nd Floor           73.6
41                                Nail(kg) 2 in         2      100.0       200.0 2025-09-29  Construction  2nd Floor           73.6
42                                Nail(kg) 1 in         2      100.0       200.0 2025-09-29  Construction  2nd Floor           73.6
43                                       Cement        50      480.0     24000.0 2025-09-30  Construction  2nd Floor           73.6
44                             Cement Transport        50       20.0      1000.0 2025-09-30  Construction  2nd Floor           73.6
45                    Momo Waggeh's Sept Salary         1     4000.0      4000.0 2025-09-30  Construction  2nd Floor           73.6
46                            Gas for Generator         1      500.0       500.0 2025-10-01  Construction  2nd Floor           73.6
47             Njaye Extra- Transporting Bricks         1     5000.0      5000.0 2025-10-04  Construction  2nd Floor           73.6
48                            For Bubacarr Faye         1     5000.0      5000.0 2025-10-09  Construction  2nd Floor           73.6
49                                       Cement        50      480.0     24000.0 2025-10-11  Construction  2nd Floor           73.6
50                             Cement Transport        50       20.0      1000.0 2025-10-11  Construction  2nd Floor           73.6
51                            Gas for Generator         1      400.0       400.0 2025-10-13  Construction  2nd Floor           73.6
52                             Generator Repair         1     2700.0      2700.0 2025-10-14  Construction  2nd Floor           73.6
53                          Generator Transport         1      600.0       600.0 2025-10-14  Construction  2nd Floor           73.6
54                           Wheelbarrow Repair         1      800.0       800.0 2025-10-14  Construction  2nd Floor           73.6
55                                Sand(10Wheel)         1     8500.0      8500.0 2025-10-17  Construction  2nd Floor           73.6
56                           Binding Wire(Roll)         1      500.0       500.0 2025-10-17  Construction  2nd Floor           73.6
57                                Nail(kg) 3 in         3      100.0       300.0 2025-10-17  Construction  2nd Floor           73.6
58                            Gas for Generator         1      435.0       435.0 2025-10-19  Construction  2nd Floor           73.6
59                                Nail(kg) 3 in         7      100.0       700.0 2025-10-20  Construction  2nd Floor           73.6
60                                Nail(kg) 2 in         3      100.0       300.0 2025-10-20  Construction  2nd Floor           73.6
61                            Momo Waggeh's Bed         1     2000.0      2000.0 2025-10-20  Construction  2nd Floor           73.6
62             Contractor Momodou Njaye Payment         1    10000.0     10000.0 2025-10-20  Construction  2nd Floor           73.6
63                            Gas for Generator         1      440.0       440.0 2025-10-23  Construction  2nd Floor           73.6
64                           Wheelbarrow Repair         1     1500.0      1500.0 2025-10-23  Construction  2nd Floor           73.6
65                                       Cement        25      480.0     12000.0 2025-10-24  Construction  2nd Floor           73.6
66                             Cement Transport        25       20.0       500.0 2025-10-24  Construction  2nd Floor           73.6
67                           Pilar Mold Rental          3     2000.0      6000.0 2025-10-24  Construction  2nd Floor           73.6
68                                Tank Removal          1     5000.0      5000.0 2025-10-24  Construction  2nd Floor           73.6
69                            Gas for Generator         1      500.0       500.0 2025-10-26  Construction  2nd Floor           74.0
70                                       Cement        25      480.0     12000.0 2025-10-27  Construction  2nd Floor           74.0
71                             Cement Transport        25       20.0       500.0 2025-10-27  Construction  2nd Floor           74.0
72                                 Plywood 12mm         4     1725.0      6900.0 2025-10-27  Construction  2nd Floor           74.0
73                                   Cardboard          3      350.0      1050.0 2025-10-27  Construction  2nd Floor           74.0
74                                  1 by 2 wood         4      100.0       400.0 2025-10-27  Construction  2nd Floor           74.0
75                Plywood & cardboard Transport         1      400.0       400.0 2025-10-27  Construction  2nd Floor           74.0
76                             Generator Repair         1     1650.0      1650.0 2025-10-27  Construction  2nd Floor           74.0
77                           six Pilar Iron Man         1     2500.0      2500.0 2025-10-28  Construction  2nd Floor           74.0
78                        Momo Waggeh's Salary          1     4000.0      4000.0 2025-10-31  Construction  2nd Floor           74.0
79   Workers Bathroom Plumbing Materials +Trans         1     5975.0      5975.0 2025-11-01  Construction  2nd Floor           74.0
80                            Four Pillars Mold         3     1000.0      3000.0 2025-11-01  Construction  2nd Floor           74.0
81                 Four Pillars Mold Transport          2      500.0      1000.0 2025-11-01  Construction  2nd Floor           74.0
82                                  1 by 2 wood         5      100.0       500.0 2025-11-03  Construction  2nd Floor           74.0
83                                Nail(kg) 3 in         1      100.0       100.0 2025-11-03  Construction  2nd Floor           74.0
84                                  1 by 6 Wood         2      400.0       800.0 2025-11-04  Construction  2nd Floor           74.0
85                                Nail(kg) 3 in         3      100.0       300.0 2025-11-04  Construction  2nd Floor           74.0
86                  Bathroom Plumbing Materials         1      500.0       500.0 2025-11-04  Construction  2nd Floor           74.0
87                                Borehole Pile         1     2050.0      2050.0 2025-11-04  Construction  2nd Floor           74.0
88                                       Cement        25      480.0     12000.0 2025-11-04  Construction  2nd Floor           74.0
89                             Cement Transport        25       20.0       500.0 2025-11-04  Construction  2nd Floor           74.0
90                          Joins For Plumbing          2      150.0       300.0 2025-11-04  Construction  2nd Floor           74.0
91                      Tube for Plumbing(15mm)        15       50.0       750.0 2025-11-04  Construction  2nd Floor           74.0
92                                Soft Plywood          1     1000.0      1000.0 2025-11-04  Construction  2nd Floor           74.0
93                           Plywood Transport          1      400.0       400.0 2025-11-04  Construction  2nd Floor           74.0
94                                 Plumber Fees         1     4500.0      4500.0 2025-11-05  Construction  2nd Floor           74.0
95                                    Wave Fees         1      120.0       120.0 2025-11-05  Construction  2nd Floor           74.0
96                                    Scarfing          3      450.0      1350.0 2025-11-06  Construction  2nd Floor           74.0
97                          Scarfing Transport          1      400.0       400.0 2025-11-06  Construction  2nd Floor           74.0
98                                  1 by 2 wood         5      100.0       500.0 2025-11-07  Construction  2nd Floor           74.0
99                       1 by 2 wood Transport          1      300.0       300.0 2025-11-07  Construction  2nd Floor           74.0
100    Bathroom Manual and plastering the floor         1     2500.0      2500.0 2025-11-07  Construction  2nd Floor           74.0
101                          Pilar Mold Rental          4     2000.0      8000.0 2025-11-11  Construction  2nd Floor           74.0
102                          Balcony Extension          1     2000.0      2000.0 2025-11-14  Construction  2nd Floor           74.0
103            Contractor Momodou Njaye Payment         1    10000.0     10000.0 2025-11-14  Construction  2nd Floor           74.0
104                              Bathroom Door          1     2600.0      2600.0 2025-11-15  Construction  2nd Floor           74.0
105                                 Ali Salary          1     5500.0      5500.0 2025-11-15  Construction  2nd Floor           74.0
106                        Scarfing + Acro Jack         1     2994.0      2994.0 2025-11-17  Construction  2nd Floor           74.0
107             Scarfing + Acro Jack Transport          1     1000.0      1000.0 2025-11-17  Construction  2nd Floor           74.0
108                            Miss Calculation         1      500.0       500.0 2025-12-17  Construction  2nd Floor           74.0

In [30]:
secondfloor_const.to_csv('ParadiseView/out/df_secondfloor_const.csv', index=False)

In [31]:
secondfloor_const.to_csv('ParadiseView/out/df_secondfloor_const.csv', index=False)

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Rope for Lifting Bricks,1,400.0,400.0,2025-08-28,Construction,2nd Floor,73.5
1,Iron Rod 12mm,70,550.0,38500.0,2025-08-30,Construction,2nd Floor,73.5
2,Iron Rod 6mm,40,150.0,6000.0,2025-08-30,Construction,2nd Floor,73.5
3,Wheelbarrow,1,2800.0,2800.0,2025-08-30,Construction,2nd Floor,73.5
4,Binding Wire(Roll),2,500.0,1000.0,2025-08-30,Construction,2nd Floor,73.5
...,...,...,...,...,...,...,...,...
104,Bathroom Door,1,2600.0,2600.0,2025-11-15,Construction,2nd Floor,74.0
105,Ali Salary,1,5500.0,5500.0,2025-11-15,Construction,2nd Floor,74.0
106,Scarfing + Acro Jack,1,2994.0,2994.0,2025-11-17,Construction,2nd Floor,74.0
107,Scarfing + Acro Jack Transport,1,1000.0,1000.0,2025-11-17,Construction,2nd Floor,74.0
108,Miss Calculation,1,500.0,500.0,2025-12-17,Construction,2nd Floor,74.0