In [1]:
import numpy as np
import pandas as pd

In [16]:
secondfloor_roof = pd.read_csv('ParadiseView/Paradise View/2nd Floor Construction Roof Concreting.csv',)

In [17]:
secondfloor_roof

,ITEM,QUALITY,UNIT PRICE(D),TOTAL COST(D),DATE,Unnamed: 5
0,1/2 wood,100.0,100,"10,000",12/05/2025,NaN
1,1/2 Wood Transport,1.0,"1,000","1,000",12/05/2025,NaN
2,Concrete Nail 2 1/2 in,5.0,200,"1,000",12/05/2025,NaN
3,Concrete Nail 2 in,45.0,30,"1,350",12/05/2025,NaN
4,1/2 Wood,35.0,100,"3,500",12/06/2025,NaN
...,...,...,...,...,...,...
114,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN
116,TOTAL AMOUNT SPENT,NaN,NaN,"1,017,906.00",NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN
118,REMAINING BALANCE IN HAND,NaN,NaN,0.00,NaN,NaN

In [18]:
secondfloor_roof.drop(columns='Unnamed: 5', inplace=True)

In [33]:
secondfloor_roof.drop(secondfloor_roof.loc[86:].index)

,item,quantity,unit_cost,total_cost,date
0,1/2 wood,100.0,100,"10,000",12/05/2025
1,1/2 Wood Transport,1.0,"1,000","1,000",12/05/2025
2,Concrete Nail 2 1/2 in,5.0,200,"1,000",12/05/2025
3,Concrete Nail 2 in,45.0,30,"1,350",12/05/2025
4,1/2 Wood,35.0,100,"3,500",12/06/2025
...,...,...,...,...,...
81,2/3 Wood Rental 2Days Extension,375.0,5,"5,625",01/18/2026
82,Acrojack Rental 2Days Extension,475.0,2.5,"3,565",01/18/2026
83,Carpenter Sana Payment,1.0,"1,500","1,500",01/20/2026
84,Bubacarr Faye Payment,1.0,"12,000","12,000",01/22/2026
85,Ali moving the Woods to the Room,1.0,481,481,01/22/2026

In [24]:
secondfloor_roof.columns = secondfloor_roof.columns.str.lower()

In [25]:
secondfloor_roof.columns

Index(['item', 'quality ', 'unit price(d)', 'total cost(d)', 'date'], dtype='str')

In [27]:
secondfloor_roof.rename(columns={'quality ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [28]:
secondfloor_roof.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [29]:
secondfloor_roof[secondfloor_roof['item'] == 'Sand']

    item  quantity unit_cost total_cost        date
42  Sand       3.0     8,000     24,000  12/26/2025

In [30]:
secondfloor_roof.loc[42, ['quantity', 'total_cost']] = [2.0, '16000']

In [55]:
#secondfloor_roof.drop(columns=['qauntity', 'qantity'], inplace=True)

In [23]:
#secondfloor_roof.columns = secondfloor_roof.columns.str.lower

In [35]:
secondfloor_roof.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'date'], dtype='str')

In [42]:
secondfloor_roof.drop(secondfloor_roof.loc[86:].index, inplace =True)

In [43]:
print(secondfloor_roof.to_string())

                                     item  quantity unit_cost total_cost        date
0                                1/2 wood     100.0       100     10,000  12/05/2025
1                     1/2 Wood Transport        1.0     1,000      1,000  12/05/2025
2                  Concrete Nail 2 1/2 in       5.0       200      1,000  12/05/2025
3                      Concrete Nail 2 in      45.0        30      1,350  12/05/2025
4                                1/2 Wood      35.0       100      3,500  12/06/2025
5                                1/6 Wood       2.0       350        700  12/06/2025
6                         Wood Transport        1.0       500        500  12/06/2025
7                 Carpenter Sana Payment        1.0    15,000     15,000  12/06/2025
8                                2/3 Wood     350.0         5     52,500  12/13/2025
9                                Nail(pkg      17.0       100      1,700  12/13/2025
10                   Materials Transport        4.0     2,500     10,000  12/13/2025
11                Carpenter Sana Payment        1.0     5,000      5,000  12/23/2025
12                              Acrojack      400.0       2.5     27,000  12/15/2025
13                      Generator Repair        1.0       600        600  12/17/2025
14                   Generator Transport        2.0       300        600  12/17/2025
15                     Gas for Generator        1.0       500        500  12/17/2025
16                        Plywood Rental       65.0        20     32,500  12/18/2025
17                               Nail(kg)       8.0       100        800  12/20/2025
18                           Plywood 12mm      30.0     1,700     51,000   12/22/225
19                              Acrojack       50.0       2.5        400  12/22/2025
20                   Materials Transport        1.0     2,000      2,000  12/22/2025
21                          Iron Rod 10mm     500.0       330    165,000  12/23/2025
22                          Iron Rod 12mm      30.0       500     15,000  12/23/2025
23                           Iron Rod 6mm      35.0       130      4,550  12/23/2025
24                           Binding Wire       3.0       400      1,200  12/23/2025
25                   Materials Transport        1.0     5,000      5,000  12/23/2025
26                Carpenter Sana Payment        1.0     5,000      5,000  12/23/2025
27                       Iron Man Payment       1.0    11,000     11,000  12/23/2025
28                      Wave Transfer Fee       1.0       110        110  12/23/2025
29                           Plywood 12mm      12.0     1,700     20,400  12/24/2025
30                     Plywood Transport        1.0       500        500  12/24/2025
31                              10m Rope        1.0       500        500  12/24/2025
32                                   Poly       1.0       200        200  12/24/2025
33                    Plumbing Materials        1.0    19,132     19,000  12/26/2025
34                   Materials Transport        1.0       300        300  12/26/2025
35                           Plywood 12mm      10.0     1,700     17,000  12/26/2025
36                             Cardboard        2.0       400        800  12/26/2025
37                   Materials Transport        1.0       300        300  12/26/2025
38                   Electrical Materials       1.0    12,475     12,475  12/26/2025
39         Electrical Material Transport        1.0       300        300  12/26/2025
40                             Wash Stone       3.0    14,000     42,000  12/26/2025
41                           Asphalt 19cu       1.0    94,500     94,500  12/26/2025
42                                   Sand       2.0     8,000      16000  12/26/2025
43                           Buba Tunkara       1.0     8,000      8,000  12/26/2025
44                          Nail(Box) 2in      25.0        30        750  12/27/2025
45                                  Nails       1.0     1,200      1,200  12/27/2025
46                              Acrojack       25.0       2.5      1,000  12/27/2025
47                               2/3 Wood      30.0         5      2,400  12/27/2025
48                   Materials Transport        1.0       600        600  12/27/2025
49                               1/6 Wood      18.0       375      6,750  12/27/2025
50                               1/2 Wood       2.0       100        200  12/27/2025
51                    Acrojack Transport        1.0       350        350  12/27/2025
52                           Electrician        1.0     9,000      9,000  12/27/2025
53         Electrical Material Transport        2.0       500      1,000  12/28/2025
54                   Electrical Material        1.0     3,100      3,100  12/29/2025
55         Electrical Material Transport        1.0       300        300  12/29/2025
56                     Binding Wire(Roll)       1.0       500        500  12/29/2025
57                 Adjusting the Pillars        1.0     1,000      1,000  12/29/2025
58                       Iron Man Payment       1.0    11,000     11,000  12/29/2025
59                               Plumber        1.0    16,000     16,000  12/29/2025
60                   Ali Clearly pathway        1.0     1,000      1,000  12/29/2025
61                                Cement      364.0       480    174,720  12/29/2025
62                      Cement Transport      364.0        20      7,280  12/29/2025
63                               1/2 Wood      10.0       100      1,000  12/30/2025
64                    1/2 Wood Transport        1.0       500        500  12/30/2025
65        1/12 Wood Rental and Transport        3.0       400        400  12/30/2025
66                 Supervising Contractor       1.0     1,500      1,500  12/30/2025
67                         Stone(6 wheel)       1.0     8,000      8,000  12/30/2025
68                    Stone(6 wheel mini)       1.0     6,500      6,500  12/30/2025
69              Gas for Generator and Tea       1.0     1,000      1,000  12/30/2025
70                           Electrician        1.0       300        300  12/30/2025
71                           Concrete Man       1.0    40,000     40,000  12/30/2025
72                       Food for Workers       1.0     2,000      2,000  12/30/2025
73                          Bubacarr Faye       1.0     5,000      5,000  01/31/2026
74                     Gas for Generator        1.0       500        500         NaN
75                     Gas for Generator        1.0       500        500         NaN
76                             Ali Salary       1.0     5,500      5,500  01/07/2026
77                   Ali Watering Rooftop       1.0     2,000      2,000  01/07/2026
78  Ali Bringing Down Woods and Acrojacks       1.0     3,500      3,500  01/15/2026
79              Roof Materials Transport        1.0    10,000     10,000  01/15/2026
80        Plywood Rental 2Days Extension       60.0        20      3,600  01/18/2026
81       2/3 Wood Rental 2Days Extension      375.0         5      5,625  01/18/2026
82       Acrojack Rental 2Days Extension      475.0       2.5      3,565  01/18/2026
83                Carpenter Sana Payment        1.0     1,500      1,500  01/20/2026
84                 Bubacarr Faye Payment        1.0    12,000     12,000  01/22/2026
85      Ali moving the Woods  to the Room       1.0       481        481  01/22/2026

In [44]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        86 non-null     str
 1   quantity    86 non-null     float64
 2   unit_cost   86 non-null     str
 3   total_cost  86 non-null     str
 4   date        84 non-null     str
dtypes: float64(1), str(4)
memory usage: 3.5 KB

In [77]:
secondfloor_roof.loc[secondfloor_roof['date'].isna()]

Empty DataFrame
Columns: [item, quantity, unit_cost, total_cost, date]
Index: []

In [76]:
secondfloor_roof.loc[[74, 75], 'date'] = '12/31/2026'

In [79]:
secondfloor_roof.loc[[74, 75]]

                  item  quantity unit_cost total_cost        date
74  Gas for Generator        1.0       500        500  12/31/2026
75  Gas for Generator        1.0       500        500  12/31/2026

In [86]:
print(secondfloor_roof.to_string())

                                     item  quantity unit_cost total_cost        date
0                                1/2 wood     100.0       100     10,000  12/05/2025
1                     1/2 Wood Transport        1.0     1,000      1,000  12/05/2025
2                  Concrete Nail 2 1/2 in       5.0       200      1,000  12/05/2025
3                      Concrete Nail 2 in      45.0        30      1,350  12/05/2025
4                                1/2 Wood      35.0       100      3,500  12/06/2025
5                                1/6 Wood       2.0       350        700  12/06/2025
6                         Wood Transport        1.0       500        500  12/06/2025
7                 Carpenter Sana Payment        1.0    15,000     15,000  12/06/2025
8                                2/3 Wood     350.0         5     52,500  12/13/2025
9                                Nail(pkg      17.0       100      1,700  12/13/2025
10                   Materials Transport        4.0     2,500     10,000  12/13/2025
11                Carpenter Sana Payment        1.0     5,000      5,000  12/23/2025
12                              Acrojack      400.0       2.5     27,000  12/15/2025
13                      Generator Repair        1.0       600        600  12/17/2025
14                   Generator Transport        2.0       300        600  12/17/2025
15                     Gas for Generator        1.0       500        500  12/17/2025
16                        Plywood Rental       65.0        20     32,500  12/18/2025
17                               Nail(kg)       8.0       100        800  12/20/2025
18                           Plywood 12mm      30.0     1,700     51,000  12/22/2025
19                              Acrojack       50.0       2.5        400  12/22/2025
20                   Materials Transport        1.0     2,000      2,000  12/22/2025
21                          Iron Rod 10mm     500.0       330    165,000  12/23/2025
22                          Iron Rod 12mm      30.0       500     15,000  12/23/2025
23                           Iron Rod 6mm      35.0       130      4,550  12/23/2025
24                           Binding Wire       3.0       400      1,200  12/23/2025
25                   Materials Transport        1.0     5,000      5,000  12/23/2025
26                Carpenter Sana Payment        1.0     5,000      5,000  12/23/2025
27                       Iron Man Payment       1.0    11,000     11,000  12/23/2025
28                      Wave Transfer Fee       1.0       110        110  12/23/2025
29                           Plywood 12mm      12.0     1,700     20,400  12/24/2025
30                     Plywood Transport        1.0       500        500  12/24/2025
31                              10m Rope        1.0       500        500  12/24/2025
32                                   Poly       1.0       200        200  12/24/2025
33                    Plumbing Materials        1.0    19,132     19,000  12/26/2025
34                   Materials Transport        1.0       300        300  12/26/2025
35                           Plywood 12mm      10.0     1,700     17,000  12/26/2025
36                             Cardboard        2.0       400        800  12/26/2025
37                   Materials Transport        1.0       300        300  12/26/2025
38                   Electrical Materials       1.0    12,475     12,475  12/26/2025
39         Electrical Material Transport        1.0       300        300  12/26/2025
40                             Wash Stone       3.0    14,000     42,000  12/26/2025
41                           Asphalt 19cu       1.0    94,500     94,500  12/26/2025
42                                   Sand       2.0     8,000      16000  12/26/2025
43                           Buba Tunkara       1.0     8,000      8,000  12/26/2025
44                          Nail(Box) 2in      25.0        30        750  12/27/2025
45                                  Nails       1.0     1,200      1,200  12/27/2025
46                              Acrojack       25.0       2.5      1,000  12/27/2025
47                               2/3 Wood      30.0         5      2,400  12/27/2025
48                   Materials Transport        1.0       600        600  12/27/2025
49                               1/6 Wood      18.0       375      6,750  12/27/2025
50                               1/2 Wood       2.0       100        200  12/27/2025
51                    Acrojack Transport        1.0       350        350  12/27/2025
52                           Electrician        1.0     9,000      9,000  12/27/2025
53         Electrical Material Transport        2.0       500      1,000  12/28/2025
54                   Electrical Material        1.0     3,100      3,100  12/29/2025
55         Electrical Material Transport        1.0       300        300  12/29/2025
56                     Binding Wire(Roll)       1.0       500        500  12/29/2025
57                 Adjusting the Pillars        1.0     1,000      1,000  12/29/2025
58                       Iron Man Payment       1.0    11,000     11,000  12/29/2025
59                               Plumber        1.0    16,000     16,000  12/29/2025
60                   Ali Clearly pathway        1.0     1,000      1,000  12/29/2025
61                                Cement      364.0       480    174,720  12/29/2025
62                      Cement Transport      364.0        20      7,280  12/29/2025
63                               1/2 Wood      10.0       100      1,000  12/30/2025
64                    1/2 Wood Transport        1.0       500        500  12/30/2025
65        1/12 Wood Rental and Transport        3.0       400        400  12/30/2025
66                 Supervising Contractor       1.0     1,500      1,500  12/30/2025
67                         Stone(6 wheel)       1.0     8,000      8,000  12/30/2025
68                    Stone(6 wheel mini)       1.0     6,500      6,500  12/30/2025
69              Gas for Generator and Tea       1.0     1,000      1,000  12/30/2025
70                           Electrician        1.0       300        300  12/30/2025
71                           Concrete Man       1.0    40,000     40,000  12/30/2025
72                       Food for Workers       1.0     2,000      2,000  12/30/2025
73                          Bubacarr Faye       1.0     5,000      5,000  01/31/2026
74                     Gas for Generator        1.0       500        500  12/31/2026
75                     Gas for Generator        1.0       500        500  12/31/2026
76                             Ali Salary       1.0     5,500      5,500  01/07/2026
77                   Ali Watering Rooftop       1.0     2,000      2,000  01/07/2026
78  Ali Bringing Down Woods and Acrojacks       1.0     3,500      3,500  01/15/2026
79              Roof Materials Transport        1.0    10,000     10,000  01/15/2026
80        Plywood Rental 2Days Extension       60.0        20      3,600  01/18/2026
81       2/3 Wood Rental 2Days Extension      375.0         5      5,625  01/18/2026
82       Acrojack Rental 2Days Extension      475.0       2.5      3,565  01/18/2026
83                Carpenter Sana Payment        1.0     1,500      1,500  01/20/2026
84                 Bubacarr Faye Payment        1.0    12,000     12,000  01/22/2026
85      Ali moving the Woods  to the Room       1.0       481        481  01/22/2026

In [85]:
secondfloor_roof.loc[18, 'date'] = '12/22/2025'

In [87]:
secondfloor_roof['date'] = pd.to_datetime(secondfloor_roof['date'])

In [88]:
secondfloor_roof['date'].info()

<class 'pandas.Series'>
RangeIndex: 86 entries, 0 to 85
Series name: date
Non-Null Count  Dtype
--------------  -----
86 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 820.0 bytes

In [101]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        86 non-null     str
 1   quantity    86 non-null     float64
 2   unit_cost   86 non-null     str
 3   total_cost  86 non-null     str
 4   date        86 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 3.5 KB

In [103]:
secondfloor_roof.to_csv('ParadiseView/out/df_secondfloor_roof.csv', index=False)

In [2]:
secondfloor_roof = pd.read_csv('ParadiseView/out/df_secondfloor_roof.csv')

In [3]:
secondfloor_roof

,item,quantity,unit_cost,total_cost,date
0,1/2 wood,100.0,100,"10,000",2025-12-05
1,1/2 Wood Transport,1.0,"1,000","1,000",2025-12-05
2,Concrete Nail 2 1/2 in,5.0,200,"1,000",2025-12-05
3,Concrete Nail 2 in,45.0,30,"1,350",2025-12-05
4,1/2 Wood,35.0,100,"3,500",2025-12-06
...,...,...,...,...,...
81,2/3 Wood Rental 2Days Extension,375.0,5,"5,625",2026-01-18
82,Acrojack Rental 2Days Extension,475.0,2.5,"3,565",2026-01-18
83,Carpenter Sana Payment,1.0,"1,500","1,500",2026-01-20
84,Bubacarr Faye Payment,1.0,"12,000","12,000",2026-01-22
85,Ali moving the Woods to the Room,1.0,481,481,2026-01-22

In [4]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        86 non-null     str
 1   quantity    86 non-null     float64
 2   unit_cost   86 non-null     str
 3   total_cost  86 non-null     str
 4   date        86 non-null     str
dtypes: float64(1), str(4)
memory usage: 3.5 KB

In [14]:
secondfloor_roof['unit_cost'] = secondfloor_roof['unit_cost'].str.replace(",", "").astype('float64')

In [15]:
secondfloor_roof['total_cost'] = secondfloor_roof['total_cost'].str.replace(',', '').astype('float64')

In [16]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        86 non-null     str
 1   quantity    86 non-null     float64
 2   unit_cost   86 non-null     float64
 3   total_cost  86 non-null     float64
 4   date        86 non-null     str
dtypes: float64(3), str(2)
memory usage: 3.5 KB

In [18]:
secondfloor_roof['date'] = pd.to_datetime(secondfloor_roof['date'])

In [19]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item        86 non-null     str
 1   quantity    86 non-null     float64
 2   unit_cost   86 non-null     float64
 3   total_cost  86 non-null     float64
 4   date        86 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 3.5 KB

In [21]:
secondfloor_roof['sub_category'] = 'Roof Concreting'
secondfloor_roof['category'] = '2nd Floor'

In [23]:
secondfloor_roof.to_csv('ParadiseView/out/df_secondfloor_roof.csv', index=False)

In [76]:
secondfloor_roof = pd.read_csv('ParadiseView/out/df_secondfloor_roof.csv')

In [77]:
print(secondfloor_roof.to_string())

                                     item  quantity  unit_cost  total_cost        date     sub_category   category
0                                1/2 wood     100.0      100.0     10000.0  2025-12-05  Roof Conrecting  2nd Floor
1                     1/2 Wood Transport        1.0     1000.0      1000.0  2025-12-05  Roof Conrecting  2nd Floor
2                  Concrete Nail 2 1/2 in       5.0      200.0      1000.0  2025-12-05  Roof Conrecting  2nd Floor
3                      Concrete Nail 2 in      45.0       30.0      1350.0  2025-12-05  Roof Conrecting  2nd Floor
4                                1/2 Wood      35.0      100.0      3500.0  2025-12-06  Roof Conrecting  2nd Floor
5                                1/6 Wood       2.0      350.0       700.0  2025-12-06  Roof Conrecting  2nd Floor
6                         Wood Transport        1.0      500.0       500.0  2025-12-06  Roof Conrecting  2nd Floor
7                 Carpenter Sana Payment        1.0    15000.0     15000.0  2025-12-06  Roof Conrecting  2nd Floor
8                                2/3 Wood     350.0        5.0     52500.0  2025-12-13  Roof Conrecting  2nd Floor
9                                Nail(pkg      17.0      100.0      1700.0  2025-12-13  Roof Conrecting  2nd Floor
10                   Materials Transport        4.0     2500.0     10000.0  2025-12-13  Roof Conrecting  2nd Floor
11                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Conrecting  2nd Floor
12                              Acrojack      400.0        2.5     27000.0  2025-12-15  Roof Conrecting  2nd Floor
13                      Generator Repair        1.0      600.0       600.0  2025-12-17  Roof Conrecting  2nd Floor
14                   Generator Transport        2.0      300.0       600.0  2025-12-17  Roof Conrecting  2nd Floor
15                     Gas for Generator        1.0      500.0       500.0  2025-12-17  Roof Conrecting  2nd Floor
16                        Plywood Rental       65.0       20.0     32500.0  2025-12-18  Roof Conrecting  2nd Floor
17                               Nail(kg)       8.0      100.0       800.0  2025-12-20  Roof Conrecting  2nd Floor
18                           Plywood 12mm      30.0     1700.0     51000.0  2025-12-22  Roof Conrecting  2nd Floor
19                              Acrojack       50.0        2.5       400.0  2025-12-22  Roof Conrecting  2nd Floor
20                   Materials Transport        1.0     2000.0      2000.0  2025-12-22  Roof Conrecting  2nd Floor
21                          Iron Rod 10mm     500.0      330.0    165000.0  2025-12-23  Roof Conrecting  2nd Floor
22                          Iron Rod 12mm      30.0      500.0     15000.0  2025-12-23  Roof Conrecting  2nd Floor
23                           Iron Rod 6mm      35.0      130.0      4550.0  2025-12-23  Roof Conrecting  2nd Floor
24                           Binding Wire       3.0      400.0      1200.0  2025-12-23  Roof Conrecting  2nd Floor
25                   Materials Transport        1.0     5000.0      5000.0  2025-12-23  Roof Conrecting  2nd Floor
26                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Conrecting  2nd Floor
27                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-23  Roof Conrecting  2nd Floor
28                      Wave Transfer Fee       1.0      110.0       110.0  2025-12-23  Roof Conrecting  2nd Floor
29                           Plywood 12mm      12.0     1700.0     20400.0  2025-12-24  Roof Conrecting  2nd Floor
30                     Plywood Transport        1.0      500.0       500.0  2025-12-24  Roof Conrecting  2nd Floor
31                              10m Rope        1.0      500.0       500.0  2025-12-24  Roof Conrecting  2nd Floor
32                                   Poly       1.0      200.0       200.0  2025-12-24  Roof Conrecting  2nd Floor
33                    Plumbing Materials        1.0    19132.0     19000.0  2025-12-26  Roof Conrecting  2nd Floor
34                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Conrecting  2nd Floor
35                           Plywood 12mm      10.0     1700.0     17000.0  2025-12-26  Roof Conrecting  2nd Floor
36                             Cardboard        2.0      400.0       800.0  2025-12-26  Roof Conrecting  2nd Floor
37                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Conrecting  2nd Floor
38                   Electrical Materials       1.0    12475.0     12475.0  2025-12-26  Roof Conrecting  2nd Floor
39         Electrical Material Transport        1.0      300.0       300.0  2025-12-26  Roof Conrecting  2nd Floor
40                             Wash Stone       3.0    14000.0     42000.0  2025-12-26  Roof Conrecting  2nd Floor
41                           Asphalt 19cu       1.0    94500.0     94500.0  2025-12-26  Roof Conrecting  2nd Floor
42                                   Sand       2.0     8000.0     16000.0  2025-12-26  Roof Conrecting  2nd Floor
43                           Buba Tunkara       1.0     8000.0      8000.0  2025-12-26  Roof Conrecting  2nd Floor
44                          Nail(Box) 2in      25.0       30.0       750.0  2025-12-27  Roof Conrecting  2nd Floor
45                                  Nails       1.0     1200.0      1200.0  2025-12-27  Roof Conrecting  2nd Floor
46                              Acrojack       25.0        2.5      1000.0  2025-12-27  Roof Conrecting  2nd Floor
47                               2/3 Wood      30.0        5.0      2400.0  2025-12-27  Roof Conrecting  2nd Floor
48                   Materials Transport        1.0      600.0       600.0  2025-12-27  Roof Conrecting  2nd Floor
49                               1/6 Wood      18.0      375.0      6750.0  2025-12-27  Roof Conrecting  2nd Floor
50                               1/2 Wood       2.0      100.0       200.0  2025-12-27  Roof Conrecting  2nd Floor
51                    Acrojack Transport        1.0      350.0       350.0  2025-12-27  Roof Conrecting  2nd Floor
52                           Electrician        1.0     9000.0      9000.0  2025-12-27  Roof Conrecting  2nd Floor
53         Electrical Material Transport        2.0      500.0      1000.0  2025-12-28  Roof Conrecting  2nd Floor
54                   Electrical Material        1.0     3100.0      3100.0  2025-12-29  Roof Conrecting  2nd Floor
55         Electrical Material Transport        1.0      300.0       300.0  2025-12-29  Roof Conrecting  2nd Floor
56                     Binding Wire(Roll)       1.0      500.0       500.0  2025-12-29  Roof Conrecting  2nd Floor
57                 Adjusting the Pillars        1.0     1000.0      1000.0  2025-12-29  Roof Conrecting  2nd Floor
58                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-29  Roof Conrecting  2nd Floor
59                               Plumber        1.0    16000.0     16000.0  2025-12-29  Roof Conrecting  2nd Floor
60                   Ali Clearly pathway        1.0     1000.0      1000.0  2025-12-29  Roof Conrecting  2nd Floor
61                                Cement      364.0      480.0    174720.0  2025-12-29  Roof Conrecting  2nd Floor
62                      Cement Transport      364.0       20.0      7280.0  2025-12-29  Roof Conrecting  2nd Floor
63                               1/2 Wood      10.0      100.0      1000.0  2025-12-30  Roof Conrecting  2nd Floor
64                    1/2 Wood Transport        1.0      500.0       500.0  2025-12-30  Roof Conrecting  2nd Floor
65        1/12 Wood Rental and Transport        3.0      400.0       400.0  2025-12-30  Roof Conrecting  2nd Floor
66                 Supervising Contractor       1.0     1500.0      1500.0  2025-12-30  Roof Conrecting  2nd Floor
67                         Stone(6 wheel)       1.0     8000.0      8000.0  2025-12-30  Roof Conrecting  2nd Floor
68                    Stone(6 wheel mini)       1.0     6500.0      6500.0  2025-12-30  Roof Conrecting  2nd Floor
69              Gas for Generator and Tea       1.0     1000.0      1000.0  2025-12-30  Roof Conrecting  2nd Floor
70                           Electrician        1.0      300.0       300.0  2025-12-30  Roof Conrecting  2nd Floor
71                           Concrete Man       1.0    40000.0     40000.0  2025-12-30  Roof Conrecting  2nd Floor
72                       Food for Workers       1.0     2000.0      2000.0  2025-12-30  Roof Conrecting  2nd Floor
73                          Bubacarr Faye       1.0     5000.0      5000.0  2026-01-31  Roof Conrecting  2nd Floor
74                     Gas for Generator        1.0      500.0       500.0  2026-12-31  Roof Conrecting  2nd Floor
75                     Gas for Generator        1.0      500.0       500.0  2026-12-31  Roof Conrecting  2nd Floor
76                             Ali Salary       1.0     5500.0      5500.0  2026-01-07  Roof Conrecting  2nd Floor
77                   Ali Watering Rooftop       1.0     2000.0      2000.0  2026-01-07  Roof Conrecting  2nd Floor
78  Ali Bringing Down Woods and Acrojacks       1.0     3500.0      3500.0  2026-01-15  Roof Conrecting  2nd Floor
79              Roof Materials Transport        1.0    10000.0     10000.0  2026-01-15  Roof Conrecting  2nd Floor
80        Plywood Rental 2Days Extension       60.0       20.0      3600.0  2026-01-18  Roof Conrecting  2nd Floor
81       2/3 Wood Rental 2Days Extension      375.0        5.0      5625.0  2026-01-18  Roof Conrecting  2nd Floor
82       Acrojack Rental 2Days Extension      475.0        2.5      3565.0  2026-01-18  Roof Conrecting  2nd Floor
83                Carpenter Sana Payment        1.0     1500.0      1500.0  2026-01-20  Roof Conrecting  2nd Floor
84                 Bubacarr Faye Payment        1.0    12000.0     12000.0  2026-01-22  Roof Conrecting  2nd Floor
85      Ali moving the Woods  to the Room       1.0      481.0       481.0  2026-01-22  Roof Conrecting  2nd Floor

In [78]:
secondfloor_roof['date'][secondfloor_roof['date'].between('2025-12-05', '2025-12-25')]

0     2025-12-05
1     2025-12-05
2     2025-12-05
3     2025-12-05
4     2025-12-06
5     2025-12-06
6     2025-12-06
7     2025-12-06
8     2025-12-13
9     2025-12-13
10    2025-12-13
11    2025-12-23
12    2025-12-15
13    2025-12-17
14    2025-12-17
15    2025-12-17
16    2025-12-18
17    2025-12-20
18    2025-12-22
19    2025-12-22
20    2025-12-22
21    2025-12-23
22    2025-12-23
23    2025-12-23
24    2025-12-23
25    2025-12-23
26    2025-12-23
27    2025-12-23
28    2025-12-23
29    2025-12-24
30    2025-12-24
31    2025-12-24
32    2025-12-24
Name: date, dtype: str

In [93]:
secondfloor_roof['exchange_rate'] = np.where(secondfloor_roof['date'].between('2025-12-05', '2025-12-25'), 74.25, 0)

In [94]:
secondfloor_roof

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,1/2 wood,100.0,100.0,10000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
1,1/2 Wood Transport,1.0,1000.0,1000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
2,Concrete Nail 2 1/2 in,5.0,200.0,1000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
3,Concrete Nail 2 in,45.0,30.0,1350.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
4,1/2 Wood,35.0,100.0,3500.0,2025-12-06,Roof Conrecting,2nd Floor,74.25
...,...,...,...,...,...,...,...,...
81,2/3 Wood Rental 2Days Extension,375.0,5.0,5625.0,2026-01-18,Roof Conrecting,2nd Floor,0.00
82,Acrojack Rental 2Days Extension,475.0,2.5,3565.0,2026-01-18,Roof Conrecting,2nd Floor,0.00
83,Carpenter Sana Payment,1.0,1500.0,1500.0,2026-01-20,Roof Conrecting,2nd Floor,0.00
84,Bubacarr Faye Payment,1.0,12000.0,12000.0,2026-01-22,Roof Conrecting,2nd Floor,0.00
85,Ali moving the Woods to the Room,1.0,481.0,481.0,2026-01-22,Roof Conrecting,2nd Floor,0.00

In [95]:
secondfloor_roof.loc[secondfloor_roof['date'].between('2025-12-26', '2025-12-28'), 'exchange_rate'] = 74.10

In [96]:
secondfloor_roof.loc[secondfloor_roof['date'].between('2025-12-29', '2026-01-22'), 'exchange_rate'] = 74

In [83]:
secondfloor_roof

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,1/2 wood,100.0,100.0,10000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
1,1/2 Wood Transport,1.0,1000.0,1000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
2,Concrete Nail 2 1/2 in,5.0,200.0,1000.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
3,Concrete Nail 2 in,45.0,30.0,1350.0,2025-12-05,Roof Conrecting,2nd Floor,74.25
4,1/2 Wood,35.0,100.0,3500.0,2025-12-06,Roof Conrecting,2nd Floor,74.25
...,...,...,...,...,...,...,...,...
81,2/3 Wood Rental 2Days Extension,375.0,5.0,5625.0,2026-01-18,Roof Conrecting,2nd Floor,74.00
82,Acrojack Rental 2Days Extension,475.0,2.5,3565.0,2026-01-18,Roof Conrecting,2nd Floor,74.00
83,Carpenter Sana Payment,1.0,1500.0,1500.0,2026-01-20,Roof Conrecting,2nd Floor,74.00
84,Bubacarr Faye Payment,1.0,12000.0,12000.0,2026-01-22,Roof Conrecting,2nd Floor,74.00
85,Ali moving the Woods to the Room,1.0,481.0,481.0,2026-01-22,Roof Conrecting,2nd Floor,74.00

In [97]:
print(secondfloor_roof.to_string())

                                     item  quantity  unit_cost  total_cost       date     sub_category   category  exchange_rate
0                                1/2 wood     100.0      100.0     10000.0 2025-12-05  Roof Conrecting  2nd Floor          74.25
1                     1/2 Wood Transport        1.0     1000.0      1000.0 2025-12-05  Roof Conrecting  2nd Floor          74.25
2                  Concrete Nail 2 1/2 in       5.0      200.0      1000.0 2025-12-05  Roof Conrecting  2nd Floor          74.25
3                      Concrete Nail 2 in      45.0       30.0      1350.0 2025-12-05  Roof Conrecting  2nd Floor          74.25
4                                1/2 Wood      35.0      100.0      3500.0 2025-12-06  Roof Conrecting  2nd Floor          74.25
5                                1/6 Wood       2.0      350.0       700.0 2025-12-06  Roof Conrecting  2nd Floor          74.25
6                         Wood Transport        1.0      500.0       500.0 2025-12-06  Roof Conrecting  2nd Floor          74.25
7                 Carpenter Sana Payment        1.0    15000.0     15000.0 2025-12-06  Roof Conrecting  2nd Floor          74.25
8                                2/3 Wood     350.0        5.0     52500.0 2025-12-13  Roof Conrecting  2nd Floor          74.25
9                                Nail(pkg      17.0      100.0      1700.0 2025-12-13  Roof Conrecting  2nd Floor          74.25
10                   Materials Transport        4.0     2500.0     10000.0 2025-12-13  Roof Conrecting  2nd Floor          74.25
11                Carpenter Sana Payment        1.0     5000.0      5000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
12                              Acrojack      400.0        2.5     27000.0 2025-12-15  Roof Conrecting  2nd Floor          74.25
13                      Generator Repair        1.0      600.0       600.0 2025-12-17  Roof Conrecting  2nd Floor          74.25
14                   Generator Transport        2.0      300.0       600.0 2025-12-17  Roof Conrecting  2nd Floor          74.25
15                     Gas for Generator        1.0      500.0       500.0 2025-12-17  Roof Conrecting  2nd Floor          74.25
16                        Plywood Rental       65.0       20.0     32500.0 2025-12-18  Roof Conrecting  2nd Floor          74.25
17                               Nail(kg)       8.0      100.0       800.0 2025-12-20  Roof Conrecting  2nd Floor          74.25
18                           Plywood 12mm      30.0     1700.0     51000.0 2025-12-22  Roof Conrecting  2nd Floor          74.25
19                              Acrojack       50.0        2.5       400.0 2025-12-22  Roof Conrecting  2nd Floor          74.25
20                   Materials Transport        1.0     2000.0      2000.0 2025-12-22  Roof Conrecting  2nd Floor          74.25
21                          Iron Rod 10mm     500.0      330.0    165000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
22                          Iron Rod 12mm      30.0      500.0     15000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
23                           Iron Rod 6mm      35.0      130.0      4550.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
24                           Binding Wire       3.0      400.0      1200.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
25                   Materials Transport        1.0     5000.0      5000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
26                Carpenter Sana Payment        1.0     5000.0      5000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
27                       Iron Man Payment       1.0    11000.0     11000.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
28                      Wave Transfer Fee       1.0      110.0       110.0 2025-12-23  Roof Conrecting  2nd Floor          74.25
29                           Plywood 12mm      12.0     1700.0     20400.0 2025-12-24  Roof Conrecting  2nd Floor          74.25
30                     Plywood Transport        1.0      500.0       500.0 2025-12-24  Roof Conrecting  2nd Floor          74.25
31                              10m Rope        1.0      500.0       500.0 2025-12-24  Roof Conrecting  2nd Floor          74.25
32                                   Poly       1.0      200.0       200.0 2025-12-24  Roof Conrecting  2nd Floor          74.25
33                    Plumbing Materials        1.0    19132.0     19000.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
34                   Materials Transport        1.0      300.0       300.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
35                           Plywood 12mm      10.0     1700.0     17000.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
36                             Cardboard        2.0      400.0       800.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
37                   Materials Transport        1.0      300.0       300.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
38                   Electrical Materials       1.0    12475.0     12475.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
39         Electrical Material Transport        1.0      300.0       300.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
40                             Wash Stone       3.0    14000.0     42000.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
41                           Asphalt 19cu       1.0    94500.0     94500.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
42                                   Sand       2.0     8000.0     16000.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
43                           Buba Tunkara       1.0     8000.0      8000.0 2025-12-26  Roof Conrecting  2nd Floor          74.10
44                          Nail(Box) 2in      25.0       30.0       750.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
45                                  Nails       1.0     1200.0      1200.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
46                              Acrojack       25.0        2.5      1000.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
47                               2/3 Wood      30.0        5.0      2400.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
48                   Materials Transport        1.0      600.0       600.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
49                               1/6 Wood      18.0      375.0      6750.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
50                               1/2 Wood       2.0      100.0       200.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
51                    Acrojack Transport        1.0      350.0       350.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
52                           Electrician        1.0     9000.0      9000.0 2025-12-27  Roof Conrecting  2nd Floor          74.10
53         Electrical Material Transport        2.0      500.0      1000.0 2025-12-28  Roof Conrecting  2nd Floor          74.10
54                   Electrical Material        1.0     3100.0      3100.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
55         Electrical Material Transport        1.0      300.0       300.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
56                     Binding Wire(Roll)       1.0      500.0       500.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
57                 Adjusting the Pillars        1.0     1000.0      1000.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
58                       Iron Man Payment       1.0    11000.0     11000.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
59                               Plumber        1.0    16000.0     16000.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
60                   Ali Clearly pathway        1.0     1000.0      1000.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
61                                Cement      364.0      480.0    174720.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
62                      Cement Transport      364.0       20.0      7280.0 2025-12-29  Roof Conrecting  2nd Floor          74.00
63                               1/2 Wood      10.0      100.0      1000.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
64                    1/2 Wood Transport        1.0      500.0       500.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
65        1/12 Wood Rental and Transport        3.0      400.0       400.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
66                 Supervising Contractor       1.0     1500.0      1500.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
67                         Stone(6 wheel)       1.0     8000.0      8000.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
68                    Stone(6 wheel mini)       1.0     6500.0      6500.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
69              Gas for Generator and Tea       1.0     1000.0      1000.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
70                           Electrician        1.0      300.0       300.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
71                           Concrete Man       1.0    40000.0     40000.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
72                       Food for Workers       1.0     2000.0      2000.0 2025-12-30  Roof Conrecting  2nd Floor          74.00
73                          Bubacarr Faye       1.0     5000.0      5000.0 2025-12-31  Roof Conrecting  2nd Floor          74.00
74                     Gas for Generator        1.0      500.0       500.0 2025-12-31  Roof Conrecting  2nd Floor          74.00
75                     Gas for Generator        1.0      500.0       500.0 2025-12-31  Roof Conrecting  2nd Floor          74.00
76                             Ali Salary       1.0     5500.0      5500.0 2026-01-07  Roof Conrecting  2nd Floor          74.00
77                   Ali Watering Rooftop       1.0     2000.0      2000.0 2026-01-07  Roof Conrecting  2nd Floor          74.00
78  Ali Bringing Down Woods and Acrojacks       1.0     3500.0      3500.0 2026-01-15  Roof Conrecting  2nd Floor          74.00
79              Roof Materials Transport        1.0    10000.0     10000.0 2026-01-15  Roof Conrecting  2nd Floor          74.00
80        Plywood Rental 2Days Extension       60.0       20.0      3600.0 2026-01-18  Roof Conrecting  2nd Floor          74.00
81       2/3 Wood Rental 2Days Extension      375.0        5.0      5625.0 2026-01-18  Roof Conrecting  2nd Floor          74.00
82       Acrojack Rental 2Days Extension      475.0        2.5      3565.0 2026-01-18  Roof Conrecting  2nd Floor          74.00
83                Carpenter Sana Payment        1.0     1500.0      1500.0 2026-01-20  Roof Conrecting  2nd Floor          74.00
84                 Bubacarr Faye Payment        1.0    12000.0     12000.0 2026-01-22  Roof Conrecting  2nd Floor          74.00
85      Ali moving the Woods  to the Room       1.0      481.0       481.0 2026-01-22  Roof Conrecting  2nd Floor          74.00

In [98]:
# secondfloor_roof['date'] = np.select([secondfloor_roof['date'] == '2026-01-31',  
#                                       secondfloor_roof['date'] == '2026-12-31'], ['2025-12-31', '2025-12-31'], 
#                                                    default =secondfloor_roof['date'])

In [91]:
secondfloor_roof['date'] = pd.to_datetime(secondfloor_roof['date'])

In [92]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           86 non-null     str
 1   quantity       86 non-null     float64
 2   unit_cost      86 non-null     float64
 3   total_cost     86 non-null     float64
 4   date           86 non-null     datetime64[us]
 5   sub_category   86 non-null     str
 6   category       86 non-null     str
 7   exchange_rate  86 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 5.5 KB

In [105]:
#secondfloor_roof['item'] = 
secondfloor_roof['item'] = np.where(secondfloor_roof['item'] == '2/3 Wood', '2/3 Wood Rental', secondfloor_roof['item'])

In [111]:
secondfloor_roof.at[53, 'item'] = 'Electrical Materials'

In [123]:
secondfloor_roof.at[9, 'item'] = 'Nail(pkg)'

In [137]:
df = secondfloor_roof[secondfloor_roof['item'] == 'Acrojack ']

In [141]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
12,Arcojack Rental,400.0,2.5,27000.0,2025-12-15,Roof Conrecting,2nd Floor,74.25
19,Arcojack Rental,50.0,2.5,400.0,2025-12-22,Roof Conrecting,2nd Floor,74.25
46,Arcojack Rental,25.0,2.5,1000.0,2025-12-27,Roof Conrecting,2nd Floor,74.10

In [145]:
secondfloor_roof['item'] = np.where(secondfloor_roof['item'] == 'Acrojack ', 'Arcojack Rental', secondfloor_roof['item'])

In [146]:
secondfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           86 non-null     str
 1   quantity       86 non-null     float64
 2   unit_cost      86 non-null     float64
 3   total_cost     86 non-null     float64
 4   date           86 non-null     datetime64[us]
 5   sub_category   86 non-null     str
 6   category       86 non-null     str
 7   exchange_rate  86 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 5.5 KB

In [5]:
print(secondfloor_roof.to_string())

                                     item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                                1/2 wood     100.0      100.0     10000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
1                     1/2 Wood Transport        1.0     1000.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
2                  Concrete Nail 2 1/2 in       5.0      200.0      1000.0  2025-12-05  Roof Concreting  2nd Floor          74.25
3                      Concrete Nail 2 in      45.0       30.0      1350.0  2025-12-05  Roof Concreting  2nd Floor          74.25
4                                1/2 Wood      35.0      100.0      3500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
5                                1/6 Wood       2.0      350.0       700.0  2025-12-06  Roof Concreting  2nd Floor          74.25
6                         Wood Transport        1.0      500.0       500.0  2025-12-06  Roof Concreting  2nd Floor          74.25
7                 Carpenter Sana Payment        1.0    15000.0     15000.0  2025-12-06  Roof Concreting  2nd Floor          74.25
8                         2/3 Wood Rental     350.0        5.0     52500.0  2025-12-13  Roof Concreting  2nd Floor          74.25
9                               Nail(pkg)      17.0      100.0      1700.0  2025-12-13  Roof Concreting  2nd Floor          74.25
10                   Materials Transport        4.0     2500.0     10000.0  2025-12-13  Roof Concreting  2nd Floor          74.25
11                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
12                        Arcojack Rental     400.0        2.5     27000.0  2025-12-15  Roof Concreting  2nd Floor          74.25
13                      Generator Repair        1.0      600.0       600.0  2025-12-17  Roof Concreting  2nd Floor          74.25
14                   Generator Transport        2.0      300.0       600.0  2025-12-17  Roof Concreting  2nd Floor          74.25
15                     Gas for Generator        1.0      500.0       500.0  2025-12-17  Roof Concreting  2nd Floor          74.25
16                        Plywood Rental       65.0       20.0     32500.0  2025-12-18  Roof Concreting  2nd Floor          74.25
17                               Nail(kg)       8.0      100.0       800.0  2025-12-20  Roof Concreting  2nd Floor          74.25
18                           Plywood 12mm      30.0     1700.0     51000.0  2025-12-22  Roof Concreting  2nd Floor          74.25
19                        Arcojack Rental      50.0        2.5       400.0  2025-12-22  Roof Concreting  2nd Floor          74.25
20                   Materials Transport        1.0     2000.0      2000.0  2025-12-22  Roof Concreting  2nd Floor          74.25
21                          Iron Rod 10mm     500.0      330.0    165000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
22                          Iron Rod 12mm      30.0      500.0     15000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
23                           Iron Rod 6mm      35.0      130.0      4550.0  2025-12-23  Roof Concreting  2nd Floor          74.25
24                           Binding Wire       3.0      400.0      1200.0  2025-12-23  Roof Concreting  2nd Floor          74.25
25                   Materials Transport        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
26                Carpenter Sana Payment        1.0     5000.0      5000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
27                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-23  Roof Concreting  2nd Floor          74.25
28                      Wave Transfer Fee       1.0      110.0       110.0  2025-12-23  Roof Concreting  2nd Floor          74.25
29                           Plywood 12mm      12.0     1700.0     20400.0  2025-12-24  Roof Concreting  2nd Floor          74.25
30                     Plywood Transport        1.0      500.0       500.0  2025-12-24  Roof Concreting  2nd Floor          74.25
31                              10m Rope        1.0      500.0       500.0  2025-12-24  Roof Concreting  2nd Floor          74.25
32                                   Poly       1.0      200.0       200.0  2025-12-24  Roof Concreting  2nd Floor          74.25
33                    Plumbing Materials        1.0    19132.0     19000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
34                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
35                           Plywood 12mm      10.0     1700.0     17000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
36                             Cardboard        2.0      400.0       800.0  2025-12-26  Roof Concreting  2nd Floor          74.10
37                   Materials Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
38                   Electrical Materials       1.0    12475.0     12475.0  2025-12-26  Roof Concreting  2nd Floor          74.10
39         Electrical Material Transport        1.0      300.0       300.0  2025-12-26  Roof Concreting  2nd Floor          74.10
40                             Wash Stone       3.0    14000.0     42000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
41                           Asphalt 19cu       1.0    94500.0     94500.0  2025-12-26  Roof Concreting  2nd Floor          74.10
42                                   Sand       2.0     8000.0     16000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
43                           Buba Tunkara       1.0     8000.0      8000.0  2025-12-26  Roof Concreting  2nd Floor          74.10
44                          Nail(Box) 2in      25.0       30.0       750.0  2025-12-27  Roof Concreting  2nd Floor          74.10
45                                  Nails       1.0     1200.0      1200.0  2025-12-27  Roof Concreting  2nd Floor          74.10
46                        Arcojack Rental      25.0        2.5      1000.0  2025-12-27  Roof Concreting  2nd Floor          74.10
47                        2/3 Wood Rental      30.0        5.0      2400.0  2025-12-27  Roof Concreting  2nd Floor          74.10
48                   Materials Transport        1.0      600.0       600.0  2025-12-27  Roof Concreting  2nd Floor          74.10
49                               1/6 Wood      18.0      375.0      6750.0  2025-12-27  Roof Concreting  2nd Floor          74.10
50                               1/2 Wood       2.0      100.0       200.0  2025-12-27  Roof Concreting  2nd Floor          74.10
51                    Acrojack Transport        1.0      350.0       350.0  2025-12-27  Roof Concreting  2nd Floor          74.10
52                           Electrician        1.0     9000.0      9000.0  2025-12-27  Roof Concreting  2nd Floor          74.10
53                   Electrical Materials       2.0      500.0      1000.0  2025-12-28  Roof Concreting  2nd Floor          74.10
54                   Electrical Material        1.0     3100.0      3100.0  2025-12-29  Roof Concreting  2nd Floor          74.00
55         Electrical Material Transport        1.0      300.0       300.0  2025-12-29  Roof Concreting  2nd Floor          74.00
56                     Binding Wire(Roll)       1.0      500.0       500.0  2025-12-29  Roof Concreting  2nd Floor          74.00
57                 Adjusting the Pillars        1.0     1000.0      1000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
58                       Iron Man Payment       1.0    11000.0     11000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
59                               Plumber        1.0    16000.0     16000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
60                   Ali Clearly pathway        1.0     1000.0      1000.0  2025-12-29  Roof Concreting  2nd Floor          74.00
61                                Cement      364.0      480.0    174720.0  2025-12-29  Roof Concreting  2nd Floor          74.00
62                      Cement Transport      364.0       20.0      7280.0  2025-12-29  Roof Concreting  2nd Floor          74.00
63                               1/2 Wood      10.0      100.0      1000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
64                    1/2 Wood Transport        1.0      500.0       500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
65        1/12 Wood Rental and Transport        3.0      400.0       400.0  2025-12-30  Roof Concreting  2nd Floor          74.00
66                 Supervising Contractor       1.0     1500.0      1500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
67                         Stone(6 wheel)       1.0     8000.0      8000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
68                    Stone(6 wheel mini)       1.0     6500.0      6500.0  2025-12-30  Roof Concreting  2nd Floor          74.00
69              Gas for Generator and Tea       1.0     1000.0      1000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
70                           Electrician        1.0      300.0       300.0  2025-12-30  Roof Concreting  2nd Floor          74.00
71                           Concrete Man       1.0    40000.0     40000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
72                       Food for Workers       1.0     2000.0      2000.0  2025-12-30  Roof Concreting  2nd Floor          74.00
73                          Bubacarr Faye       1.0     5000.0      5000.0  2025-12-31  Roof Concreting  2nd Floor          74.00
74                     Gas for Generator        1.0      500.0       500.0  2025-12-31  Roof Concreting  2nd Floor          74.00
75                     Gas for Generator        1.0      500.0       500.0  2025-12-31  Roof Concreting  2nd Floor          74.00
76                             Ali Salary       1.0     5500.0      5500.0  2026-01-07  Roof Concreting  2nd Floor          74.00
77                   Ali Watering Rooftop       1.0     2000.0      2000.0  2026-01-07  Roof Concreting  2nd Floor          74.00
78  Ali Bringing Down Woods and Acrojacks       1.0     3500.0      3500.0  2026-01-15  Roof Concreting  2nd Floor          74.00
79              Roof Materials Transport        1.0    10000.0     10000.0  2026-01-15  Roof Concreting  2nd Floor          74.00
80        Plywood Rental 2Days Extension       60.0       20.0      3600.0  2026-01-18  Roof Concreting  2nd Floor          74.00
81       2/3 Wood Rental 2Days Extension      375.0        5.0      5625.0  2026-01-18  Roof Concreting  2nd Floor          74.00
82       Acrojack Rental 2Days Extension      475.0        2.5      3565.0  2026-01-18  Roof Concreting  2nd Floor          74.00
83                Carpenter Sana Payment        1.0     1500.0      1500.0  2026-01-20  Roof Concreting  2nd Floor          74.00
84                 Bubacarr Faye Payment        1.0    12000.0     12000.0  2026-01-22  Roof Concreting  2nd Floor          74.00
85      Ali moving the Woods  to the Room       1.0      481.0       481.0  2026-01-22  Roof Concreting  2nd Floor          74.00

In [6]:
secondfloor_roof.to_csv('ParadiseView/out/df_secondfloor_roof.csv', index=False)

In [3]:
pd.read_csv('ParadiseView/out/df_secondfloor_roof.csv')