In [1]:
import pandas as pd
import numpy as np

In [175]:
thirdfloor_bricks = pd.read_csv('ParadiseView/Paradise View/3rd_4th Floorbricks.csv')

In [176]:
thirdfloor_bricks.drop(columns=(thirdfloor_bricks.loc[:, 'Unnamed: 6':'Unnamed: 11']), inplace=True)

In [177]:
thirdfloor_bricks.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ITEM           36 non-null     str
 1   QUALITY        35 non-null     str
 2   UNIT PRICE(D)  35 non-null     str
 3   COST(D)        36 non-null     str
 4   FLOOR          35 non-null     str
 5   DATE           35 non-null     str
dtypes: str(6)
memory usage: 3.0 KB

In [178]:
thirdfloor_bricks = thirdfloor_bricks.dropna(thresh=3)

In [179]:
thirdfloor_bricks.columns.values

<StringArray>
['ITEM', 'QUALITY ', 'UNIT PRICE(D)', 'COST(D)', 'FLOOR', 'DATE']
Length: 6, dtype: str

In [180]:
thirdfloor_bricks.columns = thirdfloor_bricks.columns.str.lower()

In [181]:
thirdfloor_bricks.columns

Index(['item', 'quality ', 'unit price(d)', 'cost(d)', 'floor', 'date'], dtype='str')

In [182]:
thirdfloor_bricks.rename(columns={'quality ': 'quantity', 'unit price(d)': 'unit_cost', 'cost(d)': 'total_cost', 'floor': 'category'}, inplace=True)

In [183]:
thirdfloor_bricks.columns

Index(['item', 'quantity', 'unit_cost', 'total_cost', 'category', 'date'], dtype='str')

In [184]:
thirdfloor_bricks['date'] = pd.to_datetime(thirdfloor_bricks['date'])

C:\Users\mrsuf\AppData\Local\Temp\ipykernel_33788\1260041865.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  thirdfloor_bricks['date'] = pd.to_datetime(thirdfloor_bricks['date'])

In [186]:
df_thirdfloor_bricks = thirdfloor_bricks[thirdfloor_bricks['date'] <= pd.to_datetime('2025-10-29')]

In [188]:
df_fourthfloor_bricks = thirdfloor_bricks[thirdfloor_bricks['date'] > pd.to_datetime('2025-10-29')]

In [189]:
df_fourthfloor_bricks

                  item quantity  unit_cost total_cost   category       date
15             Cement       200     415.00     83,000  4th Floor 2026-03-31
16    Cement Transport      200      30.00      6,000  4th Floor 2026-03-31
17      Shovel Repair         3     100.00        300  4th Floor 2026-04-01
18   Gas for Generator        1     400.00        400  4th Floor 2026-04-01
19                Sand        1   8,000.00      8,000  4th Floor 2026-04-02
20       Sand Wave Fee        1      80.00         80  4th Floor 2026-04-02
21                Sand        1   8,000.00      8,000  4th Floor 2026-04-04
22   Gas for Generator        2     400.00        800  4th Floor 2026-04-08
23                Sand        1   8,000.00      8,000  4th Floor 2026-04-10
24       Sand Wave Fee        1      80.00         80  4th Floor 2026-04-10
25  Brick Molding Cost        1  15,000.00     15,000  4th Floor 2026-04-11
26                Sand        1   8,000.00      8,000  4th Floor 2026-04-11
27   Gas for Generator        1     400.00        400  4th Floor 2026-04-14
28   Gas for Generator        1     400.00        400  4th Floor 2026-04-16
29  Brick Molding Cost        1   5,000.00      5,000  4th Floor 2026-04-16
30                Sand        1   8,000.00      8,000  4th Floor 2026-04-17
31            Wave Fee        1      80.00         80  4th Floor 2026-04-17
32                Sand        1   8,000.00      8,000  4th Floor 2026-04-24
33   Gas for Generator        1     400.00        400  4th Floor 2026-04-24
34  Brick Molding Cost        1  16,066.00     16,066  4th Floor 2026-04-28

In [190]:
df_thirdfloor_bricks

                  item quantity unit_cost total_cost   category       date
0              Cement       100    480.00     48,000  3rd Floot 2025-10-14
1     Cement Transport      100     20.00      2,000  3rd Floot 2025-10-14
2                 Sand        1  8,500.00      8,500  3rd Floot 2025-10-14
3                 Sand        1  8,500.00      8,500  3rd Floot 2025-10-15
4                 Sand        1  8,500.00      8,500  3rd Floot 2025-10-17
5   Brick Molding Cost    2,910      6.00     17,460  3rd Floot 2025-10-20
6              Cement       100    480.00     48,000  3rd Floot 2025-10-20
7     Cement Transport      100     20.00      2,000  3rd Floot 2025-10-20
8                 Sand        1  8,500.00      8,500  3rd Floot 2025-10-21
9                 Sand        1  8,500.00      8,500  3rd Floot 2025-10-23
10  Brick Molding Cost    2,766      6.00     16,600  3rd Floot 2025-10-27
11             Cement        50    480.00     24,000  3rd Floot 2025-10-27
12    Cement Transport       50     20.00      1,000  3rd Floot 2025-10-27
13                Sand        1  8,500.00      8,500  3rd Floot 2025-10-27
14  Brick Molding Cost    1,400      6.00      8,400  3rd Floot 2025-10-29

In [191]:
df_thirdfloor_bricks['category'] = '3rd Floor'

In [192]:
df_thirdfloor_bricks['total_cost'] = df_thirdfloor_bricks['total_cost'].str.replace(',', '').astype('float64')

In [193]:
df_thirdfloor_bricks['unit_cost'] = df_thirdfloor_bricks['unit_cost'].str.replace(',', '').astype('float64')

In [195]:
df_thirdfloor_bricks['quantity'] = df_thirdfloor_bricks['quantity'].str.replace(',', '').astype('float64')

In [196]:
df_thirdfloor_bricks['sub_category'] = 'Brick Molding'

In [197]:
df_thirdfloor_bricks = df_thirdfloor_bricks.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [198]:
df_thirdfloor_bricks.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   item          15 non-null     str
 1   quantity      15 non-null     float64
 2   unit_cost     15 non-null     float64
 3   total_cost    15 non-null     float64
 4   date          15 non-null     datetime64[us]
 5   sub_category  15 non-null     str
 6   category      15 non-null     str
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 972.0 bytes

In [199]:
print(df_thirdfloor_bricks.to_string())

                  item  quantity  unit_cost  total_cost       date   sub_category   category
0              Cement      100.0      480.0     48000.0 2025-10-14  Brick Molding  3rd Floor
1     Cement Transport     100.0       20.0      2000.0 2025-10-14  Brick Molding  3rd Floor
2                 Sand       1.0     8500.0      8500.0 2025-10-14  Brick Molding  3rd Floor
3                 Sand       1.0     8500.0      8500.0 2025-10-15  Brick Molding  3rd Floor
4                 Sand       1.0     8500.0      8500.0 2025-10-17  Brick Molding  3rd Floor
5   Brick Molding Cost    2910.0        6.0     17460.0 2025-10-20  Brick Molding  3rd Floor
6              Cement      100.0      480.0     48000.0 2025-10-20  Brick Molding  3rd Floor
7     Cement Transport     100.0       20.0      2000.0 2025-10-20  Brick Molding  3rd Floor
8                 Sand       1.0     8500.0      8500.0 2025-10-21  Brick Molding  3rd Floor
9                 Sand       1.0     8500.0      8500.0 2025-10-23  Brick Molding  3rd Floor
10  Brick Molding Cost    2766.0        6.0     16600.0 2025-10-27  Brick Molding  3rd Floor
11             Cement       50.0      480.0     24000.0 2025-10-27  Brick Molding  3rd Floor
12    Cement Transport      50.0       20.0      1000.0 2025-10-27  Brick Molding  3rd Floor
13                Sand       1.0     8500.0      8500.0 2025-10-27  Brick Molding  3rd Floor
14  Brick Molding Cost    1400.0        6.0      8400.0 2025-10-29  Brick Molding  3rd Floor

In [202]:
df_thirdfloor_bricks.to_csv('ParadiseView/out/df_thirdfloor_bricks.csv', index=False)

In [47]:
df_thirdfloor_bricks = pd.read_csv('ParadiseView/out/df_thirdfloor_bricks.csv')

In [49]:
df_thirdfloor_bricks['exchange_rate'] = 73.75

In [58]:
df_thirdfloor_bricks.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           15 non-null     str
 1   quantity       15 non-null     float64
 2   unit_cost      15 non-null     float64
 3   total_cost     15 non-null     float64
 4   date           15 non-null     str
 5   sub_category   15 non-null     str
 6   category       15 non-null     str
 7   exchange_rate  15 non-null     float64
dtypes: float64(4), str(4)
memory usage: 1.1 KB

In [59]:
df_thirdfloor_bricks['item'] == 'Sand'

0     False
1     False
2      True
3      True
4      True
5     False
6     False
7     False
8      True
9      True
10    False
11    False
12    False
13     True
14    False
Name: item, dtype: bool

In [63]:
df_thirdfloor_bricks['item'] = np.where(df_thirdfloor_bricks['item'] == 'Sand', 'Sand (10 Wheel)', df_thirdfloor_bricks['item'])

In [66]:
df_thirdfloor_bricks.to_csv('ParadiseView/out/df_thirdfloor_bricks.csv', index=False)

In [67]:
pd.read_csv('ParadiseView/out/df_thirdfloor_bricks.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cement,100.0,480.0,48000.0,2025-10-14,Brick Molding,3rd Floor,73.75
1,Cement Transport,100.0,20.0,2000.0,2025-10-14,Brick Molding,3rd Floor,73.75
2,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-14,Brick Molding,3rd Floor,73.75
3,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-15,Brick Molding,3rd Floor,73.75
4,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-17,Brick Molding,3rd Floor,73.75
5,Brick Molding Cost,2910.0,6.0,17460.0,2025-10-20,Brick Molding,3rd Floor,73.75
6,Cement,100.0,480.0,48000.0,2025-10-20,Brick Molding,3rd Floor,73.75
7,Cement Transport,100.0,20.0,2000.0,2025-10-20,Brick Molding,3rd Floor,73.75
8,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-21,Brick Molding,3rd Floor,73.75
9,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-23,Brick Molding,3rd Floor,73.75
10,Brick Molding Cost,2766.0,6.0,16600.0,2025-10-27,Brick Molding,3rd Floor,73.75
11,Cement,50.0,480.0,24000.0,2025-10-27,Brick Molding,3rd Floor,73.75
12,Cement Transport,50.0,20.0,1000.0,2025-10-27,Brick Molding,3rd Floor,73.75
13,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-27,Brick Molding,3rd Floor,73.75
14,Brick Molding Cost,1400.0,6.0,8400.0,2025-10-29,Brick Molding,3rd Floor,73.75

In [62]:
print(df_thirdfloor_bricks.to_string())

                  item  quantity  unit_cost  total_cost        date   sub_category   category  exchange_rate
0              Cement      100.0      480.0     48000.0  2025-10-14  Brick Molding  3rd Floor          73.75
1     Cement Transport     100.0       20.0      2000.0  2025-10-14  Brick Molding  3rd Floor          73.75
2      Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-14  Brick Molding  3rd Floor          73.75
3      Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-15  Brick Molding  3rd Floor          73.75
4      Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-17  Brick Molding  3rd Floor          73.75
5   Brick Molding Cost    2910.0        6.0     17460.0  2025-10-20  Brick Molding  3rd Floor          73.75
6              Cement      100.0      480.0     48000.0  2025-10-20  Brick Molding  3rd Floor          73.75
7     Cement Transport     100.0       20.0      2000.0  2025-10-20  Brick Molding  3rd Floor          73.75
8      Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-21  Brick Molding  3rd Floor          73.75
9      Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-23  Brick Molding  3rd Floor          73.75
10  Brick Molding Cost    2766.0        6.0     16600.0  2025-10-27  Brick Molding  3rd Floor          73.75
11             Cement       50.0      480.0     24000.0  2025-10-27  Brick Molding  3rd Floor          73.75
12    Cement Transport      50.0       20.0      1000.0  2025-10-27  Brick Molding  3rd Floor          73.75
13     Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-27  Brick Molding  3rd Floor          73.75
14  Brick Molding Cost    1400.0        6.0      8400.0  2025-10-29  Brick Molding  3rd Floor          73.75

In [204]:
# Fourth Floor

In [205]:
df_fourthfloor_bricks

                  item quantity  unit_cost total_cost   category       date
15             Cement       200     415.00     83,000  4th Floor 2026-03-31
16    Cement Transport      200      30.00      6,000  4th Floor 2026-03-31
17      Shovel Repair         3     100.00        300  4th Floor 2026-04-01
18   Gas for Generator        1     400.00        400  4th Floor 2026-04-01
19                Sand        1   8,000.00      8,000  4th Floor 2026-04-02
20       Sand Wave Fee        1      80.00         80  4th Floor 2026-04-02
21                Sand        1   8,000.00      8,000  4th Floor 2026-04-04
22   Gas for Generator        2     400.00        800  4th Floor 2026-04-08
23                Sand        1   8,000.00      8,000  4th Floor 2026-04-10
24       Sand Wave Fee        1      80.00         80  4th Floor 2026-04-10
25  Brick Molding Cost        1  15,000.00     15,000  4th Floor 2026-04-11
26                Sand        1   8,000.00      8,000  4th Floor 2026-04-11
27   Gas for Generator        1     400.00        400  4th Floor 2026-04-14
28   Gas for Generator        1     400.00        400  4th Floor 2026-04-16
29  Brick Molding Cost        1   5,000.00      5,000  4th Floor 2026-04-16
30                Sand        1   8,000.00      8,000  4th Floor 2026-04-17
31            Wave Fee        1      80.00         80  4th Floor 2026-04-17
32                Sand        1   8,000.00      8,000  4th Floor 2026-04-24
33   Gas for Generator        1     400.00        400  4th Floor 2026-04-24
34  Brick Molding Cost        1  16,066.00     16,066  4th Floor 2026-04-28

In [5]:
df_fourthfloor_bricks.to_csv('ParadiseView/out/df_fourthfloor_bricks.csv', index=False)

In [10]:
df_fourthfloor_bricks = pd.read_csv('ParadiseView/out/df_fourthfloor_bricks.csv')

In [16]:
df_fourthfloor_bricks['date'] = pd.to_datetime(df_fourthfloor_bricks['date'])

In [ ]:
df_fourthfloor_bricks['unit_cost'] = df_fourthfloor_bricks['unit_cost'].str.replace(',', '').astype('float64')

In [28]:
df_fourthfloor_bricks['total_cost'] = df_fourthfloor_bricks['total_cost'].str.replace(',', '').astype('float64')

In [32]:
df_fourthfloor_bricks['quantity'] = df_fourthfloor_bricks['quantity'].astype('float64')

In [33]:
df_fourthfloor_bricks['sub_category'] = 'Brick Molding'

In [37]:
df_fourthfloor_bricks = df_fourthfloor_bricks.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [39]:
df_fourthfloor_bricks['exchange_rate'] = 69.50

In [42]:
df_fourthfloor_bricks.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           20 non-null     str
 1   quantity       20 non-null     float64
 2   unit_cost      20 non-null     float64
 3   total_cost     20 non-null     float64
 4   date           20 non-null     datetime64[us]
 5   sub_category   20 non-null     str
 6   category       20 non-null     str
 7   exchange_rate  20 non-null     float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 1.4 KB

In [43]:
df_fourthfloor_bricks.to_csv('ParadiseView/out.dfdf_fourthfloor_bricks.csv', index=False)

In [44]:
pd.read_csv('ParadiseView/out.dfdf_fourthfloor_bricks.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cement,200.0,415.0,83000.0,2026-03-31,Brick Molding,4th Floor,69.5
1,Cement Transport,200.0,30.0,6000.0,2026-03-31,Brick Molding,4th Floor,69.5
2,Shovel Repair,3.0,100.0,300.0,2026-04-01,Brick Molding,4th Floor,69.5
3,Gas for Generator,1.0,400.0,400.0,2026-04-01,Brick Molding,4th Floor,69.5
4,Sand,1.0,8000.0,8000.0,2026-04-02,Brick Molding,4th Floor,69.5
5,Sand Wave Fee,1.0,80.0,80.0,2026-04-02,Brick Molding,4th Floor,69.5
6,Sand,1.0,8000.0,8000.0,2026-04-04,Brick Molding,4th Floor,69.5
7,Gas for Generator,2.0,400.0,800.0,2026-04-08,Brick Molding,4th Floor,69.5
8,Sand,1.0,8000.0,8000.0,2026-04-10,Brick Molding,4th Floor,69.5
9,Sand Wave Fee,1.0,80.0,80.0,2026-04-10,Brick Molding,4th Floor,69.5
10,Brick Molding Cost,1.0,15000.0,15000.0,2026-04-11,Brick Molding,4th Floor,69.5
11,Sand,1.0,8000.0,8000.0,2026-04-11,Brick Molding,4th Floor,69.5
12,Gas for Generator,1.0,400.0,400.0,2026-04-14,Brick Molding,4th Floor,69.5
13,Gas for Generator,1.0,400.0,400.0,2026-04-16,Brick Molding,4th Floor,69.5
14,Brick Molding Cost,1.0,5000.0,5000.0,2026-04-16,Brick Molding,4th Floor,69.5
15,Sand,1.0,8000.0,8000.0,2026-04-17,Brick Molding,4th Floor,69.5
16,Wave Fee,1.0,80.0,80.0,2026-04-17,Brick Molding,4th Floor,69.5
17,Sand,1.0,8000.0,8000.0,2026-04-24,Brick Molding,4th Floor,69.5
18,Gas for Generator,1.0,400.0,400.0,2026-04-24,Brick Molding,4th Floor,69.5
19,Brick Molding Cost,1.0,16066.0,16066.0,2026-04-28,Brick Molding,4th Floor,69.5